#+options: toc:nil  ^:nil
#+begin_export md
---
layout: post
title: "内观禅修感悟"
date: 2018-05-10
tags: 
    - 佛学
---
#+end_export

#+TOC: headlines 1
* 内观禅修感悟不可忽略行禅

** 第一周：

行禅：平时懒散惯了，刚去的第一周完全没有感觉，虽然人在禅修，但是妄念一刻不停。只要一有声音或人影走过，我就会无法自控的扭头去看，完全没有正念。第一天行禅时我的旧疾腰痛就发作了，刺骨的痛，几乎每走几步就要调整一下姿式才能继续走下去，但是我仍咬牙坚持着，一直走完一个小时，那时候坐禅就是最好的休息。

坐禅：坐禅的心也是散乱的，很难长时间观照目标。每一小时的坐禅，基本上是半个小时昏沉半个小时妄想。妄想的力量是如此强大，如排山倒海之势将我淹没，这样每天一小时一小时的在昏沉妄想中挣扎，常常令我极度沮丧。

小参时，禅师总是会微笑的说，不要气馁，继续努力。情况是如此的糟糕，我唯一能做的就是继续努力，踏踏实实的行禅、坐禅，什么也不想。

** 第二周：

行禅：有一天早上醒来，我象往常一样行禅时，突然发现我的腰痛消失了，无论怎么走一点痛的感觉都没有了，这真是太神奇了，禅修真的能治病，这可是困扰我近十年的旧疾，从生下孩子就一直没好过。在激动欣喜中，这一天我格外的精进。行禅时觉知越来越强。第二天，我发现自己走起路来犹如在云中漫步，非常的轻柔，脚上的觉知象棉花一样的柔软，很舒服，走了一天下来，一点都不累，且越走越精神。隆藏法师告诉我，说我走出了轻安，当出现轻安时，走多久都不会累。并且提醒我，要更细的去觉知，走出柔软的力量。

坐禅：坐禅时仍然很糟糕，昏沉妄想仍然非常有力。经常会忆起许多年前早已遗忘的一个人或一件事，并沉溺许久，有如再次亲历。我对自己说，一切都是无常的，这个念头也将会消失。

** 第三周：

行禅：上一周就曾出现过行禅时感觉到地板轻微晃动的状况，到这一周时晃动的感觉越来越真切，我每走一步，只要把觉知放在脚上，就会如此真实的感觉到大地在晃动，且越晃越厉害。无论在哪里走地都在动，我清楚的知道这是幻觉，但是这种感觉却是如此的真实。小参时禅师告诉我，你只要知道在动、在动，继续去觉知你的脚。就这样，我在晃动不安的大地上足足走了半个月。

行禅时我的觉知越来越强，甚至能感觉到袜子上的绒毛，当脚踩下时，我能感觉到袜子的厚度，及哪一个脚趾先着地，甚至知道脚趾弯曲的感觉，强烈的觉知促使我更精进的修行。

坐禅：仍然毫无进展，只是偶尔感觉到自己的呼吸越来越深沉，有时候象是身体在呼吸。

** 第四周：

这是此次禅修的最后的一周，也是最戏剧性的一周，当然，也是收获最大的一周。

身悦：行禅时每踩下去一步，我都感觉到有一股清凉的气自脚心向小腿往上窜，非常的舒服。坐禅时，每一次呼吸时，都有一股清凉的气在身体里面游走，此时身体里所有的紧绷、压力全部消失了，非常的愉悦。师父告诉我说，这是身悦，只要知道就好，不要沉溺，要舍，继续观照目标。行禅时要继续往细里走，加大心力，身心柔软的走。

出定：师父的话让我很是欣喜，更加精进的修行。我以非常缓慢的速度轻轻的一点一点的觉知每一步的抬起、移动、放下，由于走的太慢，头晕晕的，仿佛快要摔倒了，就在我快要坚持不住的时候，我感觉突然之间，仿佛有一股强大的力量紧紧的压在我的头顶，并且那股力量开始慢慢向下移动，直达双脚。紧接着，我感到一种无比的清明，仿佛睡了一觉，刚才的晕眩一扫而光，脚下更加柔软而有力。就这样，一天之中，我数次感受到那股无形的力量不断的注入我的身体，我的觉知也越来越越轻柔有力。师父告诉我，这就是定。（戒定慧的定）

之后的数天中我的修行越来越精进，修行变得无比的愉悦，甚至觉得自己可以24小时不睡觉的修行。之后我的坐禅也开始突飞猛进，曾经一直困扰我的昏沉妄想全部都消失了，我的心变的很清明，能够长时间的觉知腹部的起伏，呼吸非常微弱，但却越来越深沉。我清楚的知道身体在自己呼吸，我的心在如如不动的觉知着每一个起伏。

觉知名色：一次坐禅时，观着观着，突然腹部的起伏全部消失了，我的眼睛开始迅速的眨动，并伴随着急促的呼吸，那一刻我完全不能自控，在极度的慌乱与眩晕中，不知过了多久，才又再次清醒过来。回到寮房后，我发现自己变的很奇怪，一举一动全部都能清楚的觉知到，不管动作有多快，我都能清楚的觉知到所有的细节，甚至眨一下眼睛我都知道。我看着自己的身体，象是看着另外一个和我毫不相干的人，我看着自己的手自己在动，麻利的洗漱，并做着各种动作。晚上睡觉时，躺在床上，我清楚的知道我的手在哪，脚在哪，胳膊、腿是什么姿式，翻身的时候就更是奇怪了，我觉得自己象是一个木偶，哗哗啦啦的翻了过去。在这种奇怪新奇的感觉中，很晚很晚才睡着。

第二天吃早餐时，以前需要很用心才能觉知到的动作，居然能够毫不费力的一一觉知到。但是一天后，我发现这种强烈的觉性开始慢慢变弱。但是相对以前来说仍然增强了很多。

随后的几天里，我发现，整个世界变的无比的安静，虽然仍然能听到飞机的声音、畜牧场里的牛叫、隔壁孩子读书的声音、附近卡拉OK的声音等等，但是，就只是这些声音而以，它们不断的升起后又不断的消失，世界仍是无边的寂静。究竟怎么了？为什么会如此的不同？终于我发现，是我内心妄想的声音消失了，真的，我惊觉，我的内心不再喋喋不休，我的心如此的安静，什么都没有，空空如也。我静静的觉知着身体在走路、喝水、上厕所，一切都是如此的安静，我静静的行禅、坐禅。当心中的妄念停止时，世界是如此的安静。

临别之际的最后一次小参，我问禅师，回家后我的修行会退步么？我应该如何继续在生活中修行？禅师无限慈悲的注视着我说：你现在感受到的法喜也许会变弱，你修行的时间也许不会象这里这么多，你可能会面对生活中各种各样的问题，但是，重要是的，要保持一颗觉知的心，快乐的时候要觉知快乐、散乱的时候要觉知散乱，累的时候要觉知累，妄想的时候要知道妄想，做事时要知道做事，不管你的身心是任何状态，你都要如实的觉知。觉知才是最重要的事情。

深深的感恩禅师的殷殷教诲，我一定会记住的，并时时刻刻在生活中践行。

带着无比的不舍与深深的感恩，我离开了恰宓禅修中心，踏上了回家的路途。

* 如何禅坐更久

https://blog.sina.com.cn/u/5774554967

禅修新人最恐惧的是坐禅时生起的两种痛：腿痛、腰痛。

禅修者被腿痛和腰痛折磨到极致的时候，禅堂的座钟持续的滴答声，遥远的汽车轰鸣声，是压垮禅修者的最后一根稻草。

借用缅甸妙乌西亚多的开示就是："禅修者在禅垫痛苦地扭曲着身体，如同被撒了一把盐的蚯蚓。脸也痛苦地扭曲着如同烈日下暴晒的西红柿。"

禅修者觉知两种苦受、正确标记两种声音、两种如理作意后，坐禅就会是一件轻松的事，尤其是禅修者体会到超越苦受之后，乐受的滋味后，禅修就成为你每天的必修课。

** 两种苦受：身苦和定苦

禅修时，有两种痛：

一种是因为身体姿势引起的苦受；

一种是因为定力带来的苦受。

** 身苦受：

坐禅时，一条腿压在另一条腿上，时间长了，有痛或者热等苦受出现产生；

坐禅时，一只手压在另一只手上，时间长了，会有痛或者热等不舒服的苦受出现；

坐禅时，脊柱不直，脊柱弯曲的时间长了，会有痛和热等出现；

坐禅时，颈椎不直，颈椎下垂的时间长了，会有痛或者热等苦受出现。

这是因为坐禅时，长久保持在一种身体姿势里或者身体姿势不正确带来的苦受。

行禅、站禅和卧禅时，时间久了，也都会因为身体姿势或者身体姿势不正确而产生苦受。

** 定苦受：

禅修者定力培养出来后，觉知力异常敏锐和犀利，一些平日实际存在但被我们粗大的感知力忽略的苦受，在禅修中被发现，例如，观照腹部起伏时，突然，胸部出现一阵刺痛；或者胳膊的肌肉，突然胀痛，等等，这就是定苦受。

** 身苦受的消失：

禅修者观照时，有时候身体姿势的苦受会消失；有时候无法通过观照令身体姿势的苦受消失。

禅修结束，我们改变身体姿势时，来自身体姿势带来的苦受会自然消失。

** 定苦受的消失：

定苦受出现时，这是我们必须观照的所缘，我们要有能力观照苦受，直到苦受消失。

面对定苦受，我们必须提起正念，精进力和耐力持续观照，直到定苦受消失，所谓苦受消失，指的在正念观照之下，苦受展现出刹那生起又刹那灭去的本质，持续观照会生起智慧。

有些禅修者不能忍受苦受，频繁改变姿势，这样就无法获得禅修的进步。

我们要在每一次禅修时，消灭所有的定苦受，这样下一次禅修时，我们就有能力消灭更剧烈的苦受，如此，才能生起更高阶的智慧，最终走向解脱。

** 标记声音的两个条件

坐禅时，有时会听到声音。听到的声音变得明显时，要去标记观照”听到”、"听到"、"听到"。

要注意的是：

声音变得非常地明显，才去标记观照,

如果声音不明显，可以不用去标记观照。比如，外面有车行驶的声音，但它很遥远并且没有那么明显，各位就可以忽略它，不用去观照。

另外一种是持续性的声音，比如，现在各位听到电风扇的声音。这种持续性的声音，各位也可以忽略它，不用去观照。

因此，对于需要标记的声音，有两个条件：

听到的声音非常明显；不是持续性的声音，

听到了满足这两个条件的声音，各位可以去标记观照”听到”、"听到"、"听到"。

当声音消失后，立刻去觉知当下明显的所缘，例如：观呼吸、观腹部起伏、观苦受、观乐受、观心跳等等，这就是坐禅时观照方法的简略说明。

** 两种如理作意

1. 禅修者在坐禅前，如理作意：坐久了苦受一定会出现，如此可以增加对苦受的忍耐。坚韧的忍耐力是超越苦受，生起乐受的基础。

2. 禅修者在坐禅前，如理作意：苦受和观照苦受的心分开，这样可以看到苦受的变化。看到苦受的持续变化也就是看到生灭，心才有能力超越苦受，生起乐受。

** 一种务实目标

禅修新人不要期待开始禅修时，轻轻松松就可以坐禅两个小时三个小时，更不要期待自己一座就可以”顿悟”。

禅坐前15分钟，接受自己是新人，自然不会心乱如麻；

接受自己需要时间来调整禅坐时的姿势：调整臀部和坐垫的接触点的位置、调整腿和脚的摆放位置，活动僵硬的头部和颈部等等。

15分钟后，禅修者的身体慢慢适应坐禅的姿势后，心理自然就慢慢安定，这时身体和心理才能够真正进入坐禅状态。
* 粗暴地标记是修止轻柔地觉知是修观

https://blog.sina.com.cn/s/blog_15830b7570102xrda.html

大多数禅修者坐禅120分钟的心路历程皆如此：

开始15分钟适应禅坐姿势；

接着45分钟舒适自在；

再接着30分钟忍耐苦受；

最后30分钟在苦受里煎熬。

** 三种观痛方式

禅修者面对苦受时，有3种观察的方式：

1、为了让疼痛消失，才观察疼痛。 禅修者期待疼痛消失而观照疼痛，意味着禅修者贪着无疼痛的快乐，对乐受贪爱，修者不应该以第一种方式来观照。

2、带着与疼痛决战的敌对心态，下定决心观察疼痛，想要就在这一坐之中彻底去除疼痛。 禅修者带着与疼痛决战的敌对态度，这敌对的态度，其中带有”瞋”与”忧”,禅修者也不应该以第二种方式进行观照。

3、纯粹为了洞察疼痛的真实本质而观察疼痛。 禅修者痛只是为了要了知疼痛的生起变化灭去的真实本质才去观察疼痛，这是正确的观照方式。

** 两种错误的标记法

剧烈的苦受出现时，有经验的禅修者，会使用标记法对治苦受。 使用标记法有两个误区：

1、粗暴地标记

如果禅修者直接高强度高频度粗暴地标记”痛”"痛"“痛"时，此刻禅修者心里藏着希望没有苦受的贪心或憎恶苦受的嗔心。 在粗暴地标记”痛”"痛"的当下，剧烈的苦受暂时停止；一旦停止高频度的标记，剧烈的苦受又回来。

正确的方法是：

首先，剧烈的苦受生起后，禅修者先轻柔地去觉知苦受的具体表现形式，尽量细腻地描述苦受的表现，例如，苦受表现为”刺疼”或"灼痛"；"块状的痛"或”线状的痛”或”点状的痛”。

接着，禅修者如其说去标记苦受，不如说是觉知苦受；标记或觉知苦受的感知力比真实的苦受，略微强一点点就足够。

再接着，如此，曾经引起嗔恨之心的剧烈的苦受，被标记或觉知时，变得可以忍受和接受。

最后，禅修者在持续觉知之下，觉知到苦受生起后又灭去，灭去后又生起的特征，苦受就不再干扰到心，即苦受是苦受，觉知苦受的心是觉知的心，苦受和觉知苦受的心分离。

2、标记”我的腿痛”

苦受出现时，禅修者开始掉入”我的腿在痛，我的头在痛，我的膝盖在痛，我的脚在痛”等等陷阱，只要进入”我”"我所有"的模式里，苦受的疼痛感会被放大------"我""我所有"有多大，"我的"苦受的疼痛感就会被放到多大倍，最终在某一个临界值时，剧烈的苦受会压垮我们忍疼痛的心，心被剧烈的苦受攫取，失去了觉知的能力。

正确的方法是：

仅仅标记”痛”或者”刺痛”或者”块状痛”等，不要标记或觉知"我的脚痛"或”我的腰椎刺痛”或者”我的胳膊块状痛”。

** 三种行，三种果报

剧烈的苦受出现时，会攫取住我们的心，换句话说，疼痛让心暂时失去了觉知苦受的能力，这时我们有3种选择：

1、被苦受打败

如果我们接受被痛苦打败，于是我们只能痛哭哀嚎或者通过注射杜冷丁、吗啡缓解疼痛。 哀嚎的当下或注射杜冷丁、吗啡的当下，虽然可以缓解疼痛，但是停止哀嚎或者药物止痛期失效时，剧烈的苦受又立刻出现。

2、粗暴地标记剧烈的苦受

高强度高频度粗暴地标记剧烈地苦受为”苦受”"苦受""苦受"时，此刻心里藏着贪或嗔，标记法的作用是暂时切断苦受的心路历程，让心暂时从苦受中脱离，一旦停止标记苦受时，剧烈的苦受又重新出现，如同嗜血的鲨鱼凶狠地扑向海中伤口流着血的动物。

3、心是心，疼是痛

我们心被苦受攫取，心暂时失去觉知和对治能力时，这时我们需要先培养正见，即如理作意苦受是色身自性相，它不是”我的”或"我所有"；接着，我们再强化正见，即如理作意，觉知”我”无法命令苦受消失或者命令苦受减弱。

正见建立时，我们必然能够发自内心地接纳”苦受”不是”我的”或者”我所有”，苦受是自己生起自己灭去，心放松，身也随之放松，于是一度被剧烈苦受攫取的心获得自由，心恢复了觉知的功能。

这颗获得自由的心，自然接纳和包容各种类型的苦受，自然接纳和包容各种程度的苦受，心如同旁观者淡定地轻柔地觉知着苦受的种类、苦受的变化、苦受的程度，而不被苦受攫取，疼痛是疼痛，心是心，互不干涉。
* 一篇值得学习和体味的禅修报告
*原文地址：* [[https://blog.sina.com.cn/s/blog_4a8514e70101fib8.html][一篇值得学习和体味的禅修报告]]
*作者：*[[https://blog.sina.com.cn/u/1250235623][ metta]]

*亲见无我，法味清凉*

------记圣水寺四念住密集禅修

沙利子2013/10/26
#+TOC: headlines 1 local
** 一、缘起


一个人会相信佛法总有一些因缘，如果这些因缘没有成熟，那么总是难免对面不相识的，相信很多禅修者都有这个体会。佛渡有缘人，这也是佛法的奇妙之处。我很庆幸，由于对历史、文献的重视，在对佛法产生兴趣后，很自然就寻到了最具原始风貌的南传佛法，避免了很多弯路。从闻思到禅修实践，是每一个学佛人都会经历的道路，我也不例外。刚开始我也只是阅读巴利经藏，后来才对禅修感兴趣，并在闲暇之余尝试实践禅修。


最初我主要练习安般念，断断续续，大概有两年左右时间。后来，我发现自己越来越喜欢禅坐中的宁静，不喜欢外界的吵闹，有时候结束禅坐后脾气反而更差。那时我并不太了解止禅与观禅的差异，当我明白止禅只是压制住人的烦恼，并不能真正减少烦恼时，我开始查阅修习观禅的方法。在看了恰宓尊者的一个指导行禅的视频后，我尝试练习行禅，我练习的并不是很多，但一次我突然发现感觉不到自己的双脚、双腿，甚至身体的感觉也很模糊，我很慌乱地低头去看自己。这次经历让我对马哈希禅法产生了很大的兴趣，开始尝试了解它。但那时候，我对很多禅法都很感兴趣，自己的禅修是一个大杂烩，什么都会去尝试，偶尔感受到心念的迅速生灭(现在看这种生灭的体会并不确切)会又惊喜又恐慌，不知道该如何去应对。我日益感觉需要一个好的老师来指点，这使我开始关注网上关于密集禅修的资讯，这在之前是从未曾考虑过的事情。


因为Metta师兄的介绍，我了解到卡玛兰迪禅师正在大陆指导禅修，不久将在圣水寺举办密集禅修。经过一再思量，我决定参加。

** 二、初见禅师


到达圣水寺时，那里正施工，禅修点改在一座僻远山峰上的尼庵------高峰寺。寺院环境很清净，远离喧嚣，是一个禅修的好地方。初见禅师，嗯，很庄严，但不觉得慈祥。食堂训导，不小心一声咳嗽，挨了一顿批评。和不少同修一样，开始对禅师并不太喜欢，严肃，太严肃。可不久发现她说话又常常有些调皮，好像也没那么严肃，可还是拿不准。开始都在想些什么啊，想必禅师看了一定会笑。


禅师对新学员的指导很简单，站禅、行禅，示范、要领，短短几句话，简单几个动作，OK!可以练习去了。期待晚上的开示，发现也没有讲什么特别的禅法理论，有些失望。而且颇多不以为然，为什么行禅脚要提高？不自然。为什么一定要默念标记？不喜欢。观察腹部？我都写过了，希望继续以鼻息为业处的......


但禅师是很善巧的，不久她就讲禅修需要对法、对导师有信心，如果带着疑虑就修不好。普通的佛经故事，早已耳熟能详，可说得适时，效果就很不同，我立刻感到惭愧，那么多意见，我慢，来这里干什么呢？我决定放下那些乱七八糟的思虑，完全投入到禅修中，一定要好好珍惜这宝贵的十天时间。

禅师非常敏锐，第一次小参，就纠正了我坐禅偏定的毛病，因为我以前是修安般的，出现偏定大概是很自然的，只是自己很难发现。小参后，对禅师有了新的认识，感觉禅师其实是非常慈悲的。小参的时候，她对每一个学员都很有耐心，并且总能敏锐地发现你禅修的毛病，并指出改正的办法。这还不是善知识吗？正如禅师后来说的，她会很严格，会批评人，但那只是针对我们的缺点和问题，并不针对任何人。

调整心态后，我很快投入到了密集禅修中，除了中间宗慈法师慈悲让我接了家中一个电话（密集禅修的确不适合和外界接触，否则将无法专心于禅修），其他时间都完全放下世俗所缘，专心于禅修，努力做到不分心，活在当下。我早晨通常起得比较早，也没有午睡的习惯，更不爱在宿舍逗留，所以只要有空，早中晚我都尽量到禅堂大厅去行禅，也会遇到其他用功的法友，回想起来，人少的时候在禅堂行禅还是很惬意的。

** 三、禅修体会

十日禅修最大的收获还是禅修上的进步，那是令人喜悦和终生难忘的。站禅、坐禅、行禅都有令人难忘的体验，但收获最大的是坐禅和行禅。

坐禅我先后经历了三次极限观痛的体验，亲见了无我。

第一次观痛是失败的。第一次坐禅是散盘，两小时没有觉到任何困难。第二次尝试由散盘改为单盘，结果遇到了前所未有的疼痛，心越发沉入疼痛的部位，疼痛越剧烈，最终挺过去时，全身冰冷，感觉整个意志已崩溃。晚上禅师开始，恰恰提到一位同修的类似经历，并提及无我智。当时，我感到很困惑，因为我与那位同修的观痛经历非常类似，最后阶段也有痛处涨大并最终破裂掉的体验，但为什么我没有任何收获，反而感到一种沮丧呢？我本来是想去向禅师请教的，但后来想还是明日再体验一次再说。

第二日下午坐禅，想到头一日意志崩溃的情形，心里隐约感到必须保持足够的力量才行，所以在观痛的过程中并没有一开始就一味地将心力完全沉入所缘，而是采取了迂回的战术，一开始只是冷静地看着疼痛，但那滋味也并不好，疼痛有时就像烧红的铁丝穿透在腿部，上面的火焰在来回地走动，有时又如同一堆火热的岩浆不断地升温，直至冒起无数小泡泡，生起灭去。但这种冷静地关照，也带给心力带来了集聚能量的空间，我感到那些疼痛虽然一再升级，但似乎又与我有一小块距离，并不是不可忍受。当觉得有足够力量时，我开始就将心慢慢地沉入到那块疼痛的核心，沉入，沉入，然而，随着观照力度的加大，疼痛也更加剧烈，它仿佛在报复，骤然地连续升级，又一瞬间差一点就决定放弃，可突然想到人终将面临死亡，那时又将如何面对疼痛的到来？于是想就当现在已经是将死之人，丝毫也动不得，却又不得不接受这难以忍受的疼痛吧！继续观照、观照，后来那疼痛突然一下子达到了顶点，成为无比巨大的一块，重重地向我压来，霎时我不自觉地将全部心力投入了进去，观照，观照......哇！突然间不可思议的事情发生了，我感觉到觉知心与所缘似乎一下子分离开来，那块巨大的疼痛还在那里，历历在目，它是那样一种令人不悦的巨大的苦，但而另一面那颗刚刚还冲锋到极点紧张观照的心却突然轻松下来，清凉而又自在，它只是静静地注视着那个苦，丝毫不觉得它与自己有什么关系。一瞬间，晚课巴利经赞中的那句话显现在我的心中："诸行无我，当我们以智慧认清它时，就不再受痛苦所惑。"是啊，那个疼痛的确不是我的，在它之中也的确没有一个我！真是不可思议！后来我曾想要形容这种巨大的苦受与清凉的觉知心并存的奇异景观，只想到”冰火两重天”这句话。那种清凉的境界并没有持续太久，我突然发现自己可以清楚地觉知到自己那颗跳动的心脏，它小小的，恰如我的拳头大小，一时非常地感慨：它的确已经尽力了，已经到达它力量的边缘了，然而多么不可思议，那颗觉知的心却让我觉得是那么清凉，那么强大！因为分心的缘故，心的清凉消失了，疼痛突然转变为另外一种，它变成巨大的电钻对准了痛处毫不客气地往下钻去！我意识到是这是由于观照的心已经远离所缘，失去了平衡，于是又努力将心投向疼痛，再一次，那种平衡建立了起来。

见法的兴奋感是无以言表的，你会对佛法升起无比的信心，因为这种信是出于亲自见法的信，而不仅仅因为听闻与思维。事后我非常激动，多次想主动申请小参，不过想到不久可能会有小参，就没有那么做。奇怪的是，晚间禅师开示就讲到禅修有进步，随着观智的提升对佛法僧三宝会升起强烈的皈依心！不少同修都私下议论觉得禅师会不会有他心通？那种感觉还真是奇怪，常常是你出现了问题，禅师就会讲到，你有了进步，她也会讲到，禅堂那么多人，仿佛很多人都觉得她在讲到自己。禅师的确是一位善巧的导师！晚上入眠前禁不住对所有寺院的同修们，对禅师，对天下无量的众生散播慈心，眼前竟然闪现出淡淡的黄光笼罩着，柔和而令人舒适，睁开眼来看，呵呵，漆黑一片啊......

果然，第二天下午就有小参，我向禅师汇报了两次观痛的经历。禅师清楚地指出了第一次观痛失败的原因："你没有了观嘛！"是啊，第一次我虽然坚持到了最后，但也在与疼痛的对立过程中，失掉了心的平静，最后完全忘记了观，又怎么会有收获呢？禅师肯定了我第二次观痛的收获。我对禅师的信心也再次增长，对导师的信任就是对法的信任！

此后，我又经历过一次极限观痛的体会。这一次与上一次又有不同，正如禅师所说，观痛真是可以观到”精彩”！疼痛来的时候，只是一处，并不严重，后来随着观照，疼痛的范围似乎越来越小，最后只是很小的一点，而且随着时间的推移，这一小点的疼痛逐渐缩小为如同针尖一般的一丁点。开始对这针尖大小的疼痛完全没有在意，大概潜意识中总觉得它应该很快就消失了吧。谁知道它还真是很不一般，越来越疼，穿透力越来越强，就针尖大小的那么一点，最后竟然疼痛到人的整个身体都抖动起来，而随着全身剧烈的抖动，身体居然变成了一块巨大的半透明的果冻一般的东西，在那里不停地颤动，难以忍受的奇特疼痛和全身剧烈的生灭感都让人无处躲藏，面对着铺天盖地的苦受，心只能完全地投入到观照中。观照，观照，没有什么期待，只是观照，观照。不知过了多久，那个针尖大小的剧痛突然消失了，巨大的果冻也消失了，整个世界都清净下来，仿佛什么都没有了，只有观照的心还在，空，空，继续观照，好寂静啊，完全没有任何身体的感觉，也没有任何声音，甚至连心跳也听不到！这次观照让我对缘起法有了更切身的领悟，疼痛因缘而来，也因缘而去，而缘起的必然也是无我的，并没有什么主宰！禅师曾说她在刚刚禅修时就是以疼痛为观的主要所缘，几次观痛下来，我真的非常地佩服她，因为观痛是需要勇气的，通常大多数人都会在觉得自己再也无法忍受下去时放弃，变换姿势，能带着一颗平静的观照的心坚持到底的人总是很少。不过不彻底地了解那些痛，又怎么能体味到观痛的”精彩”呢？孙伦尊者曾说："苦受确是致道的法则。"我想我以前其实并不明白这句话的意思。不过，观痛也是有教训的，我曾在最后分享禅修体会时跟同修们提到过，观痛不可以缺少了”观”，没了”观”，"观痛"就成了纯粹的忍受，那是没有多少意义的。

这次密集禅修另一个收获是第一次真正看到了心念的灭。那是一个凌晨，大概两三点钟，我醒来后完全没有睡意，就起身到院中殿阁下的走廊下行禅，因为光线比较暗，开始效果并不好，脚不容易站稳，但在寂静的凌晨，除了虫鸣什么声音也没有，慢慢地很容易进入状态。提，推，落......就在一次脚刚刚触地的一瞬间，我清楚地看到了落的心的灭去，紧接着，触的觉知心生起又灭去，然后压、抬、提、推，每一个动机生起、灭去又都紧接着另一个，都是那么清晰动人，哇！当时真的非常惊喜，心念的灭竟然是这样的！过去一直以为自己在行禅中能观到生，也能观到灭，其实不然，那时对灭的认识太肤浅了。心念的灭非常细微，远不像动作的灭那样容易察觉。这犹如A、B、C......心念连续生起，当B瞬间生起时，它完全占据了我们的心，此时A已不在，我们就想当然地认为见到了A的灭，其实那瞬间我们只是见到了B的生起，并未曾真正见到A的灭去，我们误把B对A的替换感当作了见灭。第一次见灭的那种感觉是奇妙的，简直有些惊艳，太令人感慨了！因为这样的新鲜感，希望进一步体验，第二天下午，也是十日禅修最后一次坐禅，我没有参加，而是选择在大殿一层禅堂继续练习行禅。不过最初因为带着想要见灭的贪，反而完全失去了感觉，于是老老实实回到基本的提、推、落，放下贪念，当然，生灭是一直在的，当你如实观照时，它们就自然向你显现出来，不但如此，最后一次行禅中又见到了更多微细的生灭现象。精彩总是出现在最后，禅师总是所言不虚！后来禅师听了我的报告，笑着说："就是啊，如实观照嘛！""如实观照"，原来不仅是一个要求，它本身就是观照的方法啊，只有如实，才能观照到实相！

** 四、感恩的心

我很少对佛像跪拜，即便在喜欢上佛法之后，对佛陀充满了敬佩之心，也很少当着他人跪拜。正如智海大和尚所说，那颗心是何等地贡高我慢！佛陀是何许人呢？他驯服了自己的心，了悟了世间的实相，渡越了苦海，出于慈悲才驻留世间向世人传法，又为了什么呢？不是为了众生也能如他那般渡越轮回的苦海吗？这样一位伟大的导师，我竟然曾觉得当众跪拜是难为情的。但经过十日禅修，我亲睹了无我，感受到了法味的清凉，我的观念彻底改变了。佛陀说他讲的法是自见的、无时的、请你来见的。的确，当一个人亲身见法后，他对三宝的信将与以前不同，那是发自生命深处的，他礼敬佛陀，礼敬佛法，礼敬僧团，不会在意他人的目光。

这次禅修要感恩的人很多，禅师是第一个。在最后一晚的报告中，大家都纷纷表达了自己对禅师的感激之情。她曾说，来到宝山，要带着宝回去，事实上，每一个禅修者都得到了法的利益，大家的感恩是由衷而发的。再一次感恩禅师，如果没有她的指点，我不会有这么大的收获。禅修的道路是漫长的，但这次禅修让我找到了终身可依的法，寻到了可靠的老师！感谢圣水寺成就了这次禅修活动，感恩智海大和尚、宗慈法师的开示、指点，感恩在高峰寺辛勤服务的法工与信众们，感恩一起努力禅修的每一位同修，感恩Metta师兄的介绍，感恩我的爱人的成全，也感恩高寺山的一切生灵，我曾在这里听到第一声鸟啼，第一声鸡鸣......

愿正法长住世间！

愿一切众生吉祥安乐！

萨度！萨度！萨度！

* 卡玛兰迪禅师四念处内观密集禅修点滴感想
https://blog.sina.cn/dpool/blog/s/blog_3bcfdece0102xj2t.html?md=gd
* 日月明行-角行时代的博客
http://blog.rhinoera.com/

