#+options: toc:nil  ^:nil
#+begin_export md
---
layout: post
title: "内观禅修感悟"
date: 2018-05-10
tags: 
    - 佛学
---
#+end_export

#+TOC: headlines 2
* 内观禅修感悟不可忽略行禅

** 第一周：

行禅：平时懒散惯了，刚去的第一周完全没有感觉，虽然人在禅修，但是妄念一刻不停。只要一有声音或人影走过，我就会无法自控的扭头去看，完全没有正念。第一天行禅时我的旧疾腰痛就发作了，刺骨的痛，几乎每走几步就要调整一下姿式才能继续走下去，但是我仍咬牙坚持着，一直走完一个小时，那时候坐禅就是最好的休息。

坐禅：坐禅的心也是散乱的，很难长时间观照目标。每一小时的坐禅，基本上是半个小时昏沉半个小时妄想。妄想的力量是如此强大，如排山倒海之势将我淹没，这样每天一小时一小时的在昏沉妄想中挣扎，常常令我极度沮丧。

小参时，禅师总是会微笑的说，不要气馁，继续努力。情况是如此的糟糕，我唯一能做的就是继续努力，踏踏实实的行禅、坐禅，什么也不想。

** 第二周：

行禅：有一天早上醒来，我象往常一样行禅时，突然发现我的腰痛消失了，无论怎么走一点痛的感觉都没有了，这真是太神奇了，禅修真的能治病，这可是困扰我近十年的旧疾，从生下孩子就一直没好过。在激动欣喜中，这一天我格外的精进。行禅时觉知越来越强。第二天，我发现自己走起路来犹如在云中漫步，非常的轻柔，脚上的觉知象棉花一样的柔软，很舒服，走了一天下来，一点都不累，且越走越精神。隆藏法师告诉我，说我走出了轻安，当出现轻安时，走多久都不会累。并且提醒我，要更细的去觉知，走出柔软的力量。

坐禅：坐禅时仍然很糟糕，昏沉妄想仍然非常有力。经常会忆起许多年前早已遗忘的一个人或一件事，并沉溺许久，有如再次亲历。我对自己说，一切都是无常的，这个念头也将会消失。

** 第三周：

行禅：上一周就曾出现过行禅时感觉到地板轻微晃动的状况，到这一周时晃动的感觉越来越真切，我每走一步，只要把觉知放在脚上，就会如此真实的感觉到大地在晃动，且越晃越厉害。无论在哪里走地都在动，我清楚的知道这是幻觉，但是这种感觉却是如此的真实。小参时禅师告诉我，你只要知道在动、在动，继续去觉知你的脚。就这样，我在晃动不安的大地上足足走了半个月。

行禅时我的觉知越来越强，甚至能感觉到袜子上的绒毛，当脚踩下时，我能感觉到袜子的厚度，及哪一个脚趾先着地，甚至知道脚趾弯曲的感觉，强烈的觉知促使我更精进的修行。

坐禅：仍然毫无进展，只是偶尔感觉到自己的呼吸越来越深沉，有时候象是身体在呼吸。

** 第四周：

这是此次禅修的最后的一周，也是最戏剧性的一周，当然，也是收获最大的一周。

身悦：行禅时每踩下去一步，我都感觉到有一股清凉的气自脚心向小腿往上窜，非常的舒服。坐禅时，每一次呼吸时，都有一股清凉的气在身体里面游走，此时身体里所有的紧绷、压力全部消失了，非常的愉悦。师父告诉我说，这是身悦，只要知道就好，不要沉溺，要舍，继续观照目标。行禅时要继续往细里走，加大心力，身心柔软的走。

出定：师父的话让我很是欣喜，更加精进的修行。我以非常缓慢的速度轻轻的一点一点的觉知每一步的抬起、移动、放下，由于走的太慢，头晕晕的，仿佛快要摔倒了，就在我快要坚持不住的时候，我感觉突然之间，仿佛有一股强大的力量紧紧的压在我的头顶，并且那股力量开始慢慢向下移动，直达双脚。紧接着，我感到一种无比的清明，仿佛睡了一觉，刚才的晕眩一扫而光，脚下更加柔软而有力。就这样，一天之中，我数次感受到那股无形的力量不断的注入我的身体，我的觉知也越来越越轻柔有力。师父告诉我，这就是定。（戒定慧的定）

之后的数天中我的修行越来越精进，修行变得无比的愉悦，甚至觉得自己可以24小时不睡觉的修行。之后我的坐禅也开始突飞猛进，曾经一直困扰我的昏沉妄想全部都消失了，我的心变的很清明，能够长时间的觉知腹部的起伏，呼吸非常微弱，但却越来越深沉。我清楚的知道身体在自己呼吸，我的心在如如不动的觉知着每一个起伏。

觉知名色：一次坐禅时，观着观着，突然腹部的起伏全部消失了，我的眼睛开始迅速的眨动，并伴随着急促的呼吸，那一刻我完全不能自控，在极度的慌乱与眩晕中，不知过了多久，才又再次清醒过来。回到寮房后，我发现自己变的很奇怪，一举一动全部都能清楚的觉知到，不管动作有多快，我都能清楚的觉知到所有的细节，甚至眨一下眼睛我都知道。我看着自己的身体，象是看着另外一个和我毫不相干的人，我看着自己的手自己在动，麻利的洗漱，并做着各种动作。晚上睡觉时，躺在床上，我清楚的知道我的手在哪，脚在哪，胳膊、腿是什么姿式，翻身的时候就更是奇怪了，我觉得自己象是一个木偶，哗哗啦啦的翻了过去。在这种奇怪新奇的感觉中，很晚很晚才睡着。

第二天吃早餐时，以前需要很用心才能觉知到的动作，居然能够毫不费力的一一觉知到。但是一天后，我发现这种强烈的觉性开始慢慢变弱。但是相对以前来说仍然增强了很多。

随后的几天里，我发现，整个世界变的无比的安静，虽然仍然能听到飞机的声音、畜牧场里的牛叫、隔壁孩子读书的声音、附近卡拉OK的声音等等，但是，就只是这些声音而以，它们不断的升起后又不断的消失，世界仍是无边的寂静。究竟怎么了？为什么会如此的不同？终于我发现，是我内心妄想的声音消失了，真的，我惊觉，我的内心不再喋喋不休，我的心如此的安静，什么都没有，空空如也。我静静的觉知着身体在走路、喝水、上厕所，一切都是如此的安静，我静静的行禅、坐禅。当心中的妄念停止时，世界是如此的安静。

临别之际的最后一次小参，我问禅师，回家后我的修行会退步么？我应该如何继续在生活中修行？禅师无限慈悲的注视着我说：你现在感受到的法喜也许会变弱，你修行的时间也许不会象这里这么多，你可能会面对生活中各种各样的问题，但是，重要是的，要保持一颗觉知的心，快乐的时候要觉知快乐、散乱的时候要觉知散乱，累的时候要觉知累，妄想的时候要知道妄想，做事时要知道做事，不管你的身心是任何状态，你都要如实的觉知。觉知才是最重要的事情。

深深的感恩禅师的殷殷教诲，我一定会记住的，并时时刻刻在生活中践行。

带着无比的不舍与深深的感恩，我离开了恰宓禅修中心，踏上了回家的路途。

* 如何禅坐更久

https://blog.sina.com.cn/u/5774554967

禅修新人最恐惧的是坐禅时生起的两种痛：腿痛、腰痛。

禅修者被腿痛和腰痛折磨到极致的时候，禅堂的座钟持续的滴答声，遥远的汽车轰鸣声，是压垮禅修者的最后一根稻草。

借用缅甸妙乌西亚多的开示就是："禅修者在禅垫痛苦地扭曲着身体，如同被撒了一把盐的蚯蚓。脸也痛苦地扭曲着如同烈日下暴晒的西红柿。"

禅修者觉知两种苦受、正确标记两种声音、两种如理作意后，坐禅就会是一件轻松的事，尤其是禅修者体会到超越苦受之后，乐受的滋味后，禅修就成为你每天的必修课。

** 两种苦受：身苦和定苦

**禅修时，有两种痛：

一种是因为身体姿势引起的苦受；

一种是因为定力带来的苦受。

** 身苦受：

坐禅时，一条腿压在另一条腿上，时间长了，有痛或者热等苦受出现产生；

坐禅时，一只手压在另一只手上，时间长了，会有痛或者热等不舒服的苦受出现；

坐禅时，脊柱不直，脊柱弯曲的时间长了，会有痛和热等出现；

坐禅时，颈椎不直，颈椎下垂的时间长了，会有痛或者热等苦受出现。

这是因为坐禅时，长久保持在一种身体姿势里或者身体姿势不正确带来的苦受。

行禅、站禅和卧禅时，时间久了，也都会因为身体姿势或者身体姿势不正确而产生苦受。

** 定苦受：

禅修者定力培养出来后，觉知力异常敏锐和犀利，一些平日实际存在但被我们粗大的感知力忽略的苦受，在禅修中被发现，例如，观照腹部起伏时，突然，胸部出现一阵刺痛；或者胳膊的肌肉，突然胀痛，等等，这就是定苦受。

** 身苦受的消失：

禅修者观照时，有时候身体姿势的苦受会消失；有时候无法通过观照令身体姿势的苦受消失。

禅修结束，我们改变身体姿势时，来自身体姿势带来的苦受会自然消失。

** 定苦受的消失：

定苦受出现时，这是我们必须观照的所缘，我们要有能力观照苦受，直到苦受消失。

面对定苦受，我们必须提起正念，精进力和耐力持续观照，直到定苦受消失，所谓苦受消失，指的在正念观照之下，苦受展现出刹那生起又刹那灭去的本质，持续观照会生起智慧。

有些禅修者不能忍受苦受，频繁改变姿势，这样就无法获得禅修的进步。

我们要在每一次禅修时，消灭所有的定苦受，这样下一次禅修时，我们就有能力消灭更剧烈的苦受，如此，才能生起更高阶的智慧，最终走向解脱。

** 标记声音的两个条件

坐禅时，有时会听到声音。听到的声音变得明显时，要去标记观照”听到”、"听到"、"听到"。

要注意的是：

声音变得非常地明显，才去标记观照,

如果声音不明显，可以不用去标记观照。比如，外面有车行驶的声音，但它很遥远并且没有那么明显，各位就可以忽略它，不用去观照。

另外一种是持续性的声音，比如，现在各位听到电风扇的声音。这种持续性的声音，各位也可以忽略它，不用去观照。

因此，对于需要标记的声音，有两个条件：

听到的声音非常明显；不是持续性的声音，

听到了满足这两个条件的声音，各位可以去标记观照”听到”、"听到"、"听到"。

当声音消失后，立刻去觉知当下明显的所缘，例如：观呼吸、观腹部起伏、观苦受、观乐受、观心跳等等，这就是坐禅时观照方法的简略说明。

** 两种如理作意

1. 禅修者在坐禅前，如理作意：坐久了苦受一定会出现，如此可以增加对苦受的忍耐。坚韧的忍耐力是超越苦受，生起乐受的基础。

2. 禅修者在坐禅前，如理作意：苦受和观照苦受的心分开，这样可以看到苦受的变化。看到苦受的持续变化也就是看到生灭，心才有能力超越苦受，生起乐受。

** 一种务实目标

禅修新人不要期待开始禅修时，轻轻松松就可以坐禅两个小时三个小时，更不要期待自己一座就可以”顿悟”。

禅坐前15分钟，接受自己是新人，自然不会心乱如麻；

接受自己需要时间来调整禅坐时的姿势：调整臀部和坐垫的接触点的位置、调整腿和脚的摆放位置，活动僵硬的头部和颈部等等。

15分钟后，禅修者的身体慢慢适应坐禅的姿势后，心理自然就慢慢安定，这时身体和心理才能够真正进入坐禅状态。
* 粗暴地标记是修止轻柔地觉知是修观

https://blog.sina.com.cn/s/blog_15830b7570102xrda.html

大多数禅修者坐禅120分钟的心路历程皆如此：

开始15分钟适应禅坐姿势；

接着45分钟舒适自在；

再接着30分钟忍耐苦受；

最后30分钟在苦受里煎熬。

** 三种观痛方式

禅修者面对苦受时，有3种观察的方式：

1、为了让疼痛消失，才观察疼痛。 禅修者期待疼痛消失而观照疼痛，意味着禅修者贪着无疼痛的快乐，对乐受贪爱，修者不应该以第一种方式来观照。

2、带着与疼痛决战的敌对心态，下定决心观察疼痛，想要就在这一坐之中彻底去除疼痛。 禅修者带着与疼痛决战的敌对态度，这敌对的态度，其中带有”瞋”与”忧”,禅修者也不应该以第二种方式进行观照。

3、纯粹为了洞察疼痛的真实本质而观察疼痛。 禅修者痛只是为了要了知疼痛的生起变化灭去的真实本质才去观察疼痛，这是正确的观照方式。

** 两种错误的标记法

剧烈的苦受出现时，有经验的禅修者，会使用标记法对治苦受。 使用标记法有两个误区：

1、粗暴地标记

如果禅修者直接高强度高频度粗暴地标记”痛”"痛"“痛"时，此刻禅修者心里藏着希望没有苦受的贪心或憎恶苦受的嗔心。 在粗暴地标记”痛”"痛"的当下，剧烈的苦受暂时停止；一旦停止高频度的标记，剧烈的苦受又回来。

正确的方法是：

首先，剧烈的苦受生起后，禅修者先轻柔地去觉知苦受的具体表现形式，尽量细腻地描述苦受的表现，例如，苦受表现为”刺疼”或"灼痛"；"块状的痛"或”线状的痛”或”点状的痛”。

接着，禅修者如其说去标记苦受，不如说是觉知苦受；标记或觉知苦受的感知力比真实的苦受，略微强一点点就足够。

再接着，如此，曾经引起嗔恨之心的剧烈的苦受，被标记或觉知时，变得可以忍受和接受。

最后，禅修者在持续觉知之下，觉知到苦受生起后又灭去，灭去后又生起的特征，苦受就不再干扰到心，即苦受是苦受，觉知苦受的心是觉知的心，苦受和觉知苦受的心分离。

2、标记”我的腿痛”

苦受出现时，禅修者开始掉入”我的腿在痛，我的头在痛，我的膝盖在痛，我的脚在痛”等等陷阱，只要进入”我”"我所有"的模式里，苦受的疼痛感会被放大------"我""我所有"有多大，"我的"苦受的疼痛感就会被放到多大倍，最终在某一个临界值时，剧烈的苦受会压垮我们忍疼痛的心，心被剧烈的苦受攫取，失去了觉知的能力。

正确的方法是：

仅仅标记”痛”或者”刺痛”或者”块状痛”等，不要标记或觉知"我的脚痛"或”我的腰椎刺痛”或者”我的胳膊块状痛”。

** 三种行，三种果报

剧烈的苦受出现时，会攫取住我们的心，换句话说，疼痛让心暂时失去了觉知苦受的能力，这时我们有3种选择：

1、被苦受打败

如果我们接受被痛苦打败，于是我们只能痛哭哀嚎或者通过注射杜冷丁、吗啡缓解疼痛。 哀嚎的当下或注射杜冷丁、吗啡的当下，虽然可以缓解疼痛，但是停止哀嚎或者药物止痛期失效时，剧烈的苦受又立刻出现。

2、粗暴地标记剧烈的苦受

高强度高频度粗暴地标记剧烈地苦受为”苦受”"苦受""苦受"时，此刻心里藏着贪或嗔，标记法的作用是暂时切断苦受的心路历程，让心暂时从苦受中脱离，一旦停止标记苦受时，剧烈的苦受又重新出现，如同嗜血的鲨鱼凶狠地扑向海中伤口流着血的动物。

3、心是心，疼是痛

我们心被苦受攫取，心暂时失去觉知和对治能力时，这时我们需要先培养正见，即如理作意苦受是色身自性相，它不是”我的”或"我所有"；接着，我们再强化正见，即如理作意，觉知”我”无法命令苦受消失或者命令苦受减弱。

正见建立时，我们必然能够发自内心地接纳”苦受”不是”我的”或者”我所有”，苦受是自己生起自己灭去，心放松，身也随之放松，于是一度被剧烈苦受攫取的心获得自由，心恢复了觉知的功能。

这颗获得自由的心，自然接纳和包容各种类型的苦受，自然接纳和包容各种程度的苦受，心如同旁观者淡定地轻柔地觉知着苦受的种类、苦受的变化、苦受的程度，而不被苦受攫取，疼痛是疼痛，心是心，互不干涉。
* 卡玛兰迪禅师四念处内观密集禅修点滴感想
https://blog.sina.cn/dpool/blog/s/blog_3bcfdece0102xj2t.html?md=gd
* 日月明行-角行时代的博客
http://blog.rhinoera.com/

