#+OPTIONS: toc:nil ^:nil
#+begin_export md
---
layout: post
title:  "南传大般涅槃经"
date:   2019-09-05
tags:
      - 佛学
---
#+end_export

#+TOC: headlines 1

* 序言

 以生存于二十世纪的现代人去研究二千五百年前释尊的生活、教理，当时印度的宗教思想及社会习俗等，因「去圣日远」，实非易事。且佛教之传入中国全赖翻译，因华梵语言的特殊结构，及文章体制的不同，一重繁，一重简，转梵为华是去繁就简。简之太甚则难免陷于晦涩，所以初期的汉译经典颇不易读；若无注疏则了解实难。其最劣者是有失原意，不为无益，反而有害，其较下乘者则为「有似嚼饭与人」1使人呕吐。那是失其精神，只存糟粕。此可见□译之难，几乎至于不可能之境地。语言隔阂固为了解原始佛教的障碍之一，但初期来中国之译经传教者并非直接来自印度，而是展转从其他地区及其他国家，诸如安世高来自波斯，支谶来自月氏，白法祖来自龟兹，康僧会来自康居，以及其他来自中亚及西域南海各地。为了时间与地域的关系，及本地的宗教与外来的宗教因接触而起了变化作用，故自上列各地传来中国的佛教不能说是没有变质的、纯粹的原始印度佛教。这正如今日的日本佛教是不同于中国或西藏的佛教，甚至八、九世纪密宗盛行的印度佛教是不同于西元前五世纪时释迦佛所传的佛教。如此说来，这是一个历史问题，因佛教是因时因地而有发展与变化。如果我们只限定在某一时间或某一地域去说：「只有此才是佛教，其余皆非。」这颇有抹杀历史事实，难免「盲人摸象」之讥，因为佛教是错综复杂的。欲对之有深刻认识与了解，我们应当从研究佛教史入手。其第一步工作应为研究原始佛教的建立与其社会环境关系，及其开山祖释迦牟尼的生活与教义等。若能如此，则是脚踏实地，不落虚幻。说到佛陀的史传，中国各期所译的典籍如：佛本行经，佛本行集经，过去现在因果经，十二游经，佛所行赞经Buddhacarita，神通游戏经Lalita-Vistara或普曜经，方广大庄严经等，多数系译自梵文，其成书日期至少是去佛入灭数百年之后。写成于此时期的作品对事实的真象或已不甚明皙，因而对佛陀的人格一部份已被渲染成「超人化」，「神化」或「神话」─因钦仰佛陀伟大的人格与崇高教理，其信徒们对之致最深敬仰；他们相信佛之地位是超出印度的梵神、帝释、天神等，并拥有如沙门果经所述的各种神通。此种用意并非不佳，但结果是使人们对佛陀的人格有「人神不分」之感。其影响所及，好的方面是一般佛教徒对佛陀有虔诚的信仰，敬之如神明，而坏的方面则是被异教徒斥为「迷信」。其实，历史的佛陀不是神话，佛教也不是迷信。这是治佛教史者所尽知，不待申辩。但今后我人甚希望学佛者多遵循史实途径以认识佛教。且尽量避免涉及「迷信」的嫌疑。若以此为目标，则南传大般涅槃经之翻译为汉文，对历史佛陀的认识应有相当助益。

「大般涅槃经」一名在汉译大藏中曾数次著录如二：一、佛般泥洹经，西晋白法祖译；二、大般涅槃经，东晋释法显译；三、般泥洹经，不载译人附东晋译；四、长阿含经卷二至卷四(游行经)，姚秦佛陀耶舍共竺佛念译以及第五大般涅槃经四十卷，北凉昙无谶译。除第五项外，第一至第四似乎是出自同一来源。它们均为佛陀将入涅槃前短期生活的写实，虽然说它们间互有差异，详略不同，将它们与巴利文原本对照，亦有悬殊之处，卒见其非译自巴利文，而是译自梵文。因此，本经从巴利文译成汉文是甚为重要与急需。此经系巴利长阿含经Digha-Nikaya三十四经之一题三名曰：Maha-Parinibbana-Suttanta，而译文所根据的原本英国巴利圣典会所刊行，其成书年代应在佛陀刚圆寂之后(约西元前四世纪左右)，且与王舍城第一次结集有密切关系。本经第六章曾提及于佛陀逝世之日有一弟子名苏跋陀。彼晚年出家，对佛陀之去世不但不表示悲戚，且公开向比丘僧众宣布，其大意为：当佛陀在世时彼等常被其告诫以去恶从善，烦扰不堪；今彼既已圆寂，彼等可以为所欲为而获得大解放！此种趋势若不加以制止，则佛陀之僧团与所建立的教法很有瓦解的可能，而佛陀的教理亦很可能被人误解。依照巴利律藏大品Maha-Vagga王舍城之第一次结集即为了纠正此种狂放思想而起。大迦叶认为苏跋陀之狂语会发生不良影响，故召开大会去共同讨论及记录佛之教言与所制的戒条，藉便大家遵守。在会议进行中阿难被询以何者为应舍弃的小小戒，即系根据本经的第六章第三节。准此，如吾人接受第一结集是在纪元前五世纪举行，则本经若干最原始部份亦应在佛陀刚去世之时完成，虽然说巴利圣典之被笔之于书是在纪元前四十三年于锡兰之4阿鲁维哈罗Aluvihara石窟。但吾人应知古代印度圣典之保存流传方法，于利用纸笔或贝叶书泐之前，人们全凭口授。其遗迹仍明皙可见于佛经者为许多重复申述，不嫌繁赘之词；其作用是便于记忆与转诵。以现代人之立场去看，那颇为滞涩与笨拙，但在彼时、彼地，那是唯一传播文化的工具，实未可厚非。此经有若干关于佛教史的重要点，如教理、僧团制度、佛陀的生活写实，以及当时的社会环境等，今不妨分别讨论之。

一、教理

在西元前五、六世纪左右，印度的宗教思想认为人生是痛苦的。欲离苦求乐，非舍弃家庭生活而度其离群独居，行乞习定的修道士生活不可，意在获得解脱Mukti。若我人观察印度教传统的宗教社会生活方式，那是将人生分为五5四个阶段如：一、梵行期Brahmacary二、居家期Garhastya三、森林期VanaPrasthya及第四出家期Sannyasa，换言之，每一印度人在其晚年必须谢绝尘缘，出家修道。当时的宗教思想与行持对佛陀有甚深影响，故彼于二十九岁时即舍弃其养尊处优的王宫生活而出家以追求真理。他究竟得成正觉。其后四十余年中彼所阐扬的主要教理为：四谛─苦谛，苦因谛，苦灭谛，及道谛。若人对此有深刻了解则「取欲已尽，有因已灭，从此不再受生。」(第二章1─3)。人们之所以「流转于生死长途」是「因不了解四圣谛之真实性」。基于现实生活如生老病死的苦痛，遂发展为十二因缘如：「无明缘行，行缘识……」业报、因果、来生等的教义。其行持方面是在持戒、修定、发慧。若人获取智慧「则心从漏得解脱─欲漏、有漏、见漏及无明漏」(第二章4)及第四章2，再以八正道、四念处、四正勤、四神足、五根、五力、七菩提分等(第三章50)的修行方法辅佐之，务期能证得圣果(第五章27)，即须陀洹至阿罗汉之四果，亦称为沙门果。若人证得四果中之阿罗汉果(Arhatship)，则他是「诸漏已尽，万行圆成，所作已作，应办已办，永远不会再投胎转世而遭受生死轮回之苦」。那可说是「佛果」的异名。在纪元前五、六世纪时，「佛」与「阿罗汉6」都是对佛常用的形容词，毫无高低分别之处，此可见于佛之十号，如：「应供(Arhat)，正遍知(Sammasambuddha)」的惯例。佛陀对此四果甚为重视，故当其向彼之最后弟子苏跋陀提及佛教之所以优胜于外道六师的理由，即因为「外道诸师之法皆空幻，无沙门果」及无八正道(第五章27)。当然佛陀之「中道」主义，施之于哲学、玄学及宗教行持，亦较外道之极端主义为优。此外，佛陀对「无常Anicca」思想亦非常重视。这虽然是因弟子们闻悉彼不久即将入涅槃发出悲戚之感，彼安慰他们而起，但佛陀对宇宙人生有彻底观察与分皙，透明其因果关系，及彻照真理，故彼之教理是：「万物实性如此，其与我们最亲近者将要与我们分别隔离。当一物既生而成形，即具分离必然性，不要其解离，此何可能，且必无此理！」(第三章48)。世间的万事万物皆由错综复杂的元素组成，如一部大机器，其数百种零件如：轮轴、引擎、车盘、汽油及司机等，须一一具备，始能发挥作用，它不是一成不变。有时机器发生障碍，须待修理。如果它的年岁太久，坏到不能修理的时候则只好抛弃之，那也可以说是机器的「寿终正寝」。人类的生命与机器相比较则殊觉短暂。人寿数十年，实际上是一转瞬间的事；荣华富贵也不过是南柯一梦。因为人类的生命是由四大(地水火风)、五蕴、六根，及不计其数的各种细胞、神经系统、呼吸系统、骨节、皮肤、毛发等所组成，并由经常的饮食、营养、医药、衣著、屋舍等之供给与庇护，才能生存与发出种种活动。但这一部「活机器」的生命是有限的。上寿最多一百年，次焉者八、九十年，那已是「难能可贵」，因为「人生七十古来稀」，早为众所周知。平均以六十年计算，那也不过是一刹那的时间。因此，古昔诗哲如李白、苏东坡等哀叹「人生如梦」及「自其变者而观之，则天地诚不能以一瞬」；虽有秦皇、汉武之服食仙药以求长生，其结果实等于零。他们未能获得预期的效果，是因其违反佛陀所说：「诸行无常，是生灭法」的真理。此「无常」思想与四谛中的「苦谛」有密切联系，因为「非永恒」即是「苦」。佛教的三法印：苦、无常、无我，本经已论及前二者。其第三项未见提及，或许是因其快将圆寂，无暇及此。又因关于「无我Anatta」之种种，他已早作详细讨论，且散见于巴利四阿含之若干经典内，那只好被认为「心照不宣」，勿庸赘述。

二、僧团制度与遗教

佛教之成为有组织的僧团，及后来成为世界伟大宗教之一，或许非佛陀本人所预料。据说佛陀于初成正觉之时，颇不欲以所证悟的真理公之于世。但既于鹿野苑转大*轮，以中道、四谛、八正道之教理向五比丘宣说，其后四十五年中他说法度生，席不暇暖；且命其弟子四出传教，远及边鄙，并用本地语言对人宣讲，藉谋普及。于西元前三世纪顷，阿输迦王之派遣使臣或传教士赴印度各处，迦湿弥罗，希腊以及西南亚洲各国传播佛教，未始不是由佛陀传教精神所感化。唯其如此，足见僧伽Sangha的重要性及其使命。但既有僧团━━那是集合多数来自不同家庭及社会背境而共同生活于一寺院内的僧众，龙蛇混杂，良莠不齐，在所难免，如提婆达多与六群比丘的行为即其先例─不得不建立戒律或宪法来共同遵守。其有违犯者或罚或摈，由全体僧团团员以民主式的精神与方式执行之。大藏经中以「波罗提木叉Pratimoksha」为首的律藏即为适应此需要而产生，那是僧伽的宪法、法律、以及若干共同生活，如传沙弥戒，授比丘戒，每半月诵戒经，坐夏，及安居后自恣等的礼仪。其在最初或甚简单，例如佛在世时，其「传戒」仪式是「善来比丘，须发自落」。(但笔者不相信那是不假借剃刀之助，而会自动掉下来！)。但为时既久，它们遂渐臻完善，而成为各宗卷帙浩繁的律藏(四分律、五分律等都是)。其实于佛去世之前，7波罗提木叉的重要戒条如波罗夷Parajika，僧伽婆斯沙Sanghavasesa等应早已完成，而佛陀的最后遗教遂成为使僧团组织与礼仪趋于严密完整的前奏。从本经所载佛陀的遗教，我们窥见其对僧团前途的关怀，及其待人接物的仁慈态度。其伟大人格甚可钦佩。他虽为佛教创立人，但他不以「教主」身份自居。他说：「若人作如是念：『我将引导僧伽。』或『僧伽以我为依怙。』此人应对僧伽设立教言，但如来不作此想」(第二章25)。他教阿难以法为明灯，以自己为明灯，而不要依靠他人。他且明白表示「如来于法无秘密，吝而不传。」(第二章26)。那即是说凡他所知者皆已传授给弟子。他对恶魔说如果他之四众弟子尚未能精研教义及建立佛教，那他是不入涅槃的(第三章35)。不但此也，他恐怕于其去世之后，有人误解其教义，他特授以「四大教法」以资辨证(第四章5─12)。欲得梵教长住，他授弟子们以各种「兴盛法」(第一章6─12)。他苦口婆心劝诫彼等应一心一德和平共处及如何修行以进趣圣果。此诸种兴盛法之被提及，起源于彼明告摩竭陀大臣雨舍越祗人(Vajji)之不能被征服的理由，因彼等是事事依照越祗人古昔的法规，行为合乎道德标准(第一章4─5)。于该大臣离去后，彼即以多种兴盛法教诫其弟子。其内容虽略有变更，但他强调无论在家与出家众均应遵循道德与伦理的轨则，及举止行动合乎法度，如是则他们是只会兴盛，不会毁灭。如果他对佛教的前途是漠不关心，那他很可能不必因说越祗人的兴盛法而详细列陈比丘的兴盛法的。在佛陀将去世前之数小时，他曾以下列数事告诫其弟子，实际上可说是他的遗嘱：(1)僧伽对于妇女的态度，甚至不应当与她们交谈及宜自警惕。(第五章9)(2)外道皈依佛教欲出家者应试习四月。(第五章29)(3)于佛去世后，弟子们应以彼所说之法与戒为导师。(第六章1)(4)比丘间应有适当的称呼━━长幼有序，各得其体。(5)应向疆那比丘施行梵罚。(6)有疑当问，免致后悔。(7)「诸因缘法含固有毁坏，应自精勤证取道果。」(第六章1─7)上列的第七项是佛陀的「最后遗教」，因其后金口缄默，一代大师遂告圆寂。

三、佛陀的最后生活

如现代人欲彻底明了佛陀的整个生活的真象，从其降生至于圆寂，实际上不是一件容易的事。因若干「佛传」，无论其原文为梵文或其他语言，其成书时代至少是距佛去世有数百年的时间。于此时期佛教已奠下坚固基础，传播既广，皈信者亦多。为了某种原因，作传者非故事夸张以「神话」色彩渲染之，即系传闻失实，或二者兼有之；例如：佛陀是从右肋降生，生后自动行七步，并宣言「天上天下唯吾独尊」等。此种奇迹揆之常情似乎是不可能。若说人性的佛陀已被「神化」，或为一适当的解释。所幸者，本经所载关于佛陀的最后生活颇能帮助我人研究彼之晚年生活实况，虽然说间亦涉及「神话」。但若以此中历史的部份与神话部份相较，则是前者多而后者少。今略举数事以明之：一、当佛陀与其最后弟子苏跋陀谈话时，他自述于二十九岁出家，届时已逾五十一年(第五章27)，合计约八十年。又在此稍前，他告阿难说：「我今年已老矣，衰耄矣，旅程将尽，寿命将满。我行年八十，譬如旧车，方便修理，尚勉强可行。」(第三章27)。准此，则佛陀享寿八十，似无可疑。二、关于佛陀得病致死之事，本经有详细记载。最初他在□舍离附近的白鹿瓦村安居坐夏时，忽罹剧痛痢疾，几乎殒命(第二章23)。后来铁匠穷达以旃檀树耳Sukara-Maddava设斋供佛；饭后他「忽患严重性血痢，剧痛几濒于死。」(第四章18┃21)。结果，佛陀竟因此一病不起，而在拘尸那罗入涅槃。根据此事，吾人很肯定相信佛陀是一历史性的伟人，而不是「神」或一则「神话」。因其遭受病苦，竟至于圆寂，是与常人无异。达穷所供的食物Sukara-Maddava应为一种菌类植物。此种菌类有时或含毒性。穷达所供者或非有毒之一种。但以八十高龄的佛陀，因年岁影响到他的健康；又因所食数量过多，以此致疾，甚有可能。不过，有一事令人不解者为其明白嘱咐穷达以全部□檀树耳供佛，而不要分奉给比丘僧众。他并令将剩余的部份掘地埋藏之。其理由为除如来外，非梵天、魔众及人类能对该物有良好的消化(第四章18─19)，如是，则佛陀在进食之前似已预知该物之特别性质。不幸的事是彼亦因此得病，竟一病不起与世长辞。笔者于一九四二年曾以英文撰八稿题名曰：Sukara-maddavaandtheBuddha'sDeath详论此事，载于印度班陀尔卡东方研究学院廿五周年纪念学报内。对此问题有兴趣的读者参阅之。三、历史佛陀的另一面则为其待人接物的慈蔼态度。他常是慈悲为怀，循循善诱，例如当阿难想念及佛陀即将入灭，而他自己尚在学地未证道果，遂倚门自泣。佛陀即以善言安慰之，并表彰他的德性(第五章13┃16)。当彼将圆寂之数小时前，游行者苏跋陀亟欲见佛以决其疑。阿难以佛病势严重数次拒绝之。佛陀得悉此事后立即命其进谒，并为之说法决疑，而成为佛陀之最后弟子(第五章23)。我人试想一垂死之人情况。但他不惜一切以接引发心者。此在常人殊为不可能之事。佛陀说法度人不择贫富贵贱，上自国王大臣，下至乡曲细民如歌女□婆婆梨，且接受伊之斋供与所献之园林(第二章14┃20)。此在他人或有所顾虑，但佛陀则不如是。又佛陀所收之弟子是来自印度各个阶级，或为婆罗门，或为最低贱阶级。佛陀对他们不分高下，一视同仁，故有「四河入海，不复河名；四姓出家，皆为释种。」9之名言。因生长在不良的社会阶级制度裹，佛陀深知其蔽。彼虽未能积极破坏之，但其所施之僧团者则为其反抗之表示，殆无可疑。如上所述，我人所见历史的佛陀是理智的，且他著重于道德伦理，事事皆合乎法度，其伟大人格与合乎人性的行为是出萃绝伦。若我们以「天神」或「神话」视之，则实际是侮辱及渎冒释迦牟尼佛！

四、佛陀入灭年代

历史佛陀的另一重要点则为彼之入灭年代，中西10学者对此问题颇为关怀及多次为文讨论。至于今日，学者们已大致承认下列日期：佛陀降生：西元前五六三年佛陀入灭：西元前四八三年此结论系根据用巴利文所写的岛史11Dipavamsa及大史12Mahavamsa。该两史籍基于古昔印度与锡兰的传承谓阿输迦王Asoka之祖旃陀掘多ChandraGupta以西元前三二一年即位为摩竭陀王，在位廿四年；其父宾头沙罗Bindusaro在位廿八年，此后四年无国君执政。阿输迦王继承其父于西元前二六五年登位，于其快将即位之前，佛入灭已二一八年，以此推之，其结果为：二六五+二一八=四八三(佛灭年代)四八三+八十=五六三(佛生年代)此外费长房历代三宝记所载之「众圣点记」亦与此推算相近。笔者于数年前曾以英文写稿13名曰AStudyoftheDottedRecord载于一九六五年美国东方学会学报详论此事，并指出高楠顺次郎所定14佛入灭为西元前四八六年之错误，请参考之。

五、神话部份

关于历史佛陀的生活，本经所贡献者已如上述，兹且论其涉及「神话」或「预言」部份：1佛陀之渡恒河似以神通力而不赖船筏之助(第一章33)。2佛陀之舍寿是因恶魔之敦请(第三章34─37)。彼曾数次给阿难以暗示谓修道者可以住寿一劫。但阿难不解佛意，未申劝请(第三章1─6)。故佛陀之舍寿，阿难遭佛谴责，谓咎在于彼(第三章38─48)。恶魔Mara一词有多种解释。若以心理或伦理立场视之，此或为我人之EvilDisposition邪念或邪欲之「人格化」。但一事滋人疑惑者则为为何佛陀必需弟子之启请始欲「住寿一劫」？揆以佛陀之年岁及健康情形(当时彼已届八十高龄)即使阿难会佛旨意恳请「住寿一劫」，佛陀是否即能久远住世，长生不死？此一问题虽非我人所能回答。但以其教理：「当一物既生而成形，即具分离必然性，不要其解离，此何可能。」观之，长生不死，殆不可能，且非佛陀所重视之事。3本经述及佛陀时代之拔塔里村Pataligama即系后来阿输迦王之首都华氏城或波吒□子城Pataliputra(现时之Patna)。经过约二百年之时间，荒僻小村变城国都殊无足怪，但经中曾提及佛陀在该村住时以天眼望见数以千计的神祗在该处划封宅地，并谓：「此拔塔里子城Pataliputta将成为一大都市与商业中心……」(第一章26─28)。此颇含有「预言」意味。吾人固不当疑惑佛之先知或「神通」。但另一可能性则是此段暗示本经之某一部份是约在西元前三世纪顷完成而被添入。将该「预言」托之于佛陀之亲口，颇为该「未来」首都增色不少。4当佛陀舍寿时有大地震(第三章10)，其圆寂时天雨曼陀罗华，而天神如梵天，因陀罗等曾以歌赞致敬(第六章10。其后在□维时神祗等暗示其意向关于佛之遗体应由某方向出城入城(第六章14─18)，以及浊水忽然变为澄清等(第四章21─25)。上列诸点似嫌涉及「神话」，但如果编辑此经的弟子们至诚「相信」伟大的佛陀是应受「人天」礼拜恭敬。他是「天人师」，及「天上天下，唯佛独尊」。他们以不可动摇的「信仰」去打破现实与理想的界限，而认为「实有其事」。那虽是无法去证实，但也是无法去证明其非是。此种问题最好保留，不作定论，以待来者。

本经初稿的译出是在廿多年前当笔者尚在印度国际大学留学。后来个人因忙于各大学之执教与研究工作，且展转由印度赴锡兰，从锡兰至美国，此稿遂被储藏箧中，无暇整理。今夏费时数月细心将原稿修正数次，始得全工告毕，并请台北慧炬出版社刊布流通。在刊印与发行方面，若无周宣德与顾世淦两先生之努力与热忱，则此经或不能立即与世人见面，今特向他们表示甚深谢意。于此，我应向前印度国际大学中国学院院长谭云山教授致最深敬礼，因本经之译出实受彼之提示与指导。彼之化雨春风，令人铭佩不已。彼努力于中印文化复兴及学术交流工作垂四十余年。国际大学中国学院之建立即其伟绩之一。今彼又在印度菩提场─佛初成正觉处创设世界佛学苑中华佛学研究所。虽时殊世易，艰难万状，彼仍以大无畏精神奋力迈进。兹谨馨香祷祝其早日成功。以现代语译巴利文佛经在今日或许是创举。如有欠妥之处，敬希海内外硕德赐教是幸。

一九七一年九月一日 巴宙 叙于美洲爱和华大学

01 此为鸠摩罗什论翻译之语。

02 W.Pachow,ComparativeStudiesintheMaha-Parinibbana-Sutta,pp.5─6,Santiniketan:Visva─BharatiCheena─Bhavana,1946.

03 SeeT.W.andC.A.F.RhysDavida(tr.,TheDialoguesoftheBuddha,PartⅡpp.51┃191,London:LuzacandCompany,一九五九).

04 W.Rahula,HistoryofBuddhisminCeylon,pp.81─82,Colombo:M.D.GunasenaandCo.,1956.

05 S.Radhakrishnan,TheHinduViewofLife,p.82,London:AllenandUnwin,1949.

06 巴宙：论巴利佛典中的阿罗汉，海潮音五十一卷五月号，一九七○。

07 W.Pachow,AComparativeStudyofthePratimoksha,pp.73─78Santiniketan:TheSino-IndianCulturalSociety,一九五五.

08 W.Pachow,"Sukara-maddavaandthe Buddha' sDeath "inthe Annalsofthe Bhandarkar Oriental Research Institute,Silver Jubilee Volume,India,Poona:1942.

09 见增一阿含经29：09大正藏卷二，六五八━六五九页。

10 1W.Geiger,The Mahavamsa,Introduction P.xxvi.2V.A.Smith,Early Historyof India,P.49.3J.F.Fleet,"The DayonWhichBuddhaDied,"in JRAS1909,P.9.4 Gopala Aiyer,"TheDateoftheBuddha,"inthe Indiah Antiquary 1908P.341ff.

11 H.Oldenburg,(Ed.andtr.TheDipavamsa,pp.144─5),London:一八七九

12 W.Geiger,The Mahavamsa,Introdcation, P.xxvi, London: 一九○八. 13W. Pachow, "AStudyofthe Dotted Record," inthe Journalofthe American Oriehtal Society,Vol.85,No.3, 一九六五pp.342─8.14 W.Pachow, ……………… p.343._
* 第一章

01 如是我闻，一时薄伽梵住在王舍城灵鹫山峰。尔时摩竭陀阿□世王━━韦提希之子立意欲征伐越祗人，彼自念言：「我将摧毁越祗人使之根绝种灭，虽然说彼等是很强盛」。

02 于是他告摩竭陀宰相瓦沙卡罗说：「来，婆罗门，你去薄伽梵处称我名顶礼佛足，问其少病少恼，健愉轻安否？你白佛言：『世尊，摩竭陀阿□世王顶礼佛足，并问候世尊少病少恼，健愉轻安否？』又说：『世尊，摩竭陀阿□世王立意欲征伐越祗人，他曾说：『我将摧毁越祗人使之根绝种灭，虽然说彼等是很强盛。』凡薄伽梵所指示者应善忆念，转述于我，因为如来是不语虚妄。」

03 「诚然」，摩竭陀宰相瓦沙卡罗回答说。他下令准备好许多辆精美车乘，自己坐上一辆车，与其侍从离开王舍城进向灵鹫山峰。凡可通车的地方皆以车行，后乃下车步行去到佛陀的住处，到已，同佛陀互叙寒暄及问候起居，就座其侧以后，摩竭陀宰相瓦沙卡罗白佛言：「世尊，摩竭陀阿□世王━━韦提希之子，顶礼佛足，并问候慈座少病少恼，健愉轻安否？彼立意欲征伐越祗人，他曾说：『我将摧毁越祗人使之根绝种灭，虽然说彼等是很强盛』」

04 尔时尊者阿难立于佛后用扇扇佛。薄伽梵语尊者阿难说：「阿难，你是否听闻越祗人常相集会？」「我听闻越祗人常相集会，世尊。」「阿难，当越祗人仍常相集会，则彼等是只会兴盛，不会衰微。阿难，你是否听闻越祗人是一心一德相会、相起及相负责任？」「我听闻越祗人是一心一德相会、相起及相负责任，世尊。」「阿难，当越祗人仍是一心一德相会、相起及相负责任，则彼等是只会兴盛，不会衰微。阿难，你是否听闻越祗人凡有所作为皆依照越祗古昔所传制度，而是未兴者不兴，已兴者不废？」「世尊，我听闻越祗人凡有所作为皆依照越祗古昔所传制度，是未兴者不兴，已兴者不废。」「阿难，当越祗人凡有所作为皆依照越祗古昔所传制度，仍是未兴者不兴，已兴者不废，则彼等是只会兴盛，不会衰微。阿难，你是否听闻越祗人恭敬尊奉其年长者并接受其忠告？」「我听闻越祗人恭敬尊奉其年长者并接受其忠告，世尊。」「阿难，当越祗人仍恭敬尊奉其年长者并接受其忠告，则彼等是只会兴盛，不会衰微。阿难，你是否听闻过越祗人不诱迫其本族的妇女与之同居？」「我听闻越祗人不诱迫其本族的妇女与之同居，世尊。」「阿难，当越祗人仍不诱迫其本族的妇女与之同居，则彼等是只会兴盛，不会衰微。阿难，你是否听闻越祗人恭敬尊奉其城市或乡镇的神舍，不废弃往昔所规定，所遵行的正当祭献？」「我听闻越祗人恭敬尊奉其城市或乡镇的神舍，不废弃往昔所规定，所遵行的正当祭献，世尊。」「阿难，当越祗人仍恭敬尊奉其城市或乡镇的神舍，不废弃往昔所规定，所遵行的正当祭献，则彼等是只会兴盛，不会衰微。阿难，你是否听闻越祗人对诸阿罗汉有适当的保护，防卫及供养，其在远地者将趋赴境内，而已在境内者会平安居处？」「我听闻越祗人对诸阿罗汉有适当的保护、防卫及供养，其在远地者将趋赴境内，而已在境内者会平安居处，世尊。」「阿难，当越祗人仍对诸阿罗汉有适当的保护、防卫及供养，其在远地者将趋赴境内，而已在境内者会平安居处，则彼等是只会兴盛，不会衰微。」

05 于是佛陀语摩竭陀宰相瓦沙卡罗婆罗门说：「婆罗门，往昔我住在□舍离的沙然达达神舍，以此七兴盛法教越祗人，当此七法尚存在于越祗人中，当越祗人仍谆谆以此相训，婆罗门，则彼等是只会兴盛，不会衰微。」时摩竭陀宰相瓦沙卡罗白佛言：「乔达摩，若越祗人有此七兴盛法之一，已只会兴盛，不会衰微，何况彼等有此七法，若如是，乔达摩，摩竭陀国王是不能屈伏越祗人；那是说在战争中得采用诡谋，或离间其同盟，国事繁忙，现请告辞。」佛言：「婆罗门，可宜知时。」时摩竭陀宰相瓦沙卡罗对佛陀的教言发生欣喜，遂离座而去。

06 瓦沙卡罗去已，薄伽梵语尊者阿难说：「阿难，你往告住在王舍城附近的诸比丘尽集讲堂。」「是，世尊。」尊者阿难回答说。他即往告住在王舍城附近的诸比丘尽会讲堂。回来时他向佛作礼，退立一面说：「世尊，比丘僧众已齐集讲堂，唯圣知时。」尔时佛陀即从座起，走向讲堂，就座后，告诸比丘说：「诸比丘，我将宣说七种兴盛法，且专心谛听！」「是，世尊。」诸比丘回答说。薄伽梵说：「诸比丘，当诸比丘(一)仍常相集会；(二)当彼等仍是一心一德相会、相起及相尽力于僧团职务；(三)当彼等依照所制定的律法而行，仍是未兴者不兴，已兴者不废；(四)当彼等仍恭敬尊奉年高望重富于经验之长老，僧伽之师父，并接受其忠告；(五)当能使人转世的贪欲既起，彼等仍不为其所影响；(六)当彼等仍乐于隐居；(七)当彼等仍守心于一，其同道中之良善者将趋赴之，而已来者将平安居处，则彼等是只会兴盛，不会衰微。当此七法尚存在于诸比丘中，当诸比丘仍谆谆以此相训，则彼等是只会兴盛，不会衰微。」

07 「诸比丘，复有七种兴盛法，我将宣说，且专心谛听！」「是，世尊。」诸比丘回答说。薄伽梵说：「诸比丘，(一)当诸比丘仍不喜沾染俗务；(二)当彼等仍不爱好闲谈；(三)当彼等仍不喜偷懒；(四)当彼等仍不喜交游；(五)当彼等仍不怀邪欲，或为邪欲所左右；(六)当彼等仍不与恶人为友或伴侣；(七)当彼等仍不因已证小果而停止进趣最高圣位，则彼等是只会兴盛，不会衰微。当此七兴盛法尚存在于诸比丘中，当彼等仍谆谆以此相训，则彼等是只会兴盛，不会衰微。」

08 「诸比丘，复有七种兴盛法，我将宣说，且专心谛听！」「是，世尊。」诸比丘回答说。薄伽梵说；「当诸比丘仍有(一)信心，(二)耻心，(三)畏恶，(四)多闻，(五)精进，(六)警勤，(七)多智慧，则彼等是只会兴盛，不会衰微。当此七兴盛法尚存在于诸比丘中，当彼等仍谆谆以此相训，则彼等是只会兴盛，不会衰微。」

09 「诸比丘，复有七种兴盛法，我将宣说，且专心谛听！」「是，世尊。」诸比丘回答说。薄伽梵说：「诸比丘，当诸比丘仍修七菩提分：(一)念菩提分，(二)择法菩提分，(三)精进菩提分，(四)喜菩提分，(五)轻安菩提分，(六)禅定菩提分，(七)舍菩提分，则彼等是只会兴盛，不会衰微。当此七兴盛法尚存在于诸比丘中，当彼等仍谆谆以此相训，则彼等是只会兴盛，不会衰微。」

10 「诸比丘，复有七种兴盛法，我将宣说，且专心谛听！」「是，世尊。」诸比丘回答说。薄伽梵说：「诸比丘，当诸比丘仍有(一)无常观，(二)无我观，(三)不净观，(四)邪念危险观，(五)舍离观，(六)心清净观，(七)涅槃观，则彼等是只会兴盛，不会衰微。当此七兴盛法尚存在于诸比丘中，当彼等仍谆谆以此相训，则彼等是只会兴盛，不会衰微。」

11 「诸比丘，复有六种兴盛法，我将宣说，且专心谛听！」「是，世尊。」诸比丘回答说。薄伽梵说：「诸比丘，当诸比丘仍在公在私均以(一)身慈，(二)口慈及(三)意慈对待其同道；(四)当彼等仍公平分配及与其善友分享从僧伽所获得之法定净物，下至钵中所有；(五)当彼等在公在私仍与圣者同居，修习那圆满、不缺、不染、清净、助长智慧，为贤者所称赞，及不为后世欲所玷污的德行；(六)当彼等与圣者同居仍在公在私执持那依之而行可以使痛苦完全毁灭的正见，则彼等是只会兴盛，不会衰微。当此六兴盛法尚存在于诸比丘中，当彼等仍谆谆以此相训，则彼等是只会兴盛，不会衰微。」

12 薄伽梵住王舍城灵鹫山峰与诸比丘如是宣说关于戒定慧的法要。彼谓：「修戒则定有很大利益与果报；修定则慧有很大利益与果报；修慧则心从漏得解脱━━欲漏、有漏、见漏及无明漏。」

13 尔时薄伽梵在王舍城随宜住已，语尊者阿难说：「来，阿难，我等去安巴拉提卡。」「是，世尊。」尊者阿难回答说。于是佛与大比丘僧众向安巴拉提卡进行。

14 于安巴拉提卡，佛陀住在王宫内。彼亦向诸比丘宣说关于戒定慧的法要。彼谓：「修戒则定有很大利益与果报；修定则慧有很大利益与果报；修慧则心从漏得解脱━━欲漏、有漏、见漏及无明漏。」

15 尔时薄伽梵在安巴拉提卡随宜住已，语尊者阿难说：「来，阿难，我等去那烂陀。」「是，世尊。」尊者阿难回答说。于是佛与大比丘僧众向那烂陀进行。到已，佛住在帕瓦哩卡□果林。

16 尔时尊者舍利弗走向佛之住处向佛作礼，就座其侧以后，白佛言：「世尊，我于如来有如是信心：于过去、未来及现在，在高深智慧方面，没有任何其他沙门或婆罗门比如来为更伟大及聪慧。」「舍利弗，你所说如狮子吼是伟大而勇敢。舍利弗，诚然，你发出喜不自胜之歌。你当然知久远世过去诸佛为阿罗汉，正等正觉。是否以你的心了悟彼等的心，并觉知其操行、智慧、生活方式及所证之解脱？」「世尊，不如是。」「既如是，舍利弗，你当然知久远世未来诸佛为阿罗汉正等正觉。是否以你的心了悟彼等的心，并觉知其操行、智慧、生活方式及所证之解脱？」「世尊，不如是。」「既如是，舍利弗，最低限度你知我为现在世阿罗汉、正等正觉。是否以你的心了悟我的心，并觉知我之操行、智慧、生活方式及所证之解脱？」「世尊，不如是。」「既如此，舍利弗，你是不能以你的心了悟过去、现在及未来阿罗汉、正等正觉诸佛的心。舍利弗，为何你所说如狮子吼，是伟大而勇敢？你为何发出如是喜不自胜之歌？」

17 「世尊，我不能了解过去、未来及现在阿罗汉、正等正觉诸佛的心，我只知传承的信仰。世尊，譬如国王有城在其边境，城基城墙及城楼均甚坚固，且唯有一门；其守门者精敏多智，拒纳陌生人，唯许相识者入内。当其环巡该城附近，或许未察及城墙相联处，或有孔之罅隙可容小猫出入。但彼知任何较大动物欲出入此城，非从此门进出不可。世尊，我所知传承的信仰亦复如是。世尊，过去世阿罗汉，正等正觉诸佛舍弃贪、嗔、懒惰、烦恼、困惑。此五障为心病能使解悟羸弱；持心于四正念。兼修习七菩提分而证无上正等正觉之圆果。未来世阿罗汉、正等正觉诸佛亦将如此行之。」

18 薄伽梵住那烂陀的帕瓦哩卡□果林与诸比丘如是宣说关于戒定慧的法要。彼谓：「修戒则定有很大利益与果报；修定则慧有很大利益与果报；修慧则心从漏得解脱──欲漏、有漏、见漏及无明漏。」

19 尔时薄伽梵在那烂陀随宜住已，语尊者阿难说：「来，阿难，我等去拔塔里村。」「是，世尊。」尊者阿难回答说。于是佛与大比丘僧众向拔塔里村进行。

20 尔时拔塔里村诸优婆塞闻佛已到达该处。彼等走向佛所，向佛作礼，就座其侧以后，白佛言：「世尊慈愍，请到村上休息室去。」薄伽梵默然许可。

21 拔塔里村诸优婆塞知佛已接受邀请，从座起向佛作礼，右□毕，即向村上休息室走去。到已，彼等散鲜沙于地，铺设地毯于休息室，安置水瓶并挂上油灯。彼等再到佛前向佛作礼，就座其侧以后白佛言：「世尊，村上休息室已全部布置就绪，鲜沙、地毯、水瓶、油灯，均已安置，唯圣知时。

22 尔时薄伽梵著衣持钵与大比丘僧众走向村上休息室。到已，洗脚入室，靠中柱而坐面向东。比丘僧众亦洗脚入室，靠西壁□佛而坐面向东。拔塔里村诸优婆塞亦洗脚入室，靠东壁坐在佛之对方，面向西。

23 尔时薄伽梵告拔塔里村诸优婆塞说：「诸居士，此是行恶不正直的五失。何者为五？第一，行恶不正直，因懒惰而遭贫困。第二、恶名远播。第三、无论其参加任何社团如刹帝利、婆罗门、居士或沙门━━彼觉得自惭与忐忑不宁。第四、死时忧虑不安。第五、身坏命终，堕入地狱。诸居士，此是行恶的五失。」

24 「诸居士，此是行善的五得。何者为五？第一、行善者因实行正直，因勤奋而获大财富。第二、善名远播。第三、无论其参加任何社团如刹帝利、婆罗门、居士或沙门━━他有自信力和镇定。第四、死时无忧虑。第五、身坏命终，上生天界。诸居士，此是行善的五得。」

25 尔时薄伽梵向拔塔里村的优婆塞开示法要至于深夜，使彼等皆大欢喜。彼谓：「诸居士，现已深夜，可宜知时。」「是，世尊。」彼等回答说；即从座起，向佛作礼，右□而去。于彼等归去后不久，薄伽梵亦退入其丈室。

26 尔时摩竭陀大臣苏尼陀与瓦沙卡罗为抵抗越祗人，在拔塔里村筑城一座。同时有无数神祗，在拔塔里村划封数以千计的宅地。凡宅地是属于有大威力的神祗，彼等恿怂最有权威的国王大臣去该处建造居宅。凡宅地是属于中等神祗，彼等恿怂中等的国王大臣去该处建造屋宇。凡宅地是属于下等神祗，彼等亦怂恿下等的国王大臣去该处兴建房舍。

27 尔时薄伽梵以其伟大超人的天眼望见数以千计的神祗在拔塔里村划封宅地。彼于破晓时分起来语尊者阿难说：「阿难，谁在拔塔里村筑城？」「世尊，摩竭陀大臣苏尼陀与瓦沙卡罗在该处筑城，为抵御越祗人。」

28 「阿难，摩竭陀大臣苏尼陀与瓦沙卡罗为抵御越祗人在拔塔里村筑城，彼等曾与忉利天天神约定。我以我之伟大清明超人的天眼望见数以千计的神祗在拔塔里村划封宅地。凡宅地是属于有大威力的神祗，彼等怂恿最有权威的国王大臣去该处建造居宅。其中神下神亦复如此(其全文见本章第二十六节)。阿难，当阿利安人仍常往还及商贾云集，此拔塔里子城将成为一大都市与商业中心。但此拔塔里子城将有三种危险，一者从火，二者从水，三者从朋友失和。」

29 尔时摩竭陀大臣苏尼陀与瓦沙卡罗走向佛前互叙寒暄及问候起居，侍立其侧以后白佛言：「唯愿世尊慈允今日与大比丘僧众赴舍间午餐。」佛陀默然许可。

30 摩竭陀大臣苏尼陀与瓦沙卡罗知佛许可遂各还家。归家后，备办甜粥糕饼已讫，即来白佛言：「世尊，诸事已备，唯圣知时。」尔时薄伽梵于清晨著衣持钵与大比丘僧众走向摩竭陀大臣苏尼陀与瓦沙卡罗的宅第。到已，坐于敷座。摩竭陀大臣苏尼陀与瓦沙卡罗即亲手奉献甜粥糕饼，以佛为首，下至诸比丘僧。佛食既竟，置钵已，彼等取两小凳，就座其侧。

31 当彼等就座已，佛陀以偈赞曰：任何智者居住此地供养僧众━━能自调伏之善人，以此功德回向划封宅地之神祗。互相敬礼，互相尊敬。彼等以仁慈待之如母亲之对于独子；人为神所眷顾者，彼等常有幸福。佛陀以偈赞叹摩竭陀大臣苏尼陀与瓦沙卡罗己。即从座起。离去。

32 尔时摩竭陀大臣苏尼陀与瓦沙卡罗尾随佛后说：「今天沙门乔达摩从某门出，该门将名为『乔达摩门』；从某渡头渡河，该渡头将名为『乔达摩渡』。」其后佛所从出之门是名为「乔达摩门」。

33 尔时薄伽梵走向河边。时恒河水涨泛，欲渡河者或求船，或求筏，或求桴。世尊此时如大力士一屈伸臂顷即不见于恒河此岸，与诸大比丘僧众再出现于恒河彼岸。

34 尔时薄伽梵见人求船、求筏或求桴，欲用渡河，遂说偈曰：幻世正缚扎筏桴，已渡苦海者造桥梁以渡池沼，彼为知者，彼为得救者。
* 第二章


01 尔时世尊语尊者阿难说：「来，阿难，我等去柯提村。」「是，世尊。」尊者阿难回答说。于是佛与大比丘僧众向柯提村进行。到已，佛陀即在村上住。

02 尔时佛告诸比丘说：「诸比丘，因未能了解四种圣谛，我等长期轮转生死之途。何者为四？诸比丘，是苦谛、苦因谛、苦灭谛、和引苦入于毁灭之途的道谛。诸比丘，若能了解此四圣谛，则取欲已尽，有因已灭，从此不再受生」。

03 薄伽梵说是语已，复以偈颂曰：因不了解四圣谛之真实性所以流传于生死长途。既已了悟，则生因已绝，苦根已断，从此不再受生。

04 薄伽梵在柯提村住时亦向诸比丘如是宣说关于戒定慧的法要。彼谓：「修戒则定有很大利益与果报；修定则慧有很大利益与果报；修慧则心从漏得解脱－－欲漏、有漏、见漏及无明漏。」

05 尔时薄伽梵在柯提村随宜住已，语尊者阿难说：「来，阿难，我等去那低卡。」「是，世尊。」尊者阿难回答说。于是佛与大比丘僧众向那低卡进行。到已，佛陀住在砖屋。

06 尔时尊者阿难走向佛前向佛作礼，就座其侧以后，白佛言：「世尊，有名沙尔哈比丘者死在那低卡，彼转生何处？命运如何？世尊，有名难陀比丘尼者死在那低卡，伊转生何处，命运如何？」同时并问及优婆塞苏达塔，优婆夷苏伽塔，优婆塞卡苦陀，羯□伽，尼卡达，卡提沙跋，兔他，山兔他，苏跋陀等，彼等转生何处及命运如何。

07 「阿难，沙尔哈比丘，彼于此世之身漏己尽，已证悟心解脱、慧解脱及获得阿罗汉果。阿难，难陀比丘尼已断除束缚人群于此欲界的五缚，已投生天界，于彼处寂灭后，即不复再来此世。阿难，优婆塞苏达塔已断除三结，并减削淫、怒、痴，已证斯陀含果，只转世一次，即得苦竟。阿难，优婆夷苏伽塔已断除三结，已获取不堕恶趣的须陀洹果，必证佛果。阿难，优婆塞卡苦陀已断除束缚人群于此欲界的五缚，已投生天界，于彼寂灭后，即不再来此世。阿难，优婆塞羯□伽，尼卡达、卡提沙跋、兔他、山兔他、跋陀、苏跋陀等已断除束缚人群于此欲界的五缚，已投生天界，于彼寂灭后，即不再来此世。阿难，复有五十余位优婆塞死在那低卡者，亦复如是。阿难，更有九十余位优婆塞死在那低卡者，已断除三结，并减削淫怒痴，已证得斯陀含果，只转世一次，即得苦竟。阿难，复有五百余位优婆塞死在那低卡者，已断除三结，已获取不堕恶趣的须陀洹果，必证佛果。

08 「阿难，人生有死，何足为奇。若每死一人，皆来问我，使我疲乏之至。因此，阿难，我将为汝宣说法镜。若圣弟子有此，即能预知其未来：地狱已毁，我不堕于畜生、饿鬼及其他苦趣。我已获取不堕恶趣的须陀洹果，必证佛果。

09 「阿难，何名法镜？若圣弟子有此，即能预知其未来：地狱已毁，我不堕于畜生、饿鬼及其他苦趣？阿难，谓圣弟子于世信佛－－相信佛陀是：如来、应供、正□知、明行足、善逝、世间解、无上士、调御丈夫、天人师、佛世尊。信法－－相信佛所说法利益世间、永恒、欢迎群众、示解脱道、使智者各自证悟。信僧－－相信僧是佛之弟子，修持八正道之四阶段、正直、奉法、具足净戒。彼等是值得敬礼，为世间无上福田，为善人所喜；其戒行是不犯不缺，不染不沾，使人解脱，为智者所称赞，不为有欲，或相信外在作为之效力所玷污，及助长禅定。「阿难，此是法镜。若圣弟子有此，即能预知其未来：地狱已毁，我不堕于畜生、饿鬼及其他苦趣。我已获取不堕恶趣的须陀洹果，必证佛果。」

10 佛陀在那低卡砖屋住时亦与诸比丘如是宣说关于戒定慧的法要。彼谓：「修戒则定有很大利益与果报；修定则慧有很大利益与果报；修慧则心从漏解脱----欲漏、有漏、见漏及无明漏。」


11 尔时薄伽梵在那低卡随宜住已，语尊者阿难说：「来，阿难，我等去□舍离。」「是，世尊，」尊者阿难回答说。于是佛与大比丘僧众向□舍离进行。到已，佛住于□婆婆梨园。

12 佛告诸比丘说：「诸比丘，比丘当摄心住念。此为我等之教言。」

13 「诸比丘，云何名比丘摄心住念？比丘因有身当观身，精勤不懈，摄心住念，舍弃世间渴望与失意。其观感觉、观意与观法亦复如是：精勤不懈，摄心住念，舍弃世间渴望与失意。」「诸比丘，云何名比丘自摄？当比丘履进履退、前瞻后顾、屈臂伸臂、著衣持钵、饮食吞嚼、行大小便、行立坐、睡眠、醒悟、言谈及静默、皆摄心住念。诸比丘当摄心住念，此为我等之教言。」

14 尔时歌女□婆婆梨闻佛已到□舍离，住于伊之□果林。伊下令准备好许多辆精美车乘，自己坐上一辆车，与其侍从离开□舍离进向伊之园林。凡可通车的地方皆以车行，后乃下车步行去到佛之住处。到已，向佛作礼，就座其侧以后，薄伽梵向伊宣示法要，使伊欢喜愉快。歌女□婆婆梨对佛所示法要甚为喜悦，伊白佛言：「唯愿世尊慈允于明日与大比丘僧众赴舍间午餐。」佛陀默然受请。伊知佛已许可，即从座起，向佛作礼，右□而去。

15 尔时□舍离的隶车闻佛已到□舍离住于□婆婆梨园，彼等下令准备好许多辆精美车乘，各坐上一辆车，与其侍从离开□舍离。彼等或现黯色，著青色，青衣及青色饰品；或现黄色，□黄色，黄衣及黄色饰品；或现红色，□红色，红衣及红色饰品；或现白色，□白色，白衣及白色饰品。

16 尔时歌女□婆婆梨与诸隶车少年车轴相接，车轮相撞及车轭相触。诸隶车告伊说：「□婆婆梨，为何你与诸隶车少年车轴相接，车轮相撞及车轭相触？」「因我已请佛及比丘僧众明天到舍下午餐。」「□婆婆梨给你十万，让此斋与我们。」「你若给我全□舍离及所属土地，我犹不舍此盛供。」于是诸隶车振手说：「此□果女获胜，我等被此□果女占优胜。」彼等遂进行到□婆婆利园。

17 薄伽梵见诸隶车自远而至，告诸比丘说：「诸比丘，凡未曾见过忉利天天神的比丘，且观看此群隶车，注视此群隶车及比较此群隶车，因其与忉利天天神无异。」

18 诸隶车凡可通车的地方皆以车行，后乃下车步行去到佛陀的住处。到已，向佛作礼，就座其侧以后，薄伽梵向彼等宣示法要，使其发心喜悦。诸隶车对佛陀所示法要殊为欣悦，遂白佛言：「谁愿世尊慈允于明日与大比丘僧众赴舍间午餐。」「诸隶车，我已首肯明日赴歌女□婆婆梨处午餐。」于是诸隶车振手说：「此□果女获胜。我等被此□果女占优胜。」诸隶车对佛陀的教言表示感谢与同意，即从座起，向佛作礼，右□而去。

19 尔时歌女□婆婆梨于其夜清旦在自己家裹备办甜粥糕饼，即白佛言：「世尊，诸事已备，唯圣知时。」尔时薄伽梵于清晨著衣持钵，与大比丘僧众走向歌女□婆婆梨的宅第。到已，坐于敷座。歌女□婆婆梨即亲手奉献甜粥糕饼，以佛为首下至诸比丘僧。佛食既竟，浣手洗钵已，歌女□婆婆梨取一小凳，就座其侧以后，伊白佛言：「世尊，我以此园奉献以佛为首的比丘僧众。」薄伽梵既接受此礼品，向伊宣示法要，使之发心喜悦后即从座起而去。

20 薄伽梵在□舍离□婆婆梨园住时亦向诸比丘如是宣说关于戒定慧的法要。彼谓：「修戒则定有很大利益与果报；修慧则定有很大利益与果报；修慧则心从漏得解脱－－欲漏、有漏、见漏及无明漏。」

21 尔时薄伽梵在□婆婆梨园随宜住已，语尊者阿难说：「来，阿难，我等去白鹿瓦村。」「是，世尊。」尊者阿难回答说。于是佛与大比丘僧众向白鹿瓦村进行。到已，佛陀住于白鹿瓦村。

22 尔时薄伽梵告诸比丘说：「诸比丘，汝等各于□舍离附近的朋友、相识或知己处过雨季，我则在白鹿瓦村过雨季。」「是，世尊。」诸比丘回答说。彼等遂在□舍离附近的朋友、相识或知已处过雨季，而佛陀则在白鹿瓦村过雨季。

23 尔时世尊在雨季中匆罹剧痛痢疾，几乎殒命。但彼摄心住念忍受之，无怨言。薄伽梵自念：若我不告诫弟子及向比丘僧众告辞而取涅槃，实非所宜，今且以坚强意志屈伏此疾，留住应享寿命。于是佛陀以坚强意志屈伏疾病，并留住应享寿命。其后病亦渐瘥。

24 薄伽梵不久即告痊愈。病愈后彼从住室出坐于荫处敷座上，尔时尊者阿难走向佛前向佛作礼，就座其侧以后，白佛言：「世尊，我曾见薄伽梵于康健时，及见其如何受苦。世尊，当我见佛陀病时，虽然我身羸弱如蔓藤，及神志昏迷不辨方向，便一念及：『若薄伽梵未将遗教与比丘僧众，彼将不证取涅槃。』我联以自慰。」

25 「阿难，是否比丘僧众盼望我之遗教？阿难，我所说法或显或隐，是无分别，如来于法是无秘密，吝而不传。阿难，若人作如是念：「我将引导僧伽」，或「僧伽以我为依怙」，则此人应对僧伽设立教言，但如来不作此想。阿难，为何如来应留关于僧伽之遗教？阿难，我今年已老矣，衰耄矣，旅程将尽，寿命将满。我行年八十，譬如旧车方便修理，尚勉强可行。阿难，我想如来之身体亦复如是，应方便摄养，阿难当如来停止顾念外事，及任何感觉皆已停止而入于灭想定时，如来之身，始为安隐。」

26 「因此，阿难，以自己为明灯、为归依，勿以他人为归依；以法为明灯、为归依，勿以他人为归依。阿难，云何为比丘以自己为明灯、为归依，勿以他人为归依；以法为明灯、为归依，勿以他人为归依？「阿难，比丘当观身，精勤不懈，摄心住念，舍弃世间渴望及失意。其观感觉、观意与观法亦复如是。阿难，此是比丘以自己为明灯、为归依，勿以他人归依；以法为明灯、为归依，勿以他人为归依。「阿难，无论现在或我去世后，若有人以自己为明灯、为归依，勿以他人为归依；以法为明灯、为归依，勿以他人为归依。阿难，彼等在我之比丘中将诣最高境界－－但必须乐于修学。」


* 第三章


01 尔时世尊于清晨著衣持钵往□舍离乞食。行乞归来后，饭食已毕，彼告尊者阿难说：「阿难，携取坐具，我将去洽巴拉神舍休息。」「是，世尊。」尊者阿难回答说，即携坐具随从佛后。

02 于是薄伽梵走向洽巴拉神舍，坐于敷座上。尊者阿难亦就坐其侧。坐已，薄伽梵告尊者阿难说：「阿难，□舍离是一可喜悦之处。而乌但那神舍、乔达摩卡神舍、七□果神舍、多子神舍、沙然达达神舍、洽巴拉神舍等亦是可喜乐的。

03 「阿难，若有人修持、留住、扩展四神足的极顶，既精于此，可用之如车乘，以此为基础，若欲，彼可住寿一劫，或其劫之某部份。而佛陀曾充份修持，扩展此四神足(其详见上)，彼若有意，可住寿一劫或其劫之某部份。」

04 尊者阿难对佛陀所给与之明显提示未能了解，他未曾恳请世尊说：「世尊，请住寿一劫，慈尊为众生之利益与快乐，及慈愍此世界，为人天之利益，快乐与幸福，请寿一劫！」因其心为魔所蒙蔽。

05 如是再三，薄伽梵告尊者阿难说(其详见上)。但尊者阿难数次均为魔所蒙蔽。

06 于是薄伽梵告尊者阿难说：「去，阿难，可宜知时。」「是，世尊。」尊者阿难回答说。即从座起，向佛作礼，右□而去，坐于一附近树下。

07 尔时恶魔于尊者阿难去后不久，即来至佛所，立于其侧，白佛言：「世尊，薄伽梵现在应入涅槃。慈尊，现在正是如来入涅槃之时，请速入涅槃，甚至根据前薄伽梵所说：『恶魔，若我之比丘、比丘尼、优婆塞优婆夷，尚未成为正闻、聪慧、善摄、多闻、熟记圣典、精娴教义、奉持戒律；既精于法，乃能教导、宣演、建立、开启、详释、明辨，能以正法扫荡，降伏异论，及广宣妙法－－之弟子时，我将不入涅槃。』

08 世尊，现在诸比丘、比丘尼、优婆塞、优婆夷皆已成为正闻、聪慧、善摄……(其详见上)之弟子。世尊，薄伽梵现在应入涅槃。慈尊，现在正是如来入涅槃之时，请速入涅槃！甚至依照薄伽梵所说：『恶魔，若我之清净教不成功、兴盛、广布、普遍及遍传于人间时，我将不入涅槃。』世尊，现在你之清净教已成功、兴盛、广布、普遍、及遍传于人间。世尊，薄伽梵现在应入涅槃。慈尊，现在正是如来入涅槃之时，请速入涅槃！」

09 他既作此语，薄伽梵告恶魔说：「恶魔，你且自喜。佛之圆寂已近。此后三月如来即将入涅槃。」

10 尔时薄伽梵于洽巴拉神舍谨然住念舍寿。佛既舍寿，有大地震，殊可惊怖及天雷响震。佛见此事已，既说偈曰：生命之源无量或微小。牟尼今舍其寿数。以内心静乐，打破其如甲胄之生命之源。

11 尔时尊者阿难自念：「此诚奇妙不可思议。此大地震殊可惊怖及天雷响震，此地震出现之远近因缘究何所在？」

12 于是尊者阿难走向佛前向佛作礼，就座其侧以后，白佛言：「世尊，此诚奇妙不可思议，此大地震殊可惊怖及天雷响震。世尊，此地震出现之远近因缘究何所在？」

13 「阿难，大地震之出现有八种因缘，何者为八？阿难，此大地止于水上，水止于风，风止于空。阿难，有时空中起大风，起大风则水动，水动则地动。此为大地震出现之第一因缘。

14 「复次，阿难，有时具大智慧力之沙门或婆罗门作摄心想；或有大威神之神祗－－当彼等观水想多，观地想少，地即大震动。此为大地震出现之第二因缘。

15 「复次，阿难，当菩萨谨然住念离兜率天而入于母胎时，地即大震动。此为大地震出现之第三因缘。

16 「复次，阿难，当菩萨谨然住念出母胎时，地即大震动，此为大地震出现之第四因缘。

17 「复次，阿难，当如来证无上正等觉时，地即大震动。此为大地震出现之第五因缘。

18 「复次，阿难，当如来转无上*轮时，地即大震动。此即大地震出现之第六因缘。

19 「复次，阿难，当如来谨然住念舍寿时，地即大震动。此为大地震出现之第七因缘。

20 「复次，阿难，当如来于无余涅槃界证取涅槃时，地即大震动。此为大地震出现之第八因缘。阿难，此为大地震出现之八种因缘。」

21 「阿难，有八种众。何者为八？即：刹帝利众、婆罗门众、居士众、沙门众、四天王众、忉利天众、魔众及梵天众。

22 「阿难，我忆念往昔曾参加一约数百人之刹帝利众。于我未就座、或言说、或交谈以前，我使我自己与其颜色相同、与其声音相同，以法要示教利喜之。当我宣说时，彼等不识我，自问说：『宣说者为谁？是神是人？』以法要示教利喜之后，我即隐身不见。彼等亦不知我何时隐去，自问说：『隐去者为谁？是神是人？』

23 「阿难，我忆念往昔曾参加一约数百人之婆罗门众、居士众、沙门众、四天王众、忉利天众、魔众及梵天众。于我未就座、或言说、或交谈以前，我使我自己与其颜色相同，与其声音相同，以法要示教利喜之。当我宣说时，彼等不识我，自问说：『宣说者为谁？是神是人？』以法要示教利喜之后，我即隐身不见。彼等亦不知我何时隐去，自问说：『隐去者为谁？是神是人？』阿难，此为八种众。」

24 「阿难，有八胜处。何者为八？

25 「阿难，若人有主观色想视外间有限或苦或乐之诸相，既专精于此，遂有『我知我见』之念。此为第一胜处。

26 「若人以主观色想视外间无穷或苦或乐之诸相，既专精于此，遂有『我知我见』之念。此为第二胜处。

27 「若人无主观色想视外间有限或苦或乐之诸相，既专精于此，遂有『我知我见』之念。此为第三胜处。

28 「若人以无主观色想视外间无穷或苦或乐之诸相，既专精于此，遂有『我知我见』之念。此为第四胜处。

29 「若人以无主观色想视外间诸相是青色、青相、青映影。正如乌马花是青色、青相、青映影。又如波罗奈所产细布，表裹精致是青色、青相、青映影。若如此以无主观色想视外间诸相是青色、青相、青映影，既专精于此，遂有『我知我见』之念。此为第五胜处。

30 「若人以无主观色想视外间诸相是黄色、黄相、黄映影。正如堪尼卡罗花是黄色、黄相、黄映影。又如波罗奈所产细布，表裹精致是黄色、黄相、黄映影，既专精于此，遂有『我知我见』之念。此为第六胜处。

31 「若人以无主观色想视外间诸相是红色、红相、红映影。正如班都几瓦卡是红色、红相、红映影，又如波罗奈所产细布，表裹精致是红色、红相、红映影，既专精于此，遂有『我知我见』之念。此为第七胜处。

32 「若人以无主观色想视外间诸相是白色、白相、白映影。正如俄沙底星是白色、白相、白映影。又如波罗奈所产细布，表裹精致是白色、白相、白映影。若人如此以无主观色想视外间诸相是白色、白相、白映影，既专精于此，遂有『我知我见』之念。此为第八胜处。阿难，此为八胜处。」

33 「阿难，此为八解脱。何者为八？「以相见相，是第一解脱。「不觉其自相见外间诸相，是第二解脱。「存心于善，是第三解脱。「超出诸色想，断除诸愤怒想，不思念诸相，自念：是『空无边』而入于空无边处定，是第四解脱。「超出空无边处，自念：是『识无边处』而入于识无边处定，是第五解脱。「超出识无边处，自念：是『无所有』而入于无所有处定，是第六解脱。「超出无所有处，自念：是『非想非非想』而入于非想非非想处定，是第七解脱。　「超出一切『非想非非想处』而入于灭想定，是第八解脱。阿难，此为八解脱。

34 「阿难，往昔我于尼连禅河岸边，牧羊人菩提树下初成正觉时，彼时恶魔来至我所，立于我侧向我说：『世尊，薄伽梵现在应入涅槃。慈尊，现在正是如来入涅槃之时，请速入涅槃。』

35 「阿难，彼作是语已，我告恶魔说：『恶魔，若我之比丘、比丘尼、优婆塞、优婆夷尚未成为正闻、聪慧、善摄、多闻、熟记圣典、精娴教义、奉持戒律；既精于法乃能教导、宣演、建立、开启、详释、明辨；能以正法扫荡、降伏异论及广宣妙法之弟子时，我将不入涅槃。「『恶魔，若我之清净戒不成功、兴盛、广布、普遍及遍传于人间时，我将不入涅槃。』

3637 「阿难，我今于洽巴拉神舍，该恶魔复来我所，立于我侧向我说：『世尊，薄伽梵现在应入涅槃。慈尊，现在正是如来入涅槃之时，请速入涅槃！世尊，即使依照前薄伽梵所说：(其详见上)』「阿难，他既作此语，我告恶魔说：『恶魔，你应欢喜！佛陀不久即将圆寂。此后三月，如来即将入涅槃。』「阿难，如来今日于洽巴拉神舍谨然住念舍寿。」

38 彼说是语时，尊者阿难白佛言：「世尊，请住寿一劫，慈尊为众生之利益与快乐，及慈愍此世界，为人天之利益、快乐与幸福，请住寿一劫！」「阿难，止止，莫恳请如来。现今劝请如来，已非其时。」

39 如是第二第三(阿难如是恳请，佛陀如是回答)。「阿难，你对佛陀之智慧是否有信仰？」「是，世尊。」「阿难，你为何烦扰如来至于第三次？」

40 「世尊，我亲从佛闻及亲从佛受：『若有人修持、留住、扩展及抵达四神足的极顶，既精于此，可用之如车乘。以此为基础，若欲，彼可住寿一劫或劫之剩余部份；而佛陀曾充份修持、扩展及抵达此四神足………(其详见上)他若有意，可住寿一劫或其劫之某部份。』「阿难，你是否有信仰？」「是，世尊。」「阿难，此是你之错误及罪过。前如来给与你之明显提示，你都未能了解，未曾恳请如来说：『世尊，请住寿一劫，慈尊为众生之利益与快乐，及慈愍此世界，为人天之利益，快乐与幸福，请住寿一劫。』阿难，你若如是垦请如来，至于第二次，他或不俯允，但第三次他或将纳受。因此，阿难，此是你之错误及罪过！」

41 「阿难，往昔我住王舍城灵鹫山峰时亦曾向你说：『阿难，王舍城与灵鹫山峰是甚可喜乐之处。阿难，若有人修持、留住、扩展及抵达四神足的极顶，既精于此，可用之如车乘。以此为基础，若欲，彼可住寿一劫或其劫之剩余部份；而佛陀曾充份修持、扩展及抵达此四神足……(其详见上)，他若有意，可住寿一劫或其劫之剩余部份。』而你，阿难，如来给与你之明显提示，你都未能了解，未曾恳请如来说：『世尊，请住寿一劫，慈尊为众生之利益与快乐，及慈愍此世界，为人天之利益、快乐与幸福，请住寿一劫！』阿难，你若如是恳请如来至于第二次，他或不俯允，但第三次他或将纳受。因此，阿难，此是你之错误及罪过！」

42 「阿难，往昔我住王舍城榕树园，住王舍城贼峰，住王舍城韦跋罗坡之沙打畔尼洞，住王舍城伊思□里坡之黑岩，住王舍城沙巴桑底卡山□斯塔园，住王舍城塔坡达园，住王舍城竹园喂松鼠处，住王舍城耆婆之□果，住王舍城马打苦其之鹿林。

43 「阿难，在上列各处，我也曾向你说：『阿难，王舍城等等(其详见上)是甚可喜乐之处。』

44 「『阿难，若有人修持、留住、扩展及抵达四神足的极顶，既精于此，可用之如车乘。经此为基础，若欲，彼可住寿一劫或其劫之剩余部份；而佛陀曾充份修持、扩展及抵达此四神足(其详见上)，他若有意，可住寿一劫或其劫之剩余部份。』而你，阿难，如来给与你之明显提示，你都未能了解，未曾恳请如来说：『世尊，请住寿一劫，慈尊为众生之利益与快乐，及慈愍此世界，为人天之利益、快乐与幸福，请住寿一劫！』阿难，你若如是恳请如来至于第二次，他或不俯允，但第三次他或将纳受。因此，阿难，此是你之错误及罪过！」

45 「阿难，往昔我住□舍离之乌但拉神舍时，亦曾向你说『阿难，□舍离与乌但拉是甚可喜乐之处。若有人修持、留住、扩展及抵达四神足的极顶，既精于此，可用之如车乘，以此为基础，若欲，彼可住寿一劫或其劫之剩余部份；而佛陀曾充份修持、留住及扩展此四神足……(其详见上)，他若有意，可住寿一劫或其劫之剩余部份。』而你，阿难，如来给与你之明显提示，你都未能了解，未曾恳请如来说：『世尊，请住寿一劫，慈尊为众生之利益与快乐，及慈愍此世界，为人天之利益、快乐与幸福，请住寿一劫！』阿难，你若如是恳请如来至于第二次，他或不俯允，但第三次他或将纳受。因此，阿难，此是你之错误及罪过！」

46 「阿难，往昔我住□舍离之乔达摩卡神舍，住□舍利之七□果神舍，住□舍离之多子塔神舍，住□舍离之沙然达达神舍时，亦曾向你说：『阿难，□舍离各地是甚可喜乐之处……。」(其祥见上)

47 「阿难，现今在洽巴拉神舍，我也曾向你说：『阿难，□舍离是甚为幽静，乌但拉神舍，乔达摩卡神舍，七□果神舍，多子塔神舍，沙然达达神舍等是甚可喜乐之处。若有人修持、留住、扩展及抵达四神足的极顶，既精于此，可用之如车乘，以此为基础，若欲，彼可住寿一或其劫之剩余部份；而佛陀曾充份修持、留住及扩展此四神足。他若有意，可住寿一劫或其劫之剩余部份。』而你，阿难，如来给与你之明显提示，你都未能了解，未曾恳请如来说：『世尊，请住寿一劫，慈尊为众生之利益与快乐，及慈愍此世界，为人天之利益、快乐与幸福，请住寿一劫！』阿难，你若如是恳请如来至于第二次，他或不俯允，但第三次他或将纳受。因此，阿难，此是你之错误及罪过！」

48 「阿难，是否往昔我曾告诉你说：万物实性如此，其与我们最亲近者将要与我们分别隔离？当一物既生而成形，既具分离必然性，不要其解离，此何可能，且必无此理。阿难，如来已舍弃寿命。且他一言既出：『佛陀之圆寂甚近，此后三月如来即将入涅槃。』如来为生存而食言，应无是处！」「来，阿难，我等去大林的重阁讲堂。」「是，世尊。」尊者阿难回答说。

49 尔时佛陀与尊者阿难走向大林的重阁讲堂。到已，佛告尊者阿难说：「阿难。你往告住在□舍离附近的诸比丘尽集讲堂。」「是，世尊。」尊者阿难回答说。他即往告住在□舍离附近的诸比丘尽会讲堂。回来时他向佛作礼，退立一面说：「世尊，比丘僧众已齐集讲堂，唯圣知时。」

50 于是薄伽梵从座起，走向讲堂，就座已，告诸比丘说：「因此，诸比丘，我所知及为汝等所宣说之法，当善学、善修、善思、善布，因而梵教可以长远住世。此是为众生之利益与快乐，及慈愍此世界，为人天之利益、快乐与幸福。诸比丘，云何为我所知及为汝等所宣说之法，当善学、善修、善思、善布，因而梵教可以长远住世。此是为众生之利益与快乐，及慈愍此世界，为人天之利益、快乐与幸福？盖即：四念处四正勤四神足五根五力七菩提分八圣道诸比丘，此是我所知及为汝等所宣说之法，当善学、善修、善思、善布，因而梵教可以长远住世。此是为众生之利益与快乐，及慈愍此世界，为人天之利益、快乐与幸福。」

51 尔时薄伽梵告诸比丘说：「诸因缘合和法皆归老朽，当精勤取证！如来的圆寂甚近，此后三月，如来即将入涅槃。」薄伽梵说此后，复以偈曰：我之生命已成熟，我之寿命将尽。我将离尔等而去，独依靠我自己。诸比丘当精勤、持净及善思维，应有坚定决心及自观心。谁能勤恳住于法与戒，则超度生命之海，而证得苦尽。
* 第四章


01 尔时世尊于清晨著衣持钵去□舍离乞食。行乞后，饭食已毕，从城中托钵归来时，他以象视－－回身转顾□舍离，告尊者阿难说：「阿难，此为如来最后顾视□舍离。来，阿难，我等去班达镇。」「是，世尊。」尊者阿难回答说。于是佛与大比丘僧众向班达镇进行。到已，如来即住在镇上。

02 尔时佛告诸比丘说：「诸比丘，因不了解四种法，我与汝等长期奔陟于生死之途。何者为四？诸比丘，是圣戒、圣定、圣慧及圣解脱。诸比丘，若能了解及证悟此四种法，，则世欲已尽，尘缘已绝，永久不受后有。」

03 薄伽梵作如是语已，慈喜之导师复以偈曰：戒定慧与无上解脱，此为乔达摩所证最著之法。智者以所知之法宣示诸比丘，导师以天眼使苦尽而证涅槃。

04 佛陀在班达镇时亦向诸比丘如是宣说圆满法语：「此为戒，此为定，此为慧。修戒则定有很大利益与果报，修定则慧有很大利益与果报，修慧则心从漏得解脱－－欲漏、有漏、见漏及无明漏。」

05 尔时薄伽梵在班达镇随宜住已，语尊者阿难说：「来，阿难，我等去哈谛镇、□果镇、江捕镇及波□城。」

06「是，世尊。」尊者阿难回答说。于是佛与大比丘僧众向上列诸处进行(每处均复述上列之二、三、四各节)。

07 到已，佛陀即住在波□城之阿难陀神舍。彼告诸比丘说：「诸比丘，我将宣说四大教法，且专心谛听！」「是，世尊。」诸比丘回答说。

08 薄伽梵说：「诸比丘，若有比丘作如是语：『此是法，此是律，此是导师之教言，我从佛亲口闻受。』诸比丘对该比丘所言，不应称赞，也不应藐视，应了解其每字与音节，而与经律相比较、相对照；既较对以后，若其不与经律相符，则其结论应为：『诚然，此非佛陀之教言，而是该比丘之误会。』因此，诸比丘，汝等应拒绝之。若与经律相比较、相对照以后，彼能与之相符，则其结论应为：『诚然，此是佛陀之教言，该比丘善了解之。』诸比丘，此是第一大教法，应当学。

09 「复次，诸比丘，若比丘作如是语：『于某寺宇有僧伽及其长老与导师居住，我从其僧团亲口听受：此是法，此是律，此是导师之教言。』诸比丘对该比丘所言不应称赞，也不应藐视，应了解其每字与音节，而与经律相比较、相对照；既较对以后，若其不与经律相符，则其结论应为：『诚然，此非佛陀之教言，而是该比丘之误会。』因此，诸比丘，汝等应拒绝之。若与经律相比较、相对照以后，彼能与之相符，则其结论应为：『诚然，此是佛陀教言，该比丘善了解之。』诸比丘，此是第二大教法，应当学。

10 「复次，诸比丘，若比丘作如是语：『于某寺宇住有众多博学多闻、深具信仰、深入于法、精娴□尼及通晓律尼的僧团长老。我从诸长老亲口听受：此是法，此是律，此是导师之教言。』诸比丘对该比丘所言，不应称赞，也不应藐视，应了解其每字与音节，而与经律相比较、相对照；既较对以后，若其不与经律相符，则其结论应为：『诚然，此非佛陀之教言，而是该比丘之误会。』因此，诸比丘，汝等应拒绝之。若与经律相比较、相对照以后，彼能与之相符，则其结论应为：『诚然，此是佛陀之教言，该比丘善了解之。』诸比丘，此是第三大教法，应当学。

11 「复次，诸比丘，若比丘作如是语：『于某寺宇住有一博学多闻、深具传统信仰、深入于法、精娴□尼及通晓律仪的比丘。我从该长老亲口听受：此是法，此是律，此是导师之教言。』诸比丘对该比丘所言，不应称赞，也不应藐视，应了解其每字与音节，而与经律相比较、相对照；既较对以后，若其不与经律相符，则其结论应为：『诚然，此非佛陀之教言，而是该比丘之误会。』因此，诸比丘，汝等应拒绝之。若与经律相比较、相对照以后，彼能与之相符，则其结论应为：『诚然，此是佛陀之教言，该比丘善了解之。』诸比丘，此是第四大教法，应当学。「诸比丘，此是四大教法应当学！」

12 薄伽梵在波□城阿难陀神舍住时，亦向诸比丘如是宣说圆满法语：「此为戒，此为定，此为慧。修戒则定有很大利益与果报；修定则慧有很大利益与果报；修慧则心从漏得解脱－－欲漏，有漏，见漏及无明漏。」

13 尔时薄伽梵在波□城随宜住已，告尊者阿难说：「来，阿难，我等去波婆。」「是，世尊。」尊者阿难回答说。于是佛与大比丘僧众向波婆进行。到已，佛住于铁匠穷达的□果林。

14 铁匠穷达闻佛已到达波婆，且住于彼之□果林。于是彼走向如来的住处，向佛作礼，就座其侧以后，薄伽梵向其宣示法要，使之欢喜愉快。

15 穷达对佛所开示的法要甚为喜悦，他白佛言：「唯愿世尊慈允于明天与大比丘僧众赴舍间午餐。」佛陀默然受请。

16 穷达知佛已许可，即从座起，向佛作礼，右□而去。

17 尔时铁匠穷达于其夜清旦在自己家裹备办甜粥糕饼及□檀树耳1，即白佛言：「世尊，诸事已备，唯圣知时。」1巴利原文为Sukara-maddava似为菌类植物)

18 尔时薄伽梵于清晨著衣持钵，与大比丘僧众走向铁匠穷达家裹。到已，坐于敷座后佛告穷达说：「穷达，凡是你所备办的□檀树耳尽奉献与我，其他食物如甜粥等则分给比丘僧众。」「是，世尊。」穷达回答说。于是他将所备办的□檀树耳献佛，其他食物如甜粥等，则分奉给比丘僧众。

19 尔时薄伽梵告穷达说：「穷达，所有余剩的□檀树耳应埋藏一小孔裹。穷达，我不见地上任何人、或魔、天、与梵天、或沙门、婆罗门、或神、或人，除如来外，若服食该物能有适宜的消化。」「是，世尊。」穷达回答说。他将余剩的□檀树耳埋藏一小孔后，走向佛前向佛作礼。他就座其侧以后，佛陀向穷达开示法要，使之发心喜悦，即从座起而去。

20 尔时薄伽梵于服食铁匠穷达所设斋供后，匆患严重性血痢，剧痛几濒于死。但彼摄心自持，忍受而无怨言。于是薄伽梵语尊者阿难说：「来，阿难，我等去拘尸那罗。」「是，世尊。」尊者阿难回答说。我闻彼服食铁匠穷达的斋供以后，彼忍受几濒于死的剧痛。因进用□檀树耳，慈尊所以患此严重性疾病。薄伽梵于清泻后说：「我等去拘尸那罗城。」

21 尔时薄伽梵离开大路而去坐于一树下，告尊者阿难说：「阿难，你将我衣叠为四摺并敷设之。我疲乏已甚，宜稍休息。」「是，世尊。」尊者阿难回答说。他遂将衣叠为四摺。

22 薄伽梵坐于敷座后语尊者阿难说：「阿难，请取水与我，我甚渴，欲饮水。」于彼作如是语后，尊者阿难白佛言：「世尊，今有五百牛车渡河，车轮扰水，流水既浅又混浊。不远即是卡枯塔河，其水清凉净洁，入水甚易，令人欣悦。佛陀既可饮水，又能凉身。」

23 第二次薄伽梵语尊者阿难说：「阿难，请取水与我，我甚渴，欲饮水。」第二次尊者阿难白佛言：「世尊，今有五百牛车渡河，车轮扰水，流水既浅又混浊。不远即是卡枯塔河，其水清凉净洁，入水甚易，令人欣悦，佛陀既可饮水，又能凉身。」

24 第三次薄伽梵语尊者阿难说：「阿难，请取水与我，我甚渴，欲饮水。」「是，世尊。」尊者阿难回答说。彼即持钵诣该小河。尔时该小河刚被车轮扰水，流水既浅又混浊。但恰好在尊者阿难抵达时，河水立即变为澄清净洁。

25 尔时尊者阿难自念：「诚然，如来的大威神力是奇妙不可思议。此小河刚被车轮扰水，流水既浅又混浊；当我到来时，河水立即变为澄清净洁。」彼遂用钵取水，回到佛陀的住处，白佛言：「世尊，如来的大威神力是奇妙不可思议。因该小河刚被车轮扰水，流水既浅又混浊；当我到达时，河水立即变为澄清净洁。世尊，请饮水！慈尊，请饮水！」薄伽梵遂饮水。

26 尔时有一马拉少年系阿拉罗．卡拉马的弟子名蒲枯沙者，旅行于从拘尸那罗赴波婆的道上。马拉少年蒲枯沙见佛陀坐于树下，即走到佛前向佛作礼，就座其侧以后，白佛言：「世尊，彼诸出家者度时于如是和平心境，此事实为不可思议！」

27 「世尊，往昔阿拉罗．卡拉马是沿路步行，后来在热气正盛之际，他坐于路侧树下休息。世尊，尔时有五百牛车逼近阿拉罗．卡拉马络绎驶过。时有一人尾随诸车辆之后，走向阿拉罗．卡拉马住处。到已，他向阿拉罗．卡拉马说：『师尊，你曾见五百牛车驶过？』『不，我不曾看见。』『师尊，你曾闻其声音？』『不，我不曾闻其声音。』『师尊，你是否入睡？』『不，我不曾入睡。』『师尊，你是否有知觉？』『是，我有知觉。』『师尊，你是清醒而有知觉，对那逼近你络绎驶过的五百牛车，既不见，又不曾闻其声音，甚至灰尘飘坠在你的衣服上？』『正是如此。』「尔时其人如是思维：『彼诸出家者度时于如是和平心境，此事实为奇妙不可思议。虽然说他是清醒而有知觉，但对那逼近他络绎驶过的五百牛车，既不见，又不曾闻其声音，甚至灰尘飘坠在他的衣服上。』于其表示对阿拉罗．卡拉马有甚深信仰以后，即告辞而去。」

28 「蒲枯沙，汝意云何？此两事中谁为较难举行与应付？是那清醒而有知觉，对那逼近他络绎驶过的五百牛车，既不见，也不闻其声音的人，抑是那清醒而有知觉，既不闻骤雨的飘洒，雷霆的震吼，也不见电光的闪灼的人？」

29 「若作一比较，此五百牛车，或六百、七百、八百、九百、一千，甚至百千万牛车能算什么！当一人既清醒而有知觉，既不闻骤雨的飘洒，雷霆的震吼，也不见电光的闪灼，实是较困难而不易举行与应付。」

30 「蒲枯沙，往昔我住于阿吐马打谷场。当时骤雨的飘洒，雷霆的震吼，和电光的闪灼，打谷场有农夫兄弟二人和四头牛被击毙。蒲枯沙，尔时有一人群从阿吐马赴该农夫兄弟和四头牛被击毙之处。」

31 「蒲枯沙，尔时我离开打谷场，只在打谷场门首空地上往来经行及思维。时有一人从该人群中向我走来并行礼。他侍立一面后，我告其人说：『朋友，为何群众集会？』

32 『世尊，适才有骤雨的飘洒、雷霆的震吼，和电光的闪灼，有农夫兄弟二人和四头牛被击毙。因此，群众聚集。但世尊，您是在何处？』『我一向在此。』『世尊，您曾见此事？』『我不曾看见。』『世尊，您曾闻其声音？』『我不曾闻其声音。』『世尊，您是否入睡？』『我不曾入睡。』『世尊，您是否有知觉？』『是，我有知觉。』『世尊　※，您是清醒而有知觉，对骤雨的飘洒、雷霆的震吼，和电光的闪灼，是既不见，又不闻其声音？』『正是如此』

33 「蒲枯沙，尔时其人如是思维：『彼诸出家者度时于如是和平心境，此事实为奇妙不可思议。虽然说他是清醒而有知觉，但对那骤雨的飘洒、雷霆的震吼，和电光的闪灼，他是既不见，又不曾闻其声音。于其表示对我有甚深信仰以后，他即向我顶礼，告辞而去。」

34 于彼作如是语后，马拉少年蒲枯沙白佛言：「世尊，现今我对阿拉罗．卡拉马的信仰如迅风扬尘，如河中急湍的冲洗。世尊之言最为佳善！此正如倾者扶之，晦者显之。迷途者示以道路，住黑暗者示以明灯，因而有眼者能视外物。佛陀用种种方便对我宣说真理亦复如是。世尊，我今以佛法僧为依归，请薄伽梵接受我为优婆塞，从今日起至于命终。」

35 于是蒲枯沙语其从人说：「朋友，请携取两件制就的金缕衣来。」「是，先生。」其人回答说。彼即携来两件制就的金缕衣。蒲枯沙将该两件金缕衣奉献与佛说：「世尊，伏维垂愍，请接受此两件制就的金缕衣！」「既如此，你给我穿上一件，另一件则给阿难穿上。」「是，世尊。」蒲枯沙回答说。他即给佛陀披上一件，另一件则给阿难披上。

36 薄伽梵遂向马拉少年蒲枯沙宣示法要，使之发心喜悦。当其对佛陀所示法要表示发心喜悦后即从座起，向佛作礼，右□而去。

37 尔时尊者阿难于马拉少年蒲枯沙去后不久，即将该两件制就的金缕衣披上佛身。当佛披上后该衣即失去光彩。尔时尊者阿难白佛言：「世尊，如来的肤色是如此明皙！此诚奇妙不可思议！当两件制就的金缕衣披上佛身后，该衣即失去光彩。」「阿难，诚然，如来的肤色有两次是异常明皙。何为两次？一次为如来证无上正等觉之夜，另一次则为如来证无余涅槃界之夜。阿难，此两次如来的肤色是异常明皙。」

38 「阿难，今夜三更时分，在拘尸那罗之鸟帕瓦塔那，马拉之娑罗树林，娑罗双树间，如来将取涅槃。来，阿难，我等去卡古塔河。」「是，世尊。」尊者阿难回答说。两件制就之金缕衣，为蒲枯沙所携来；慈尊披上后，放光如金色。

39 尔时薄伽梵与大比丘僧众走向卡古塔河。到已，他入河洗浴和饮水。既达彼岸，他走向□果林并语尊者穷达卡说：「穷达卡，请将衣叠为四摺，我甚倦，欲躺下。」「是，世尊。」尊者穷达卡回答说。彼遂将衣叠为四摺。

40 尔时薄伽梵偃卧右侧，将双足叠并。彼静寂入定，存念将再起来。尊者穷达卡即坐于佛前。

41 佛陀既到卡古塔河，其水清鲜澄静地流□。彼投身入河流，疲倦已甚，如来是世间无比。洗浴及饮水后，导师达于彼岸，比丘众追随其后。时薄伽梵宣转大法，圣尊遂抵达□果林。彼语穷达卡比丘说：「将衣叠为四摺，我欲卧。」穷达卡为圣尊所敦促，遂迅速叠衣四摺于地上；慈尊偃卧甚为疲乏，穷达卡亦坐于其前。

42 尔时薄伽梵告尊者阿难说：「阿难，若有人向铁匠穷达引起悔憾说：『穷达，此是对你不吉及遭受损失。当如来用过彼之最后一餐饭遂入涅槃。』阿难，此种悔憾于铁匠穷达应如此纠正说：『穷达，此对你甚善及有利益。当如来用过彼之最后一餐饭遂入涅槃。穷达，我从佛亲口闻受：此两次的斋供有同样果报、同样利益，比其他大果报、大利益为更大。云何为两次？一次是当如来进餐后成无上正等正觉，另一次是当彼进餐后入无余涅槃界而取涅槃。这两次斋供有同样果报、同样利益，比其他大果报、大利益为更大。铁匠穷达已种下了得长寿、得端正相貌、得幸福、得美誉、得生天、得为君胄的善业。』「阿难，若有此种悔憾于铁匠穷达应如此纠正之。」

43 尔时薄伽梵念及此事，以偈颂曰：布施者其福德增长，自制者忿怒不能起，行善者捐弃一切恶。灭尽贪镇痴，彼得证涅槃。
* 第五章


01 尔时薄伽梵告尊者阿难说：「来，阿难，我等去醯连尼耶瓦提河之彼岸，拘尸那罗的乌帕瓦塔那，马拉之娑罗树林。」「是，世尊。」尊者阿难回答说。于是佛与大比丘僧众向醯连尼耶瓦提河之彼岸，拘尸那罗的乌帕瓦塔那，马拉之娑罗树林进行。到已，语尊者阿难说：「阿难，请为我敷设床具于娑罗双树间，其头北向，我倦甚，欲偃卧。」「是，世尊。」尊者阿难回答说，即于娑罗树间敷陈床具，其头北向。时世尊心境安稳，偃卧右侧，将其双足叠并，作狮子睡。

02 尔时娑罗双树忽于非时鲜花开发，缤纷散落在如来身上以供养如来。天上的曼陀罗华亦从天下降，缤纷散落在如来身上以供养如来。天上的旃陀罗香屑亦从天下降缤纷散落在如来身上以供养如来。天上的音乐亦从天演奏以供养如来。天上的歌唱亦从天发出以供养如来。

03 于是世尊告尊者阿难说：「阿难，娑罗双树忽于非时鲜花开发，缤纷散落在如来身上以供养如来。天上的曼陀罗华亦从天下降缤纷散落在如来身上以供养如来。天上的旃陀罗香屑亦从天下降缤纷散落在如来身上以供养如来。天上的音乐亦从天演奏以供养如来。天上的歌唱亦从天发出以供养如来。「阿难，并非如此是对如来有适宜的恭敬供养。若比丘、比丘尼、优婆塞、优婆夷继续担负大小责任，持身端正，依止戒律－－如是，其人是对如来有适宜的恭敬供养和最有价值的敬礼。是以阿难，汝应继续负担大小责任，持身端正，依止戒律。阿难，应如此教化。」

04 尔时尊者乌帕宛那立于佛前以扇扇佛。世尊对他不悦并告之曰：「汝退出，比丘，不用立在我面前。」尊者阿难自念：「此尊者乌帕宛那亲身奉侍如来已为时很久。现在于临终之际，世尊对之不悦并告之曰：『汝退出，比丘，不用立在我面前。』究竟是何因缘，世尊对他不悦而发出此语？」

05 尔时尊者阿难白佛言：「世尊，此尊者鸟帕宛那亲身奉侍如来为时已久。现在于临终之际对他不悦并向他说：『汝退出，比丘，不用立在我面前。』究竟是何因缘，世尊对他不悦而发出此语？」「阿难，十方世界无数天神云集来瞻仰如来。环□拘尸那罗的乌帕瓦塔那，马拉之娑罗双树林十二由旬的附近，无一容发尖之缝隙没有被具大威神的天神所占据。阿难，此诸天神埋怨说：『我等自远道来瞻视如来，正等正觉阿罗汉如来之出世是甚为希有。在今晚更末如来将取涅槃，而这位有名的比丘立于其前遮蔽之，我等不得于临终之际瞻仰如来！』阿难，诸天神如此埋怨说。」

06 「但世尊认彼等为何等样的天神？」「阿难，在天上的神祗还有尘世意念，彼等或披发而哭，或挺臂而哭，或自投地宛转而哭，当一念及：『薄伽梵取涅槃何如是其迅速，慈尊取涅槃何如是其迅速！世界之光熄灭何如是其迅速！』「阿难，在地上的神祗还有尘世意念，彼等或披发而哭，或挺臂而哭，或自投地宛转而哭，当一念及：『薄伽梵取涅槃何如是其迅速，慈尊取涅槃何如是其迅速！世界之光熄灭何如是其迅速！』「但诸离欲的神祗泰然自摄忍受之，并忆念及：『缘会诸法实是无常，若不如此，实不可能。』

07 「世尊，往昔诸比丘于各地坐夏后皆来觐见如来。我等接待诸长老，使晤见及侍候如来。但于如来去世后，我等不能接待诸长老使晤见及侍候如来。」

08 「阿难，有四处，具信仰之族姓王子应朝礼致敬，何者为四？「(1)阿难，信仰者于一处能说：『此是如来降生处』，则为应朝礼及致敬之处。」「(2)阿难，信仰者于一处能说：『此是如来证无上正等正觉处』，则为应朝礼及致敬之处。」「(3)阿难，信仰者于一处能说：『此是如来转*轮处』，则为应朝礼及致敬之处。」「(4)阿难，信仰者于一处能说：『此是如来入无余涅槃界处』，则为应朝礼及致敬之处。」「阿难，此为四处，具信仰之族姓子应朝礼致敬。阿难，信仰者－－比丘、比丘尼、优婆塞、优婆夷等将赴上列各处并说：『此是如来降生处』、或『此是如来证无上正等觉处』、或『此是如来转*轮处』、或『此是如来入无余涅槃界处』。「阿难，当彼等朝礼诸圣地，其有信心而死去时，彼等于身坏命终将上生快乐的天界。」

09 「世尊，我们对于妇女将何以自处？」「阿难，不要看她们。」「若见了她们，我们将何以自处？」「阿难，不要交谈。」「世尊，若她们向我们攀谈又将如何？」「阿难，当自警惕！」

10 「世尊，我们对于如来的遗体将如何处理？」「阿难，你们向如来的遗体致敬不必顾虑，我请求你们当自勉、当专重于自善、当自精勤不懈及注法于自善。在刹帝利、婆罗门、居士中有智者，他们对如来有坚固信仰；他们将对如来的遗体致敬。」

11 「世尊，对于如来的遗体当如何处理？」「阿难，如人处理转轮圣王的遗体，对如来的遗体亦应如此。」「世尊，如何处理转轮圣王的遗体？」「他们以新布包裹转轮圣王的遗体，继以亲净棉，再以新细布，如是一层布、一层棉，至各有五百层为止。然后将其安放在有油之金(1)棺内，复以另一金棺盖之，用诸种香□作火葬场以焚烧转轮圣王的遗体；于十字街头为之建塔。此为人们处理转轮圣王的遗体之法。「阿难，人们如此处理转轮圣王的遗体，对如来的遗体亦应如此；也应在十字街头为如来建塔。若有人对之奉献花香、图绘或礼拜，其人将获永久福利及快乐。」^2□1巴利文AYASAYA原意为「铁」，或「铜」，佛音谓此地应作「金」。

12 「阿难，有四种人应值得为之造塔，何者为四？「(1)正等正觉如来应值得造塔。(2)辟支佛应值得造塔。(3)如来的声闻弟子应值得造塔。(4)转轮圣王应值得造塔。「阿难，云何正等正觉如来应值得造塔？若人念及：『此为正等正觉如来的塔』之时，那将使很多人内心平静及愉快。他们既得内心平静快慰，于身坏命终之后能转生快乐的天界。阿难，此为正等正觉如来应值得造塔的理由。「阿难，云何辟支佛应值得造塔？若人念及：『此为辟支佛的塔』之时，那将使很多人内心平静及愉快。他们既得内心平静快慰，于身坏命终之后能转生快乐的天界。阿难，此为辟支佛应值得造塔的理由。「阿难，云何如来之声闻弟子应值得造塔？若人念及：『此为如来声闻弟子的塔』之时，那将使很多的人内心平静及愉快。他们既得内心平静快慰，于身坏命终之后能转生快乐的天界。阿难，此为如来的声闻弟子应值得造塔的理由。「阿难，云何转轮圣王应值得造塔？若人念及：『此为公平正值转轮王的塔』之时，那将使很多人内心平静及愉快。他们既得内心平静快慰，于身坏命终之后能转生快乐的天界。阿难，此为转轮圣王应值得造塔的理由。「阿难，此为四种人应值得为之造塔。」

13 尔时尊者阿难走入精舍，立于门楣，哭泣自念：『现在我还是一个声闻，未获道果，而慈愍的导师即将入涅槃！」尔时薄伽梵告诸比丘说：「诸比丘，阿难在Α魾？」「世尊，尊者阿难走入精舍，立于门楣，哭泣自念：『现在我还是一个声闻，未获道果，而慈愍的导师即将入涅槃！』于是薄伽梵语某一比丘说：「比丘，你称我名告阿难说：『阿难师兄，导师唤你。』」「是，世尊。」该比丘回答说，遂走向尊者阿难所在处。到已，他告尊者阿难说：「阿难师兄，导师唤你。」「是，师弟。」尊者阿难回答说，遂走向佛陀所在处。到已，向佛作礼，退坐一面。

14 当尊者阿难就座后，薄伽梵向他说：「止止，阿难，不要自苦，也不要哭！是否我于往昔曾告诉你万物实性如此，其与我们最亲近者将要与我们分别隔离？当一物既生而成形，即具分离的必然性，不要其解离，此何可能？且必无此理。阿难，很久以来，以你的慈而善的爱行、爱语、爱念亲近于我，永不更变及莫可计算，甚堪嘉奖。阿难，当自精勤，不久你也将获得漏竟。」

15 尔时薄伽梵告诸比丘说：「诸比丘，于过去世正等正觉阿罗汉诸佛有忠诚的侍者为诸如来服务，正如阿难之对于我。而未来世若有人作正等正觉阿罗汉诸佛，亦有忠诚的侍者为诸如来服务，也正如阿难之对于我。「诸比丘，阿难为一智者，他知何时为比丘、比丘尼、优婆塞、优婆夷、国王、大臣、外道及其信徒等去觐见如来是最为适宜。

16 「诸比丘，阿难有四种希有特质。何者为四？」诸比丘，若有(1)比丘众往访阿难，谒见后他们充满欣悦，彼遂向之开示法要。他们对其所说充满欣喜；当阿难默然不语，则诸比丘殊觉不安。「诸比丘，若有(2)比丘尼、(3)优婆塞、(4)优婆夷往访阿难，谒见后他们充满欣悦，彼遂向之开示法要。他们对其所说也充满欣喜；当阿难默然不语，则诸比丘尼等殊觉不安。「诸比丘，转轮圣王有四种希有特质。何者为四？「诸比丘，若(1)刹帝利、(2)婆罗门、(3)居士、(4)沙门等众往谒转轮圣王，觐见后他们充满欣悦，彼遂向之开示法要。他们对其所说充满欣喜；当转轮圣王默然不语，则他们殊觉不安。「诸比丘，正如此，阿难有此四种希有特质。若比丘、比丘尼、优婆塞、优婆夷众往访阿难，谒见后他们充满欣悦，彼遂向之开示法要。他们对其所说充满欣喜；当阿难默然不语，则彼等殊觉不安。「诸比丘，此为阿难的四种希有特质。」

17 当其作如是语已，尊者阿难白佛言：「世尊，请不要在此鄙陋小城，荒毁之地，证取涅槃。因为更有大城如：瞻波、王舍、舍卫、萨克陀、柯善必、波罗奈等，请薄伽梵于其中之一证取涅槃，彼处多诸富有的刹帝利、婆罗门、长者居士－－信佛弟子。他们对如来的遗体将致敬仰。」

18 「止止，阿难，不应作如是语：此是一鄙陋小城，荒毁之地。阿难，往昔有一王名大善见。他是一正直之人，以正直御世，拥有七宝，征服全球，为四天下之主，并为人民保护者。此大善见王之首都名拘舍婆提，即在此拘尸那罗城。其城东西长十二由旬，南北宽七由旬。「阿难，此拘舍婆提首都甚为广阔繁荣，人民汇集，充满各种食品，正如诸天之首都阿拉卡曼达，广阔繁荣，民众及诸天神荟集，各种食品充满。阿难，拘舍婆提首都亦复如是。「阿难，此拘舍婆提首都日夜发出十种声音，如：象声、马声、车声、鼓声、手鼓声、琵琶声、歌声、钵铙钵声、锣声及「吃、喝、嬉笑声」。

19 「阿难，你去拘尸那罗通知该地的马拉说：『瓦舍塔们，今晚更末如来将取涅槃，你们请自便，不要后来自责说：『如来在我们的乡村圆寂，而我们失去最后觐见的机会。』「是，世尊，」尊者阿难回答说。他遂著衣持钵，有另一比丘作伴，走向拘尸那罗。

20 尔时拘尸那罗的马拉正集于会厅商议公事。尊者阿难走向该会厅。到已，他告诉马拉说：『瓦舍塔们，今晚更末如来将取涅槃。你们请自便！不要后来自责说：『如来在我们的乡村圆寂，而我们失去最后觐见的机会。』

21 闻尊者阿难如是语已，马拉们与其少年、少女及妻子皆悲哀惨凄，中心忧伤，当一念及：「薄伽梵取涅槃何如是其迅速！慈尊取涅槃何如是其迅速！世界之光熄灭何如是其迅速！」他们或披头散发而哭，或伸臂而哭，或自投地宛转而哭。尔时马拉们与其少年、少女及妻子皆悲哀惨凄，中心忧伤走向乌帕瓦塔那、马拉的娑罗树林尊者阿难的所在处。

22 尔时尊者阿难如是思维：「若我许拘尸那罗的马拉们一一向佛作礼，恐全部礼佛未毕即将天明。今且令彼等分队站立，每家为一队向世尊引见说：『世尊，今有某某马拉与其妻子，侍从，亲友等顶礼佛足。』」尊者阿难遂将拘尸那罗的马拉们每家组成一队向薄伽梵敬礼说：「世尊，今有某某马拉与其妻子侍从亲友等顶礼佛足。」采用如此方法，尊者阿难于一更时分已令拘尸那罗的全部马拉进前礼佛。

23 尔时有一游行者苏跋陀抵达拘尸那罗。彼听说：「今晚三更时分沙门乔达摩将入无余涅槃。」于是游行者苏跋陀如是思维：「我曾从诸长老、师父与弟子游行者处闻来：『正等正觉阿罗汉如来之出世是甚为希罕。』但在今夜三更时分沙门乔达摩即将入涅槃。今我心有疑。然我对沙门乔达摩有信心；我想他能揭示真理，用释我之疑惑。」

24 于是游行者苏跋陀走向乌帕瓦塔那．马拉的娑罗树林，尊者阿难的所在处。到已，他向尊者阿难说：「尊者阿难，我曾从诸耆宿长老、师父与弟子游行者处闻来：『正等正觉阿罗汉如来之出世是甚为希罕。』但在今夜三更时分沙门乔达摩即将入涅槃。今我心有疑。然我对乔达摩有信心；我想他能揭示真理，用释我之疑惑。尊者阿难，或者我也被许可去见沙门乔达摩？」「止止，朋友苏跋陀，请不用劳扰如来，他很倦乏。」第二第三次游行者苏跋陀向尊者阿难说：(其详见上)

25 当薄伽梵听到尊者阿难与游行者苏跋陀的谈话，彼告尊者阿难说：「止止，阿难，不用阻拦苏跋陀，且听他瞻仰如来。随彼所问，是因求知而问，非为劳扰；而随我所答，彼将迅速了解。」于是尊者阿难向游行者苏跋陀说：「请进，朋友苏跋陀，如来已给了许可。」

26 游行者苏跋陀遂走向佛前致敬，与之互相问讯后，即就座其侧，白佛言：「乔达摩，彼诸宗教领袖，门徒之首领，教派之创建者，远近知名，群众钦仰其为贤者如：(一)富兰迦叶，(二)末伽梨□舍梨，(三)阿浮多，翅舍钦婆罗，(四)波浮迦旃延，(五)萨若□耶梨弗，(六)尼犍子等，依照其自称，是否他们已彻底了解诸法？或有了解，或有不了解者？」「止止，苏跋陀，且放下：『依照其自称，是否他们已彻底了解诸法？或有了解，或有不了解者』，我将向你说法，且专心谛听！」「是，世尊」，游行者苏跋陀回答说。

27 于是薄伽梵说：「苏跋陀，若于任何法中无八圣道者，则无第一、第二、第三及第四沙门果。若于任何法戒中有八圣道者，则有第一、第二、第三及第四沙门果。今我法戒中有八圣道，苏跋陀，亦有第一、第二、第三及第四沙门果。外道诸师之法皆空幻，无沙门果，苏跋陀，若比丘能行正道，则世间不会缺少阿罗汉。『苏跋陀，我年二十九，出家求善道。自出离已来，已逾五一年。道法广阔界，常游巡仰企；于其领域外，实无沙门果。不但无第一沙门果，且无第二、第三及第四沙门果。外道诸师之法皆空幻、无沙门果。苏跋陀，若比丘能行正道，则世间不会缺少阿罗汉。」

28 当其如是语已，游行者苏跋陀白佛言：「世尊，你之法语优妙绝伦，正如倾者扶之，晦者显之，迷途者示以正道，住黑暗者示以明灯，因而有眼者能视外物。薄伽梵以众多譬喻为我开示真理亦复如是。因此，世尊，我皈依佛法僧，甚愿能许我在佛前出家及受具足戒。」

29 「苏跋陀，若人先为外道门徒，欲来此法戒中出家或受具足戒，他应有四月试习；四月期满，诸比丘喜悦听其出家或受具足戒。但我宣布此事是因人而异。」「世尊，若人先为外道门徒欲来此戒法中出家或受具足戒，此人应试习四月；四月期满，诸比丘喜悦，听其出家，或受具足戒。现我愿试习四月，四月之后，诸比丘喜悦听我出家或受具足戒。」尔时薄伽梵告尊者阿难说：「阿难，听许苏跋陀出家。」「是，世尊，」尊者阿难回答说。

30 尔时游行者苏跋陀向尊者阿难说：「阿难，你亲从导师沾润而为此僧团之弟子，你获大饶益，你得大福利。」是时游行者苏跋陀于薄伽梵之僧团出家并受具足戒，尊者苏跋陀于受具足戒之后即坚定精勤，离群独居。不久即证得最高梵行境界。为此之故，族姓子舍弃各种家庭利益与舒适而出家。诚然，于现世以自力证取最高目标。他自知生死已断，梵行已立，所作已作，今生后不再有来生。尊者苏跋陀成了阿罗汉之一，他为薄伽梵所化的最后弟子。


* 第六章

01 尔时薄伽梵告尊者阿难说：「阿难，汝等中若有人作如是思维：『导师的教言已毕，我们无复有导师。』实非如此，不应作如是观。阿难，我为汝等所建立的法与戒，于我去世后应为汝等的导师。」

02 「阿难，「朋友」一词为现时诸比丘互相沿用的称呼，于我去世后不应再用。阿难，年长的比丘应呼年幼比丘的名或姓，或称「朋友」；但年幼者应称年长者为「大德」或「尊者」。

03 「阿难，于我去世后，若僧团同意可以舍微小戒。」

04 「阿难，于我去世后应向疆那比丘施行梵罚。」「但，世尊，何名梵罚？」「阿难，听任疆那比丘随意说话，诸比丘不应与之交谈，不劝告他，亦不教训他。」

05 尔时薄伽梵告诸比丘说：「诸比丘，若比丘心中于佛法僧正道等有所惑疑，即当谘询，不应后业自责说：『当面对导师时，我等未能亲向如来谘询！』」他如是语已，诸比丘皆默然。第二及第三次薄伽梵告诸比丘说：「诸比丘，若比丘心中于佛法僧正道等有所惑疑，即当谘询，不应后来自责说：『当面对导师时，我等未能亲向如来谘询！』」至于第三次诸比丘仍皆默然。于是薄伽梵告诸比丘说：「诸比丘，若你们是为了尊师，故不发问，可令其友人互相转达。」他如是语已，诸比丘仍皆默然。

06 尔时尊者阿难白佛言：「世尊，此诚奇妙不可思议！我深信此大众中没有一比丘于佛法僧正道等有所惑疑。」「阿难，你之所说是出自净信。但如来也确知此事：在此大众中没有一比丘于佛法僧正道等有所惑疑。阿难，于此五百比丘中连最落后者亦取得预流果，将不堕恶趣，亦决定证取正觉。」

07 尔时薄伽梵语诸比丘说：「诸比丘，现在我劝告汝等：诸因缘法含固有毁坏。大家应自精勤，证取道果！」此为如来的最后遗教。

08 于是薄伽梵即入初禅，从初禅起入第二禅，从第二禅起入第三禅，从第三禅起入第四禅，从第四禅起入空处定，从空处定起入识处定，从识处定起入无所有处定，从无所有处定起入非想非非想定。尔时尊者阿难语尊者阿□楼驮说：「大德阿□楼驮，薄伽梵已入圆寂！」「朋友阿难，如来尚未圆寂，他是入于灭想定。」

09 于是薄伽梵从灭想定起入非想非非想处定，从非想非非想处定起入无所有处定，从无所有处定起入识处定，从识处定起入第四禅，从第四禅起入第三禅，从第三禅起入第二禅，从第二禅起入初禅，从初禅起入第二禅，从第二禅起入第三禅，从第三禅起入第四禅，从第四禅起如来立即入于涅槃。

当佛陀逝世时有大地震甚可惊怖，并有天雷响震。于佛陀灭度时梵天沙航拔谛以偈颂曰：世间诸有情皆当舍诸蕴；导师亦若此世间无比伦。昔贤承继者，智慧知见深，而今竟涅槃。于佛陀涅槃时帝释因陀罗以偈颂曰：诸行无常，是生灭法；生而复灭，寂灭为乐。于佛陀涅槃时尊者阿□楼陀以偈颂曰：已舍诸贪欲，得证净涅槃。大贤损寿时，心安隐坚定。心定不可摇，战胜死痛苦。正如明灯灭，心解脱亦然。于佛陀圆寂时尊者阿难以偈颂曰：有大恐怖，毛发为竖。诸事圆成，佛取灭度。于佛陀涅槃时彼诸未离欲比丘或伸臂而哭，或自投地宛转悲泣说：「薄伽梵取涅槃何如是其迅速！慈尊取涅槃何如是其迅速！世界之光熄灭何如是其迅速！」但彼诸离欲比丘念及：「诸因缘法皆无常，不要其解离，此何可能！」遂摄抑其心以忍受悲戚。

11 尔时尊者阿□楼陀语诸比丘说：「止止，诸友，不用哭泣悲恸，是否往昔薄伽梵曾告诉我们：万物实性如此，其与我们最亲近者将要与我们分别隔离。当一物既生而成形即具分离必然性。不要其解离，此何可能，且必无此理。诸比丘，天神将责怪我等。」「但大德阿□楼陀，此诸天神属何种类？」「朋友阿难，天上诸神还有世念，他们或披发而哭，或伸臂而哭，或自投地宛转悲泣说：薄伽梵取涅槃何如是其迅速！慈尊取涅槃何如是迅速！世界之光熄灭何如是其迅速！「朋友阿难，地上诸神还有世念，他们或披发而哭，或伸臂而哭，或自投地宛转悲泣说：薄伽梵取涅槃何如是其迅速，慈尊取涅槃何如是其迅速！世界之光熄灭何如是其迅速！「但彼诸离欲天神念及：『诸因缘法皆无常，不要其解离，此何可能』，遂自摄心忍受之。」

12 尔时尊者阿□楼陀与尊者阿难议论佛法以度残夜。其后尊者阿□楼陀语尊者阿难说：「朋友阿难，你去拘尸那罗通知该地的马拉说：『瓦舍塔们，薄伽梵已入涅槃。请行所应行！』」「是，大德。」尊者阿难回答说，即于清晨著衣持钵，有另一比丘作伴，走向拘尸那罗。尔时拘尸那罗的马拉正为该事集于议事厅，尊者阿难走向该处语诸马拉说：「瓦舍塔们，薄伽梵已入涅槃，请行所应行！」闻尊者阿难语已，马拉们与其少年、少女及妻子皆悲哀惨凄，中心忧伤。他们或披发而哭，或伸臂而哭，或自投地宛转悲泣说：「薄伽梵取涅槃何如是其迅速！慈尊取涅槃何如是其迅速！世界之光熄灭何如是其迅速！」

13 尔时拘尸那罗的马拉命其侍从说：「聚集拘尸那罗所有的香、花环及音乐。」于是拘尸那罗的马拉们携带香、花环，各种音乐及五百套衣著走向乌帕瓦塔那、娑罗树林佛陀的遗体所在处。他们以歌舞，音乐，花环，名香等向如来的遗体致敬，并以其衣著作成天幕及编扎花环悬挂其上，如此他们遂度过第一天。尔时拘尸那罗的马拉如是思维：「今日已太晚，且于明天举行焚葬佛之遗体。」于是拘尸那罗的马拉们以歌舞，音乐，花环、名香等向如来的遗体致敬，并以其衣著作成天幕，及编扎花环悬挂其上。如此他们遂度过第二天，第三天，第四天，第五天及第六天。

14 于第七日拘尸那罗的马拉们如是思维：「让吾人举持如来遗体南向外出至城外之南边地点，以歌舞、音乐、花环、名香等向如来的遗体致敬已，遂于城南举行火葬典体。」尔时有八名领袖洗头著新衣并如是思维：「我们将举持如来的遗体。」但他们不能举起。于是拘尸那罗的马拉们语尊者阿□楼陀说：「此八名马拉领袖洗头著新衣并如是思维：『我们将举持如来的遗体。』但他们不能举起，是何因缘？」「瓦舍塔们，因为你们有一意向，但诸天神又有另一意向。」

15 「大德，云何为天神的意向？」「瓦舍塔们，你们的意向是：『让吾人擎持如来遗体靠南方外出至城外之南边地点，以歌舞、音乐、花环、名香等向如来的遗体致敬已，遂于城南举行火葬典礼。』但天神的意向是如此：『让我们擎持如来的遗体靠北方至城北进北门，经城之中区达其中央，从东门出，我们以歌舞、音乐、花环、名香等向如来的遗体致敬。其后移至位于城东马拉们之「系宝冠寺」遂举行火葬典礼。』」「大德，诸天神的意向既如此，且听从之。」

16 尔时天上曼陀罗花散布拘尸那罗全境，连废物堆，垃圾箱也在内其－－深过膝。于是天神及拘尸那罗的马拉们以天上和人间的歌舞、音乐、花环、名香等向如来的遗体致敬。他们擎持佛之遗体靠北方至城北，进北门，经过城之中区达其中央，从东门出，遂移至位于城东马拉们之「系宝冠寺」停放之。

17 尔时拘尸那罗的马拉们语尊者阿难说：「尊者阿难，我们对如来的遗体当如何处理？」「瓦舍塔们，如人处理转轮圣王的遗体，对如来的遗体也应如此。」「大德阿难，如何是处理转轮圣王的遗体？」「瓦舍塔们，他们以新布包裹转轮圣王的遗体，继以新净棉，再以新细布缠之。如是一层布，一层棉，至各有五百层为止，然后将其安放在有油之金棺内。复以另一金棺盖之；用诸种香□作火葬场以焚烧转轮圣王的遗体。于十字街头为之建塔。此为人们处理转轮圣王的遗体之法。「瓦舍塔们，人们如此处理转轮圣王的遗体，对如来的遗体也应如此，也应在十字街头为如来建塔。若有人对之奉献花香、图绘、或礼拜肃敬，其人将获永久福利及快乐。」

18 尔时拘尸那罗的马拉们命其侍从说：「聚集马拉们所有的新净棉。」于是拘尸那罗的马拉们以新布包裹如来的遗体，继以新净棉，再以新细布缠之。如是，一层布，一层棉，至各有五百层为止。然后将其安放在有油之金棺内，复以另一金棺盖之；用诸种香□作火葬场，遂将如来的遗体置于其上。

19 尔时尊者大迦叶与大比丘僧众五百人从波婆向拘尸那罗，正在途中旅行。其后尊者大迦叶离开公路就座一树脚下。尔时有一露体外道，手持在拘尸那罗所拾得之曼陀罗花正向赴波婆之公路走来。尊者大迦叶遥见该外道向彼走来。既相见已，语该外道说：「朋友，你应知我们的导师？」「诚然，朋友，我知之，沙门乔达摩涅槃以来已经七日。以是因缘，我获得此曼陀罗花。」(闻是语已)彼诸未离欲比丘当一念及：薄伽梵取涅槃何如是其迅速！慈尊取涅槃何如是其迅速！世界之光熄灭何如是其迅速！遂立即伸臂而哭，或自投地宛转悲泣。但彼诸离欲比丘念及：诸因缘法皆无常，不要其解离，此何可能！遂摄抑其心以忍受悲戚。

20 尔时有一年老出家比丘名苏跋陀在大众中坐。彼语诸比丘说：「止止诸师。不应哭，也不应悲恸！我们从该大沙门获得解脱！他常以『当应行是，不应行是』来烦扰我等。今后我们为所欲为。其不欲者则不为之！」但尊者大迦叶语诸比丘说：「止止，诸比丘，不应哭，也不应悲恸，是否往昔如来曾向我们说：万物实性如此，其与我们最亲近者将要与我们分别隔离？当一物既生而成形，即具分离的必然性，不要其解离，此何可能？且必无此理！」

21 尔时有四名马拉领袖洗头著新衣如是思维：「我们去燃佛之火葬场。」但香□不著火。于是拘尸那罗的马拉们语尊者阿□楼陀说：「有四名马拉领袖洗头著新衣如是思维：『我们去燃佛之火葬场。』但香□不著火，是何因缘？」「瓦舍塔们，天神别有意向。」「但大德，云何为天神别有意向？」「瓦舍塔们，天神的意向是如此：『尊者大迦叶与大比丘僧众五百人从波婆向拘尸那罗，正在途中旅行。香□将不会著火，不直到尊者大迦叶能顶礼佛足。』「大德，天神的意向既如此，且听从之！」

22 尔时尊者大迦叶走向拘尸那罗马拉们的系宝冠寺－－佛□的所在处，到已，褊袒右肩，合掌恭敬□佛□三匝。其后，将佛足揭开，他向佛足顶礼。同时五百比丘亦褊袒右肩，合掌恭敬，□佛□三匝，向佛足顶礼。当尊者大迦叶与五百比丘顶礼既毕，佛□遂自动著火。

23 如来的遗体于火化后，其皮肤肉筋及骨节液汁既不见炱，亦不见灰，唯骨存在。正如酥油焚尽后，既不见炱，亦不见灰。因此，薄伽梵的遗体于火化后，其皮肤肉筋及骨节液汁，既不见炱，亦不见灰，唯骨存在，亦复如是，而五百张细布，其最初与最后尽皆燃化。薄伽梵的遗体既火化已，天降甘霖熄佛□火；地出涌泉熄佛□火；而拘尸那罗的马拉们以诸香水熄佛□火。尔时拘尸那罗的马拉们于其议事厅内以弓作壁垒来环□佛骨。七日中均以歌舞、音乐、花环、名香等致其恭敬供养。

24 尔时摩竭陀阿□世王－－韦提希之子闻悉薄伽梵已于拘尸那罗入涅槃。于是该王遣使向拘尸那罗的马拉说：「薄伽梵是刹帝利，我亦是刹帝利。我应获得舍利一份。我将为之起塔并兴供养。」□舍离的隶车闻悉薄伽梵已于拘尸那罗入涅槃。于是彼等遣使向拘尸那罗的马拉说：「薄伽梵是刹帝利，我们亦是刹帝利。我们应获得舍利一份。我们将为之起塔并兴供养。」迦□罗卫的释种闻悉薄伽梵已于拘尸那罗入涅槃。于是彼等遣使向拘尸那罗的马拉说：「薄伽梵是我族中之荣誉。我们应获得舍利一份。我们将为之起塔并兴供养。」阿拉喀巴的补里闻悉薄伽梵已于拘尸那罗入涅槃。于是彼等遣使向拘尸那罗的马拉说：「薄伽梵是刹帝利，我们亦是刹帝利。我们应获得舍利一份。我们将为之起塔并兴供养。」罗摩村的柯里闻悉薄伽梵已于拘尸那罗入涅槃。于是彼等遣使向拘尸那罗的马拉说：「薄伽梵是刹帝利，我们亦是刹帝利。我们应获得舍利一份。我们将为之起塔并兴供养。」韦塔低巴的婆罗门闻悉薄伽梵已于拘尸那罗入涅槃，于是彼等遣使向拘尸那罗的马拉说：「薄伽梵是刹帝利，我是婆罗门。我应获得舍利一份。我将为之起塔并兴供养。」波婆的马拉闻悉薄伽梵已于拘尸那罗入涅槃。于是彼等遣使向拘尸那罗的马拉说：「薄伽梵是刹帝利，我们亦是刹帝利。我们应获得舍利一份。我们将为之起塔并兴供养。」

25 闻如是语已，拘尸那罗的马拉向集会诸人说：「薄伽梵是在我们的村地入涅槃。我们将不以佛之舍利让给他人。」说是语时有婆罗门名东那向聚会大众说：诸君，请听我一言，容忍为我佛之教训。因分众中尊之舍利，而起战门，残害，殊为不应。我等应融洽和好将其分为八份。让佛塔远遍诸国，人类将依赖此世界之光。「既如此，婆罗门，你且平均分舍利为八份。」「诚然，诸君。」东那婆罗门回答在会的大众。平均分舍利为八份已，他语众人说：「愿诸君能以此□与我？我将为此□起塔并兴供养。」彼等将该□给与东那婆罗门。

26 □拍里瓦那的莫里闻悉薄伽梵已于拘尸那罗入涅槃。于是彼等遣使向拘尸那罗的马拉说：「薄伽梵是刹帝利，我们亦是刹帝利。我们应获得舍利一份。我们将为之起塔并兴供养。」「已再无舍利，佛之舍利已全被分尽。」当其闻如此回答，他们遂取其灰烬而归。

27 尔时摩竭陀阿□世王－－韦提希之子，于王舍城为舍利起塔并兴供养。□舍离的隶车于□舍离为舍利起塔并兴供养。迦□罗卫的释种于迦□罗卫为舍利起塔并兴供养。阿拉喀巴的补里于阿拉喀巴为舍利起塔并兴供养。罗摩村的柯里于罗摩村为舍利起塔并兴供养。韦塔低巴的婆罗门于韦塔低巴为舍利起塔并兴供养。波婆的马拉于波婆为舍利起塔并兴供养。拘尸那罗的马拉于拘尸那罗为舍利起塔并兴供养。□拍里瓦的莫里亦于□拍里瓦那为灰烬起塔并兴供养。如是，舍利塔有八；第九为□塔，第十为灰烬塔。往事如斯云。

[人中尊，远视眼之舍利有八份，七份于阎浮提被人礼敬，一份在罗摩村被龙王瞻仰一牙在天国受敬礼，另一则在犍陀罗城；□凌伽有其一，另一则被龙王顶礼。藉其光荣使大地增辉及供献源源而来。以如斯供品，大师之舍利受诸被敬者之最高礼敬，诸如天、龙、国王，以及人群中之最高尚者－－佛是万劫难遭遇，汝今合掌顶礼！]－－据佛音尊者的注释，此偈系后来在锡兰为人添入，非最初结集时所有。

南传大般涅槃经竟
