#+OPTIONS: toc:2 ^:false
#+SPEAKER: 于淩波居士著述

* 第一讲　佛教诞生的背景

** 一、印度-​-早期佛教活动的舞台

在现代具有世界性的三大宗教中，诞生自印度的佛教，是最古老的一个。

三个世界性的宗教，是佛教、基督教、回教。基督教是耶稣基督于西元一世纪初所创立的，它的历史迄今不足两千年。回教是穆罕默德于西元七世纪初所创立的，迄今历史约一千三百年；而佛教，是释迦牟尼佛陀于西元前五百多年的时候所创立的，迄今已有两千五百年以上的历史-​-正确的说，佛陀涅槃于西元前四八六年，他世寿八十岁，则出生于西元前五六五年。佛陀二十九岁出家，三十五岁成道，第二年就有了原始的僧伽-​-最早的僧团。也可以说，佛教于此时已经诞生了，所以佛教已有两千五百年以上的历史了。

这个有两千五百年历史的宗教，最初是如何诞生的-​-是在什么样的时空背景之下出现的呢？要探讨佛教诞生的背景，必须要自印度的地理、历史、宗教、文化了解起。要不然，我们无从了解佛教何以诞生，也无从了解佛教在印度许多教派中的地位。尤其是，我们无从了解佛教的教理，何以说常说断、说空说有。这就是我们要探讨佛教诞生背景的原因。于此，我们就先自印度的地理环境说起。

印度位于亚细亚南端的半岛，其国土初看像三角形，实际上则是不正四边形。自现代来看，印度面积有三百二十八万平方公里，但自历史观点看，今日独立国的巴基斯坦、尼泊尔、斯里兰卡等国，早期都包括在印度的国土范围之内。所以自历史观点来看印度，它是一个历史悠久、土地辽阔、人口众多，气候、生产、种族、语言都极为复杂的地方。唐玄奘三藏在〈大唐西域记〉中，说印度的地形是：'三垂大海，北背雪山'，大体大说，确是如此，它西北方以利曼连峰邻于阿富汗，东北以雪山中隔邻于西藏。下面的半岛，西南望阿拉伯海，东南望孟加拉湾，半岛尖端下面，有一个扇形的海岛，就是古代的师子国、后来的□兰，今日的斯里兰卡。由于四面都为山海所包围，与他国隔绝，所以形成它特有的历史文化。它国内的地势，如果由西面的印度河口，向东面的恒河出海口画一直线，就成了上下两个三角形。上面的三角形，由中间垂直再画一直线，这样就共有三个三角形。上面西北方的三角，是五河地区，东南方的三角，是恒河平原，而下面的大三角，就是频阇耶山以南的半岛。而印度的文明，就是依著这三个三角区的顺序而发展的。

** 二、雅利安人的入侵

印度当地的土著民族，最早而主要的，是达罗维荼族Dravidians，早在西元前两千五百年-​-时当中国黄帝轩辕氏时代-​-就在印度河流域形成了古代的文明社会，这称为印度青铜器时代的文明。青铜器文明的遗迹，在印度河流域的哈拉巴城最显著，所以此一时期又称为哈拉巴文化。据考古学者的发现，那时他们已有了城市规划，有下水道，有两三层砖建的楼房，有公私浴室，街道上有店铺。并且手工的纺织业、陶器业都相当发达。此一文明延续了千年之久，传说是由于雅利安人的入侵而予以破坏。雅利安人入侵自是事实，但哈拉巴文化是否因此而破坏和灭绝，历史上尚无定论。

雅利安人Aryan　人，据近代学者研究，最早是在中央亚细亚地方，约在元前三四千年间，乘世界人口移动的风潮，分别向东西移动。向西者进入欧洲，成为欧洲人的祖先；向东者到达波斯，后来一部份更向东南，就是后来进入印度的雅利安人。雅利安人之入侵印度，约在西元前一千五百年前后。他们越过兴都克什山，进入印度西北部的五河地区。五河，顾名思义，是个河川纵横的地方，河川中最大的就是印度河，它汇集众流，注入阿拉伯海。雅利安人初到此地，感于此河水势之壮阔，称之曰'信度'（Sindhu ），信度，是大水或海的意思。后来由 Sindhu 转为 India，遂成为印度全境的名称。

雅利安人之侵入印度，约在西元前一千五百年前后。那时的雅利安人，已有自己相当的文化。他们已脱离杂婚，建立家庭单位，以父亲为家族之长，构成父系家长制的社会。部族的酋长即是王，王位选举或世袭。他们是逐水草而居的游牧民族，族人勇悍好战，侵入五河地区后，征服了土著，在该地区定居下来，建立了许多国家。五河地区土地肥沃，生产丰富，由于长时期在该地定居，形成了雅利安人的政治文化中心-​-也就是婆罗门文明的中心。雅利安人称那个地方为［中国］（MadhyaDesa）。指此一区域外的地方是化外之地。雅利安人也称此一地区为'阎浮提
'-​-阎浮提，就是后来佛经中称的南部赡洲。

雅利安人的宗教信仰，是自然崇拜。原来初民对于自然界有极大威力的日月星辰、风雨雷电、水火昼夜等，不能理解，以为各有神祗司理，他们礼拜诸神，颂赞诸神。所以有许多想像力丰富、词句美丽的诗篇。这些赞歌由七个家族分别保留下来，到后来有了祭祀的仪式，祭司们把古代赞歌加以汇集，应用到祭祀上，祈求子孙繁衍，家畜增殖，降雨丰收，战争胜利等等，这就是最古老的吠陀圣典，黎俱吠陀。

吠陀，是梵文Veda的音译，是智识的意思，〈翻译名义集〉曰：'韦陀，亦名吠陀，此云智识，由此生智。
'雅利安人称此为七戢所作，是天启的圣典。黎俱吠陀的完成，大约以西元前一千二百年为中心。此后的一两百年间，又有沙摩吠陀、夜柔吠陀的编集，最后又有阿达婆吠陀的出现。阿达婆吠陀，是在该地者著达罗毗荼人间流传的降福、攘灾或咀咒仇敌的咒语，为雅利安人吸收采用到祭典中，而取得第四吠陀的地位，四吠陀的完成，大约是西元前八百年间的事。这四吠陀的内容，如下所述：

(一)，黎俱吠陀Rig　veda：四吠陀中，黎俱吠陀是最原始的一种，这是雅利安人居住在五河地区的时候，诗人歌颂大自然的诗句，及招请诸神至祭祀场所的赞歌。以口耳相传的传下来，最后编集而成的，这是世界最古老的诗篇，由一千十七首所组成，计一万五百八十颂，分为十卷。这是在祭祀的时候，献给诸神的赞唱。


(二)，沙摩吠陀Sama　veda：这是苏摩祭时所用的赞歌，由一千五百四十九颂所组成，分为二卷。其实多是预祝丰年的赞歌。

(三)，夜柔吠陀　Yajur veda：这也是纯为祭祀用的赞歌，它的出世较晚，约是雅利安人离开五河，移居阎牟那河拘罗地方的作品，它是由韵文与散文混合而成的。

(四)，阿达婆吠陀　Atharua veda：阿达婆吠陀与前三者不同，前者是公认的圣典，而此则全是个人招福攘灾、咀咒仇敌的咒法，古代印度称前三吠陀为'三明'，视为三位一体，此则是后来附加的。

** 三、婆罗门教与四姓阶级制度

黎俱吠陀时代所歌颂的神，包括天空地三界，事实上全是自然现象现的神格化，如天界的太阳神，空界的风神，地界的河神等，名目繁多。其中地位最高的，在天界为婆楼那，在空界为因陀罗，在地界为阿耆尼及苏摩。婆楼那是苍空的神格化，是自然界秩序的守护者，如日月运行，四季循环，均由婆楼那司之；因陀罗是战神，他身躯高大，长于勇武，率领众神与雅利安人的敌人达沙作战；阿耆尼是火神，它有破除黑暗，消灭恶魔的力量。雅利安人之崇拜火神，当是早期与伊朗共住时代的习俗-​-即拜火教的习俗。苏摩是酒神，他是神人之间的媒介，是祭坛上重要的神。当时尚没有殿堂神像，每个家庭都有圣坛，要燃圣火、灌牛乳、献米麦、奉神酒，这是常生活中最重要的一部份。而重大的祭祀，则须由司祭者主持。

在四吠陀先后编集完成的多神时代，后世对此一时期，加之以吠陀教的名称。

在西元前一千年前后的时后，雅利安人屡屡发动战争，征服者著，并自五河地区向东南移动，由阎牟那河地区到达恒河平原，并在这里建立了许多国家。在当时流传下来的叙事诗上，可见到拘卢Kuru，般庶Panchala，拘萨罗Kosala，迦尸Kasi等名称。而由吠陀教演变而成的'婆罗门教'，也在这个时代出现了。

婆罗门Brahmana，梵文的原意，是'神学的掌握者'亦有'净行'、'静志'的意思。而婆罗门教，则是由五河时代的吠陀教演变而成的。雅利安人侵入五河地区，征服土著，当时就是有了'种姓'的分别。不过当时只是雅利安人与非雅利安人间的差别。原来种姓梵语'Varna'，它原来的字义是'颜色'、或'品质'的意思。本来，雅利安的梵语'Aryan'，就含有'神圣的'或'高贵的'意思，因此，他们认为白肤色的雅利安人是品质高贵的人，而深肤色的达罗毗荼族和其他土著，都是品质低贱的种族。这就有了雅利安人，与非雅利安人'Anaryan'的分别。换句话说，前者是白肤色的征服者雅利安Aryan　人，或者是被征服的黑肤者著，即所谓非雅利安Anaryan人。

后来因为祭祀的仪式愈来愈繁琐，非专业者不能胜任，于是有了专业司祭者的出现，而司祭者又演变成为世袭，这就形成了婆罗门阶级；另一方面，雅利安人不断的发动战争，于是有了专业战士的一个阶层，即所谓刹帝利阶级；而从事农工商业的人民，被称为吠舍族，原来被征服的土著，就成了首陀族。首陀罗种姓中，也有农人、牧人，但大部分是仆役及奴隶。各种姓的职业都是世袭的，种姓之间不许通婚，尤其禁止首陀罗和其他种姓通婚。如果首陀罗男子和其他种姓女子生下了混血种，在法律上订有一种特别名称，称为'旃陀罗'（Condala
），又称为'不可触者'-​-即可可接触之人。这种人一生只能操最微贱的职业，如屠夫、刽子手、扛死尸者等..。印度现在有七千万'不可触者种姓'的人，他们也常游行请愿争取他们的权利。

四姓阶级渐次形成，界限愈来愈森严，婆罗门阶级高高在上，专司祭祀，有解释经典的权利。刹帝利阶级主管军国大事，和婆罗门同为统治阶级。吠舍族是一般人民，受上二种姓统治及压迫。而首陀罗族的地位愈来愈低下，成为贱民、奴隶，受上三种姓的奴役。并且，上三种姓是'再生族'，都是婆罗门教的信徒，首陀罗是'一生族'，没有信奉宗教的权利，死后没有来生。

婆罗门教形成之后，四吠陀成为天启的圣典。建立了所谓'吠陀天启'、'祭祀万能'、'婆罗门至上'的二纲领。婆罗门高高在上的地位更为巩固。这以后，印度文化进入梵书时代。梵书时代大约是西元前八至七百年间。如昧把四吠陀视同佛教的经，梵书就是根据经所造的论。详细一点说，四吠陀本典，全是祭祀时的圣歌，而梵书是在适用上-​-即祭祀上加以明白的解说。所梵书是附属于各吠陀本典的神学书。

梵书之后，继之有森林书的出现。森林书，是离开村落在森林中传授者，内容是叙述秘密的祭祀仪式和神秘的教义。它相当于佛教经论的注释。不过有一点要加以说明的，四吠陀、梵书、森林书，全是口口相传的传下来，并没有文字记录，因为那时印度尚没有书写的工具。

** 四、梵书时代神格的升沈

婆罗门教继承吠陀教，也是一个多神的世界。四吠陀时代，众神分布于天空地三界，有三十三神、即三十三天之说。除此之外，尚有名目繁多的低级神祗，如乾闼婆、梨布斯等。而三界的主神，常随著时代的需要而有所升沈。雅利安人移居恒河流域后，征服土著的战争渐形减少，战神因陀罗因之失势，代之而起的是生主神。生主神是宇宙最高的原理，是宇宙的支配之神，也是祭祀的主神。生主神生天空地三界，支配三界的太阳神、风神、河神。生主神生三吠陀，生三光明，生人类及生类-​-生类，是人类以外有生命的动物。生主神从它的口、胸、股、足等处，生出不同的神和人。总之，生主神是宇宙的本源，也是宇宙的主宰。这到后来演变成'梵'是创造宇宙万物的主宰，梵从口口生出婆罗门，从胁部生出刹帝利，从腹部生出吠舍，从足部生出首陀罗。以此定四种姓的贵贱，这是创造神的旨意，这也为种姓制度建立了根据。后来佛经中称圣化后的佛陀是由右胁而生，那是一种'通说'，凡是刹帝利种姓全可说成是右胁而生的。

到梵书时代的中期，生主神渐次失去了主宰的地位，代之而起的是'梵'。梵成了宇宙的最高原理，当然这其间尚经过相当复杂的演变。最初，梵是附属于生主神的，叫做'初生梵'。后来逐渐演变成梵和生主是一，成为'生主是梵'。最后梵代替了生主的地位，成为宇宙最高的原理-​-梵生诸神，梵是天地之主，天地由梵所护持。至此，梵完全取代了生主神的地位，具有创造神兼主宰神双重性格，此时称为'自存梵'。至了奥义书时代，演变为'梵我不二'、'梵我一如'的理论。

梵书和森林书时代，印度的文化中心是在恒河中游，且继续向下游拓殖。这时雅利安人之间也不断发生内战，部族间酋长的小王，合并小部落而成为大国王。存留的小国也成为大国的附庸。大国的王权扩大，许多本来是选举制的王国，也代之以家传世袭。个人拥有土地财产，国王课人民六分之一的租税，这就逐渐演变成有如中国古代封建社会。

婆罗门种姓高居四种姓的首位，后来佛经中提到四种姓时，改变了四种姓的顺序，把原来居于首位的婆罗门改为第二位，变成刹帝利、婆罗门、吠舍、首陀罗。是有意贬抑婆罗门的地位，但与传统习俗就不符了。

在婆罗门种姓中，僧侣-​-即是司祭者，是特权阶级。婆罗门也有为王室服务的，但都是王师、大臣高位。也有是教师、地主等职业。僧侣是世袭的（当然要娶妻生子），他们主司祭祀、教育、文化，有解释经典的大权，他们把经典解释得神秘难懂，把祭祀仪式改变成繁琐万端。到后来，刹帝利王族为了解除婆罗门主义加给自身的束缚，策动开明的婆罗门学者，发动思想上的革新动动，这样，就有了反对仪式主义的奥义书的产生。

** 五、奥义书时代

初期奥义书的出现，是西元前七百年间的事。

奥义书Upanisad，音译优波尼沙陀，有'近侍'、'侍坐'的意思。意谓这是师徒近坐，所传达的秘密教义。奥义书不是一个人和一个时代的作品，那是历时数百年，无数婆罗门学者思想结晶。近代学者研究，总数有二百余种，后世所传者通常谓一百零八种。以其文体、语法内容来区分，可分为三个时期：

(一)，初期的奥义书，出现在佛教与起以前，约在西元前七至六世纪间，全部是散文体裁。

(二)，中期的奥义书，是西元前四百年至二百年间的作品，其中以韵文为主，间有散文。

(三)，后期奥义书，是西元前二百年，至西元后二百年的作品，也是以散文为主。

奥义书的兴起，是开明的婆罗门学者对于传统祭祀主义的反动。在传统积习下，他们对吠陀经典之绝对权威，祭祀之万能主义，及婆罗门之绝对尊贵，虽也大体承认，但时有否定的非婆罗门思想。如〈圣徒格耶奥义书〉中，尖刻讽刺婆罗门僧侣为'群犬的腌声'，由此可见他们对婆罗门僧侣的反感。奥义书初期的婆罗门学者，他们上继吠陀时代，继吠陀末期的哲学思想，脱去祭祀仪式的外衣，深入的作哲学的探讨。同时也继梵书末期的'梵我不二'之说，加以充实而完成之。

'梵我不二'说，是说'梵'Brahman，是宇宙的原理；'我'Atman，是个人的原理-​-个人的精神原理。因此，我的本性和梵的本性同一不二。也就是在个人的我以外，建立宇宙的大我-​-梵。梵是宇宙的原理，是遍在的，有情界和物质界是梵的显现。个人的我是小我，是'尝蜜的'命我。尝蜜，是精神攀缘外境的意思。

梵是宇宙的原理-​-本源，所以宇宙万有都是梵的显现。物质界的地水火风空五大，有情界的天、人、生物-​-胎卵湿化所生的生命体，人、象、牛、马，全是梵所创造。不过，这期间仍然以人为本。

梵本来是'原理'，是'概念'，但是后来神格化，演变为梵天、大梵天王。

印度的轮回思想，起源颇早，最初是民间的下层信仰，或起源于土著的黑人。至梵书时代，为吠陀学者所吸收，故在梵书末期已有此说，这是与'我'论相应而有的。但是成为一种不易的理论，则是在奥义书时代。奥义书上说：人从欲而有，从欲而生意向，由意向而有业，从业而有果。有情的生命，以业分做两个方向进行，一个方向是现象化的继续，就是轮回；一个方向是回到本体-​-梵，就是解脱。

现象界的轮回有三条途径：一个人如果恭谨如仪的从事祭祀，死后便能由天道而生于太阳的世界，回归于梵，获得永恒的幸福；反之，如不能恭谨如仪的行祭祀，死后则经由祖道生于月的世界，转生为人；而行恶者则生于第三道-​-兽道或地狱道。

这业与轮回的理论，后来佛教从俗的加以融摄，并变易了其内容。

* 第二讲　百家争鸣-​-思想混乱的时代

** 一、婆罗门的堕落

印度古代的婆罗门-​-四吠陀时代的司祭者，对于印度文化有值得肯定的贡献。他们是人民的导师，在日常生活上予人民以呵护及指导。在佛教原始经典《杂阿含》的《婆罗门经》、及巴利文《经集》中，曾把古代的婆罗门和当代的婆罗门加以比较，并且赞扬古代的婆罗门的德行。经文的大意说：

古代的婆罗门，都是善行的人。他们个个都相当自制，他们摒弃一切逸乐，全力尽他们的义务。

古代的婆罗门，他们没有羊群，没有金子，没有财产和谷粮。他们的财富和粮食，就是持诵的经文，他们坚守著使他们成为婆罗门的戒律。

曾经有坚守独身四十八年的古代婆罗门，为的是追求他的信仰，实践他的信仰。

古代婆罗门不与其他种姓结婚，他们不'买'妻子，他们与妻子共用爱与和谐的婚姻生活。

古代婆罗门，严守道德规律，他们贞洁、诚实、柔顺、忏悔与努力，这些都是为人所称颂的。

古代的婆罗门，举止优雅，身体宏伟，名声卓著，行为正当。他们不但热衷于善行，而且竭力阻止邪恶。因此，他们使人民获得无比的幸福与快乐。

以上是古代婆罗门的写影。可是，四姓阶级确定，婆罗门成为特权阶级以后，他们高高在上，养尊处优。一代一代傅下来，婆罗门逐渐堕落了。权力使人腐化，千古同出一辙。他们追求财富，追求享受，过著放逸宴安的生活。而却又道貌岸然的劝人为善，劝人祭祀布施。他们使祭祀仪式复杂繁琐，以他们解释经典的权力，向人民勒索供物-​-牛、马、羊、野羊，甚至于女人。这样，不但使刹帝利阶级难于忍受他们的束缚，也使一般民众感到失望。在南传佛教的《经集》中，继上段赞颂古代婆罗门经文后，有下列的记述：

随著时日的消逝，这些婆罗门逐渐误入岐途。

他们只看到快乐，国王般的豪奢生活，和打扮美丽入时的美女。

他们的车蓬画满了图画，边缘另加饰彩，并用上等马拉车；

他们的大厦建在风景最优美、交通最方便的地方，

并设有层层重拥的门阙和花园。

世俗的财富，无数的乳羊、珍美的事物和美女；

这些，全都是婆罗门所想要的。

于是他们便杜撰经文，然后到国王的根前说：

献给我们财产，你们有的是；献给我们金银，你们均极富有。

这样来生你们才会拥有更多的财富。

而这些国王，居然听信了婆罗门的话，

不但举行马的献祭礼，还举行人的献祭礼，

不但展开铺张的欢宴，还允许肉体的欢献..

等到汇集所有的财富和宝藏后，

他们因达到目的而窃喜，并将那些珍宝储藏起来。

由于利欲薰心的缘故，对爱欲的渴望，

在他们心中燃烧的更加炽烈。

当戒律不再有效，敌意在奴隶和群众间升起。

武士和贵族分裂而互斗，妻子们也轻视他们的丈夫。

这些武士、贵族、和婆罗门，还有其他受种姓制度庇荫的人，

对于他们的血统、地位不再顾虑许多，

而任由他们自已沉迷于淫逸和欢乐中。

这就是西元前五六百年，释迦牟尼出世前后已经堕落了的婆罗门。由于婆罗门的堕落，加以社会环境的改变，在佛陀出世前后，印度社会出现了许多'自由思想家'-​-即所谓'沙门集团'，这包括著后代所称的'六师外道'-​-各有大批弟子及信徒的六个集团；'六十二见'-​-六十二种不同的理论见解；'三百六十三论师'-​-三百多位思想界的辩论家等等。

** 二、百家争鸣-​-沙门集团的兴起

佛陀出生前的印度社会，由于婆罗门的堕落，社会上兴起了反婆罗门的风气，出现了许多自由思想家。自由思想家的出现，也有其时代背景。恒河流域的社会，不同于五河时代。恒河流域的土著民族，在比例土要比五河地区更多，相对的雅利安人比例就降低了。虽然规定上种姓之间不许通婚，但事实上种姓混合却愈来愈普遍。雅利安人为了巩固其对地方上的统治，允许土著部族的领袖，通过祭祀仪式，可以升格排入刹帝利种姓-​-这有如三百多年前满清入关，以少数统治多数，汉人-​-特别是有功的将领可以通过皇帝特许而'入旗' 。原本是满汉不许通婚，到后来禁令松弛，也就成为具文了。

雅利安人自五河地区向东南拓殖，这时定居在恒河中游，在此建立了许多国家，这在当时有十六大国之说，还有许多城邦式的小国不在其中。恒河流域土地肥沃，物产丰富，人民的生产方式除了由畜牧改变为农业外，手工业及商业亦日趋发达，这样就出现了许多以工商业为主的城市。工商业者以经济力为后盾，有否定传统的倾向。加以上述的因素，雅利安人是少数民族，其影响力已不如五河时代。再则由于婆罗门的作为不仅使人失望，且亦使人反感。于是社会上出现了些以自由立场思索、修行，以求解答宗教及哲学上问题的修道者。这种修道者日益增多，他们托钵行乞，栖止山林，社会上称这种托钵行乞的修道者曰'沙门
'Sramana。后来二十九岁出家修道的佛陀-​-释迦牟尼，当时就是众多沙门中的一个。

关于出家修道，托钵乞食，亦有其传统的背景。雅利安人拓殖到恒河流域后，当地夏季极长，气侯酷热，使人的思想沉滞。这样婆罗门学者便提倡到清凉的山林中去修道。梵书之后的《森林书》，就是在森林中编集的。这种森林生活，最初只流行于婆罗门阶级，后来扩及于上三姓，在西元前六世纪之初，把上三种姓一生应遵行的四期生活，规定到《法经》中。但实际上仍是以婆罗门遵守为主。这一生四期生活制度，称作梵行期、家居期、林栖期、云游期。其大约内容如下所述：

'一'、梵行期：　婆罗门种姓的儿童，在八至十二岁之间，要出家就师-​-住在师父家中，研究《吠陀经》，学习祭祀仪式，修养品德。同时朝夕奉事圣火，笃事师长。这种生活，通常是十二年。师父如果是林栖者，弟子亦随侍于林中，并到聚落中乞食以奉师。

'二'、家居期：　梵行期满，回家以营世间生活。结婚生子，以慰祖先在天之灵。经营生计，祭祀诸神，接待宾客，以尽本阶级的职责。

'三'、林栖期：　年岁既老，人生义务已毕，以家庭交付长子，以财产分配诸子，自已隐居于于森林中，修苦行以练身心，对四吠陀教义沉思冥想，进修道业。

'四'、云游期：　到了老年，剃去发鬓，手持杖与水漉，悬头陀袋，云游四方。这种云游的人，被称为比丘、沙门、行者、或云游者。

当时社会上，本来就有这种以饮食布施比丘沙门，而获功德福报的传统习俗。这就是新出现的沙门，栖止山林，托钵乞食而民众乐于布施的原因。后来佛陀领导的僧伽，乞食制度即取法于此。所不同者，是不经过前三期，年轻时即直接成为比丘-​-托钵乞食的修道者。

** 三、六师外道

佛陀出世的前后，这种托钵乞食，栖止山林的修道者为数极伙，其中名气最大，弟子众多的，要以'六师外道'为代表。

外道Tirthaka，梵音底体迦，译曰外道，亦作外教、外学，指佛教以外的一切宗教，是佛教称其他教派的名词。最早，这一名称并不含有贬抑的意义。Tirthaka 的原意，系谓'神圣而应受尊敬的隐遁者'，意思是苦行者、正说者。佛教自称内道，经典称为内典，佛教以外的经典称外典。到了后世，在这个名词上附加上了异见、邪说等意义，就成为一个含有侮蔑意义的贬称了。

不过，如果我们探讨外道的理论，有许多教派的确是充满了邪说谬见。我们且来看看六师外道的理论：

'一'、富兰那迦叶　Purana Kassapa： 他是一位无道德论者，他否认善恶和业报，他说：斫伐残害，煮炙割切，恼乱众生，愁忧啼哭，杀生偷盗，淫佚妄语，逾墙劫贼，放火焚烧，..非为恶也； 若以利剑脔割一切众生，以为肉聚，弥满世间，此非为恶，亦无罪报。于恒水南岸脔割一切众生亦无有恶报，于恒水北岸为大施会，施一切众，利人等利，亦无福报。

'二'、阿夷多翅舍钦婆罗　Ajita Kesakambali： 这是一位澈底的唯物论者，也是否定因果、业报轮迥论者，他不承认物质外有精神的存在。他说：受四大人，取命终者，地大还归地，水还归水，火还归火，风还归风； 悉皆败坏，诸根归空。人若死时，床舁举身，置于冢间，火烧其骨，如鸽色，或变为灰土。若愚若智，取命终者，为断灭法。

'三'、婆浮陀伽旃延　Pakudha Kaccayana： 他是唯物论者、无因论者，否定善恶业报者。他说： 一切众生，身有七分，何等为七？ 地、水、火、风、苦、乐、寿命。如是七法，非化非作。不可毁害，如伊师迦草，安住不动，如须弥山。不舍不作，犹如乳酪。各不诤讼，若苦若乐，若善不善，投之利刀，无所伤害。何以故？ 七分空中无妨碍。命亦无害，何以故？ 无有害者及死者故。无作无受，无说无德，无有念者，及以教者。

'四'、末伽梨拘舍梨　Makkhali Gosala： 他是一位宿命论者，他认为人生苦乐不由因缘，唯为自然所产生。他说： 人之善恶净秽，悉由命定，非由戮力懈怠而得故。世间无因果业报，非自体，非教作，非精进所致，非自由意志，一切悉由命定。吾人之命运、环境、天性可别为：黑、青、红、黄、白、纯白等六，由此而受苦乐。贤愚不肖等、于历八百四十劫尽有漏业，以业尽故，众苦得尽自得解脱。 这种谬论，佛陀批评它是用人发织成的衣服，夏不吸汗，冬不保暖，毫无用处，却给社会带来迷惑与不安。这一派在当时又被称为邪命派。

以上四种外道，全是否定因果，否定业报轮回者。尤其是富兰那迦叶，他不仅否定业报因果，并且否定善恶，破坏社会道德秩序。奇怪的是，这种荒谬之见，在当时竟成为一种哲学理论，受到许多人的拥护。也许这是对当时社会阶级制度不平，婆罗门假冒为善的一种抗议吧！在迷失、混乱的时代，这种破坏道德秩序的言论反易于为人接受。另外两种外道是：

'五'、散阇耶毗罗胝子　Sanjaya Belatthiputta：这是一位怀疑论者，不承认认知有普遍的正确性，而主张不可知论。他认为： 善行恶行的果报，可说是有，可说是无，又可以说是有是无，也可以说非有非无。可说是既不肯定也不否定的诡办论者。

'六'、尼乾陀若提子　Nirgrantha Natapata： 他是耆那教的教主，他的思想与佛教很接近，主张有因果业报，以修苦行为解脱方法。信徒须守五戒-​-不杀、不盗、不淫、不妄、无所有(财物)。耆那教的戒律严谨，信徒有强固的向心力，是传统的婆罗门教外，与佛教并存的两大宗教。迄今印度尚有百数十万耆那教信徒。

** 四、一元多元，断见常见

当时的思想界，对于人生问题，否定业果轮迥，否定善恶道德； 而对本体问题-​-形而上的本体界，更是异说纷纭，立论各异。有一元论、二元论、多元论种种。而对宇宙人生存在的形而上的本体，有永恒实体之说，有归于断灭之说，这即所谓一元、多元，断见、常见。

早期的婆罗门教，以创造支配宇宙人生的最高神为永恒的存在。这最高的神，虽以时代不同而名称有所改变-​-如生主神，梵，但都是一元有神论的神祗。奥义书以哲学立场讨论此一问题，以宇宙原理的'梵'与个人原理的'我'一体无别，主张'梵我一如'，以此为永恒不变的本体，这是哲学上的一元论。而自由思想家的沙门集团，多是主张多元论。如六师外道中的婆浮陀伽旃延，以地、水、火、风、乐、苦、寿命等七原素为七身，此七原素是常恒不变的存在。末伽梨俱舍梨于七原素之外，更加上空、生、死、得、失为十二种要素。尼乾陀若提子把存在分为灵魂的存在和非灵魂的存在，灵魂的存在不但包括人和动物，甚至于连植物、地、水、火、风等无生物也是灵魂的存在； 非灵魂的存在则有法( 运动原理)、非法(静止原理)、空间、物质要素四种。而此四者亦是常住不变的存在。此四者加上灵魂，共有五种实体元素，称之为五有身。

形而上的本体，有一元、有多元；而本体的存在，有认为永恒的存在，有认为存在并不是永远的，终归于断灭空无。佛教称前者为常见，后者为断见。常见者认为灵魂在今生肉体死亡后，来生之前是常恒存在；断见者认为人受生之时，灵魂从空无转于肉体，肉体死亡，灵魂亦随之消灭。这完全是唯物论的论点，肉体之外没有灵魂的存在。阿夷多翅舍钦婆罗即是这种主张。在此常见断见之外，还有既不属常见又不属断见的，即既不肯定也不否定的，散阇耶毗罗胝子就这一派的领袖。

后来佛教把这些不同的理论归纳起来，有六十二种之多，即所谓'六十二见论'-​-六十二种错误的谬见。这六十二见再加以归纳，就是后来佛陀所不予置评的十无记或十四无记。

** 五、邪说充斥、思想混乱的时代

西元前六世纪，佛陀出世前后，印度的国际情势，是十六大国、无数小国林立，互相征伐兼并，有如我国的战国时代(西元前六世纪，也正是我国东周的战国时代。)兵连祸结，生灵涂炭，社会动汤不安。而四姓制度的森严，政治地位的不平等，经济分配的不平均，首陀罗种姓的贱民，过著牛马不如的生活。尤其是当时的思想界，邪说充斥，思想混乱-​-外道否定因果，否定人生努力的意志，使人生价值迷失，甘于堕落。真所谓漫漫长夜，何时出现光明。

然而，就在这混乱迷失的时代，佛陀出世了，他以真理之光，照澈了黑暗的世界； 他以万法缘起理论，肯定人生努力的价值； 他以十二缘起说明生死轮回，他以诸行无常、诸受皆苦、诸法无我的三法印说明人生真像；他以四圣谛八正道，指示出人生解脱法门。使人生有了目标，有了希望。

佛陀，是天人师，是众生父，是一代圣哲。他是历史上实有的人物，是由人成佛的典范。下一章，我们将以人间的佛陀、历史上的佛陀，来介绍佛陀的一生。

*  第三讲　长夜中的真理之光-​-佛陀证道

** 一、人间佛陀

人类自有历史以来，为世人所公认'四大圣哲'，是释迦牟尼、孔子、苏格拉地、耶稣。

中国人称颂孔子，有谓：'天不生仲尼，万古如常夜'。我想、这句话如果用在人间佛陀释迦牟尼身上，也是十分妥切。正如三宝歌所云：'人天长夜，宇宙甚闇，谁启以光明？'是谁呢，是人间佛陀释迦牟尼。

我们在此一再强调'人间佛陀'，那是有别于后代经典中圣化后的佛陀。

佛教传入中国已逾两千年，中国人多具'大乘根性'，所以盛行大乘佛教。早期译经师虽也把原始佛教的 《四阿含经》 译为汉文，但中土的大乘行者，极少有人注意及所谓'小乘经典'。因之我人在大乘经典影响下，认为小乘行者是'自度自利'； 是'蕉芽败种'。因此连带对小乘经典也不屑一顾。

以此之故，我们所认识的佛陀，是为后世佛弟子圣化后的、大乘经典上的佛陀，而不是历史上的、由人证道的佛陀。由人证道的佛陀，是两千五百余年前，出生在北印度伽毗罗卫国的乔答摩、悉达多太子。他有感于人生生老病死的苦恼，十九岁出家修道。他曾历访各派宗教哲学人士，不得要领，最后在苦行林中自行参究，终于证悟了真理，成了人间佛陀-​-人间的觉者、智者。他后来被尊为'释迦牟尼'，意谓'释迦族的圣者'。

佛陀涅槃后，由于后世弟子对于佛陀的崇敬与怀念，或为了宗教上的原因，把佛陀圣化、神化、梵化、塑造成了大乘经典中理想化的佛陀。这位理想化的佛陀，具有不可思议的神通与法力，他超越了人间，上升到天界。他不是人间的觉者和智者，而被塑造成了神-​-众神之上的神，有如造物主似的上帝。有些经典中夸张的称：
佛陀居则金刚宝座，行则地涌莲花，外出则梵天执伞，帝释前导；
讲经则天龙八部护持左右。于特殊事故，则大地震动，天雨香花。这种超乎常情的渲染，绝不是佛陀生前的真面目。

人间佛陀的真面目是什么样子呢？

他有如中国的孔子，是一代圣哲，是人间伟大的教化师。他成道之后，四十五年游行传道，席不暇暖，汲汲于宣示真理。他游化期间，身著坏色之衣，手持乞食之钵，千里远行，赤足徒步，直到八十岁最后一次游化仍是如此。他没有权势，没有武力，也没有钱财。但是，在当时诸国林立的印度社会中，上至国王大臣，中至工商人士，下至贱民奴隶，都对他有著至高无上的祟敬与信仰。

佛陀是人间圣哲，人间圣哲被圣化、塑造成天上众神之神的时候，这就模糊了佛陀本来的面目。以指示月，若以为手指就是月亮，不惟失去了月亮，且亦失去了手指；圣化为神的佛陀，不惟天上的神不是佛陀，且亦失去了人间的佛陀。这就是为什么西洋学者、不以为释迦牟尼是历史上实有的人物，甚至于说佛陀是神话中太阳神的化身。

由于佛陀被后代弟子的圣化和神化，连带著佛教也变了质，变成了神佛不分的宗教。尤其是号称大乘之国的中国佛教，历来只是高僧大德、文人名士的佛教。而流传在民间的佛教，只是中国民俗化以后的佛教，所以给人的印象，是烧香、膜拜、求庇佑、求福报。以至于求子、求寿、求官、求财。这就与佛陀要人依正法而求智慧、求解脱的精神，完全背道而驰了。尤其是与民俗宗教合流，在葬仪中超度、荐亡、诵经、礼忏，使人讽之为完全是为死人服务的宗教，这就使佛陀的正法完全变了质。

如果我们要想认识佛陀的真面目，想要了解佛陀的正法，我们必须自原始佛教的经典中去探索； 尤其是南传佛教的经典，有著与佛陀思想更接近，更较真实的资料。于此，我们就从早期的经典中来认识佛陀。

** 二、雪山南麓下的小城邦-​-迦毗罗卫国

信仰佛教的人，莫不知道佛陀是印度迦毗罗卫国的王太子，这伽毗罗卫在什么地方呢？

印度的地形是'三垂大海，北背雪山'。雪山就是喜马拉雅山，实际上是在印度东北边境。雪山北麓是我国的西藏，南麓是现在的尼泊尔，古代的北天竺。

在现代尼泊尔的泰来地区，是一处高原性的盆地。于天气晴朗时，由此远眺，可以看到喜马拉雅山万年不化的积雪。夏季一部分积雪融化，汇成许多条河流，其中有一条罗泊提河，向南流入印度第一大川-​-恒河。而迦毗罗卫国，就是在雪山南麓，罗泊提河东北的一片土地上。许多佛教书籍上称迦毗罗卫地大物博，社会富饶。那是夸张之词，迦毗罗卫土地约长二十公里，宽十六公里，面积约三百二十平方公里。据说这片土地上有十个城邦，共有八万户人家，约有五十万人。十城邦各有城主，早先是由十位城主开会，推出一位有德威声望的人为王-​-类似联邦制的主席，后来演变为世袭，这世袭的王就是迦毗罗卫城的净饭王-​-释迦牟尼的父王。

释迦牟尼，不是佛陀的名字，是佛陀的称号，意思是释迦族的圣者。所以释迦是族名。释迦族不是雅利安人，圣严法师著《世界佛教史》，称释迦族与跋耆族相近。他们不愿与雅利安人通婚，视为非我族类。而后来释迦族与跋耆族出身的比丘，都有以佛是我族而夸耀者。我国地理学家李学曾著《亚洲种族地理》，书中分析不丹、锡金、尼泊尔都是蒙古西藏的民族，故其人面部平坦，肤色较黄 ( 佛经中说佛陀的身体是金色 ) ，与欧洲的白种人迥异。本来尼泊尔与西藏只一山之隔，释迦族与西藏民族有血缘关系，亦非不可能。

佛陀的家世，据说他的家族姓乔达摩Gotama(早期译为瞿昙)，祖父师子颊王有四子，即是净饭王、白饭王、甘露饭王、和斛饭王。佛陀出生时，净饭王是迦毗罗卫的国王。佛陀就是净饭王的长子。佛陀的母亲摩耶夫人，是罗泊提河西岸，拘利族天臂城城主、阿拿释迦王的女儿。拘利族，是释迦族的胞族-​-胞族，是社会学上的名词，是由血亲氏族或亲属集团组成的群体。他们的结合是由于相信有一个共同的祖先，或由于采用共同的祭礼。他们采近亲联婚制度，以保持血统的纯净。据说阿拿释迦王的妃子，就是师子颊王之妹； 而后来，悉达多太子的妃子耶输陀罗，又是摩耶夫人的侄女-​-她哥哥善觉王的女儿。

佛陀入灭于西元前四八六年，一般资料都认为佛陀八十岁涅槃，则其出生年代应在西元前五六五年-​-关于佛陀生灭年代，有数十种不同的异说，前后相差数百年之久。印度是一个素来不重视历史的国家，自古以来，互相矛盾的传说，任其同传并存而不以为怪。印度古代没有书写的工具，一切经典、史传，都是口口相传的传到后世。佛教的贝叶经，是西元前一世纪才出现的。所以对于佛教早期的史料，也只能从众说纷纭中加以抉择了。本稿所称的生灭年代，是在北传佛教中，为较多人所认同的、根据《善见毗婆娑律》所附的'众圣点记'所推算的年代。

** 三、乔达摩、悉达多太子

写佛陀传记，说容易很容易；说难又十分困难。往容易地方说，以大藏经中的佛传资料如：
佛本行经、过去现在因果经、十二游经、佛所行赞、或普曜经等等，以'八相成道'的顺序，平铺直叙的写下来，就是一篇无懈可击的佛传。但我们是要探索人间佛陀的真面目，当然不能用这种写法。说难呢，在所有佛传的资料中，任举出一个问题稍加考证，全是众说纷纭，矛盾百出。诸如佛陀的生灭年代，佛陀青年时的婚姻情形，佛陀究竟多少年岁出家，佛陀独子罗侯罗何时出生..等等，全不易考证出结论。本稿限于篇幅，也不能一一细述，我们只能择重点加以说明：

传说净饭王的王妃摩耶夫人，中年时才初次怀胎。妊娠期满，按照当时习俗，头胎的孩子要回娘家生产，净饭王派遣宫女侍从，护送夫人归宁。夫人一行人到了中途，经过一处叫'蓝毗尼园'的时侯，可能是旅途劳顿惊动了胎气，就在园子里的树林中生下了孩子。《根本说一切有部毗奈耶杂事》二十，有下述夸张的圣化记载：

摩耶夫人往蓝毗尼林攀无忧树下，暂时伫立便于右胁诞生菩萨(菩萨，是经中对佛陀未证道前的尊称)，尔时大地六种震动，放大光明与入胎无异。菩萨生时帝释亲自手承置莲花上，不假扶持，足踏莲花行七步已，遍观四方手指上下作如是语： 此即是我最后生身，天上天下唯我独尊。梵王捧伞天帝执拂，于虚空中龙王注水，一温一冷灌浴菩萨。初诞生时于其母前，自然井现，香泉上涌，随意受用。

所有的佛传，都是在佛入灭数百年后才成书的。至此、佛陀的人格已被圣化、超人化、神化。后世的佛弟子中，许多是出身于婆罗门种姓而出家修道的，这样就把婆罗门教的众神吸收到佛教中，以抬高佛陀的地位-​-后来婆罗门教的后身印度教复兴，照样也把佛陀吸收到印度教中，说他是印度教三大神之一、毗湿奴九次化身救世的化身之一，印度教的庙宇中，也有把佛陀塑像供奉于侧殿的，新德里的贝拉庙便是一例。

说佛陀是右胁生的，也有其根据。梵书时代的生主神，从祀口胸股腹等处，生出不同的神和人。到后演变成'梵' 是创造之神，婆罗门种性是由梵的口中生的，刹帝利种性是胁生的，吠舍种姓是腹生的，首陀罗种姓是脚底板生的。所以说释迦牟尼是胁生的，那是一般性的说法。也可以说，刹帝利种姓全是胁生的。

摩耶夫人生子，这是轰动全国的喜讯。净饭王为孩子命名悉达多，梵文的意思是'一切义成'-​-具备一切德行的意思。不过很不幸的是，太子出生七日，摩耶夫人便因病逝世了。这样一来，抚育太子的责任，就落在夫人的妹妹波阇波提身上。波阇波提也是净饭王的妃子，她于悉达多太子，是姨母，也是继母。资料中说、波阇波提夫人爱护太子，有如己出。这当然无可置疑。但是，姨母、继母之爱，是否就等于母亲之爱呢？ 所以太子自幼就性格沉默，好沉思冥想，这可能与他繦褓丧母有关。

据佛经记载，太子出生后，有这么一段插曲，说是南方大山中，有一位名望素著的阿私陀仙人，到王宫求见净饭王，声称要为太子占相，净饭王命人抱出太子，请阿私陀仙人观看，阿私陀观察良久，最后叹息著说：

'大王啊！照太子的相貌看来，在人间找不出第二个，将来长大，他若在家，一定为转轮圣王；他若出家，可以成就一切智慧，利益天人。但据我观察，太子将来必定出家学道，转大囧琺錀，可惜我老了，恐怕将来看不到这种情形了。'

说罢叹息著告辞而去。

太子七岁，净饭王为他请婆罗门跋陀罗尼为师。教授'四吠陀'、'五明'之学-​-五明，是声明、工巧明、医方明，因明，内明。十多岁时开始学武-​-释迦族义译为强勇之族，刹帝利又是武士阶级，习武是理所当然之事。据说他精擅击技射术，一箭能射穿七张皮鼓。有一次，太子随父王到郊外巡视，太子见田中农夫，裸背赤体，在烈日下耕作。老牛拖著犁奋力前进，还被鞭打的皮破血流。田中犁出的小虫蚯蚓，为鸟雀竞相啄食。一幅活生生的生存竞争图，使太子看的触目惊心，无限哀痛。于此，他感到人生是大苦聚，心中时有出家之想。

** 四、太子出家-​-太子为什么出家

依据《中阿含柔软经》说： 佛陀在郊外看到农民在烈日下耕作的情形，引起无限伤感。他不忍众生自相残杀； 不忍老死忧苦迫逼，使他有了出家的念头。

净饭王见太子日常沉默不乐，想起了阿私陀仙人的预言，怕他心萌遁世之意，乃想如及早为他结婚，或可打消他出家的念头。净饭王乃太子完婚，妃子是天臂城善觉王的女儿，即是太子的表妹耶输陀罗-​-太子的婚姻，有许多异说，成婚的年龄，有谓十七岁，有谓十九岁；
婚姻的物件，有谓太子有三位夫人，一为耶输陀罗，一为乔比迦，一为鹿王。另一说谓太子的三位夫人一名瞿夷、一名耶惟檀、一名鹿野。这两种说法，都载之于经典。其实这也无关紧要，一国王储，有三位妃子，也事属了寻常，此处不再细述。

据经典中说，净饭王为太子完婚，为他在宫苑中造了冬天住的暖殿，夏天住的凉殿，和春秋住的中殿。苑中广造池台，栽种花木，并以许多宫娥彩女随侍。净饭王希望以人间宫室犬马，声色歌舞来羁绊太子，以免他出家修道。关于这些，经典中有许多夸张性的叙述。关于完婚，则谓：'王即令诸臣择采吉日，遣车万乘，而往迎之'。关于宫中生活，则谓：'太子父王为立三时殿，殿有二万彩女，三殿凡六万彩女..'云云。这夸张的十分离谱。迦毗罗卫距天臂城一河之隔，'遣车万乘'迎亲，怕不把道路塞满？以人口有限的蕞尔小邦，何来此六万名适龄的少女？ 在《中阿含》一一七的《柔软经》中，称成道后的佛陀，在舍卫城祗园精舍，为弟子们说到他出家前的宫廷生活，大意是说：

比丘们呀！在没有出家以前，我过著非常幸福的生活。我家的宫苑中有著池塘，漂浮著美丽的莲花。在房间里，也时常飘浮著□檀的芳香。我所穿的，都是伽尸所产的最上等的布帛。有三处宫殿供我住用冬天就住在冬殿，夏天就住在夏殿，春天就住在中殿。在夏天的雨季里，整天躲在夏殿里，以歌舞取乐。出门时，自有一把白伞为我遮太阳。别人家以米糠绊稀饭供养佣人和寄住的人，我家供养的却是米和肉。

上面一段经文，说的十分朴实可信。净饭王是城主也好，是国王也好，在宫苑中盖上不同季节居住的房子，房中使用檀香木的家俱，穿著迦尸产的上等布帛，家中佣人和寄居者都吃米和肉，这都在情理之中。一般富有人家尚且如此，何况是一国之主呢？

与一般人来比较，太子的身份是既富且贵，一呼百诺。若是一个普通青年，过著这种安富尊荣的生活，且身居王储之位，他大可安于现状，等待著继承做国王了。无奈这位悉达多太子，他具有超人的宿慧，悲天悯人的性格。在当时四姓阶级制度下，婆罗门高高在上，假藉神命，谋取私利； 刹帝利的王室贵族，执掌军国大权，是统治阶级，生活奢靡； 上二种姓究竟只是少数，而广大的奴隶贱民阶级-​-脚底板生的首陀罗族，一生作人奴隶，一代一代生下来的孩子，先天的就注定了他们作奴隶的命运，这能算一个公平的社会吗？ 他不满于当时的宗教及政治，他把众生的痛苦当作自己的痛苦，为了探索解脱自我与众生痛苦的大道，他决意摆脱一切去出家-​-他以他个人的意志力，克服了宿命的安排。

在许多佛传的经典中，记载有'四门游观'的故事。大意是说太子在宫苑中日久，想出外游观，净饭王十分铺张的命臣下陪同太子出游，首次经过东门，净居天王化作老人：'头白背伛，柱杖赢步'。太子问从者曰：'此为何人'？ 答曰：'此为老人'。太子又问'何者为老'？'唯此人老，他人皆然'？后来见到病者、死者，都是照这一模式问答。最后出北门遇到净居天所化的比丘，太子说：'善哉善哉，天人之中，于此为胜，我当决定为学是道'。太子返宫即行出家。其实这只是经典文学表现的一种手法。太子出家时，年已二十九岁，岂能对老病死人都分不清楚？

认真探讨，太子出家，可能亦与他身为王储的身份有关。那时印度诸国林立，征伐兼并，习以为常。迦毗罗卫蕞尔小邦，无四兵之战备-​-四兵，是步兵、骑兵、车兵、象兵-​-有强邻之觊觎。如果不能使迦毗罗卫国富兵强，屹立于强国之林；那么出家修道，成为国际知名的学者，亦可间接维护国家的安全。观诸太子成道后，以舍卫城为其弘法据点，与波斯匿王维持良好的友谊，事实上就是保护了他的国家。

** 五、菩提树下，证悟真理

佛陀出家时代的所谓'出家'，是离开家庭，住于森林，或参访师友，切磋学问； 或寂默冥想，参究真理。并不是后来的'舍亲割爱，剃度出家'。

太子出家之前，他的儿子罗侯罗已经出生。罗侯罗Rahula，在梵语中是日蚀或月蚀-​-日月上有覆障的意思。太子以为儿子是出家的障碍，所以命名罗侯罗。

太子离开迦毗罗卫，初到一苦行林中访一跋伽仙人，跋伽所领导的沙门集团，是修苦行的。太子居留数日，与跋伽反覆讨论，认为苦行不是究竟解脱之道。乃辞别跋伽仙人，南下摩揭陀国，去访师学道。

太子出家的时侯，恒河中游的国际形势已有了极大的变化。这时恒河南北岸两大强国对峙，恒河南岸的是摩揭陀国，北岸是拘萨罗国。此外还有跋蹉国、阿槃提国也是较强大的独立国，以及许多城邦式的小国，多数是附庸国。拘萨罗的国都舍卫城、摩揭陀的国都王舍城，是南北两大政治文化中心。舍卫城在伽毗罗卫之西，距离不到一百公里。而摩揭陀国在恒河之南，距离四百余公里。太子何以舍近求远，不到舍卫城，而南下王舍城呢？ 也许，拘萨罗是迦毗罗卫的宗主国，他以王储的身份，有所不便吧！

太子到王舍城，暂在郊外灵鹫山栖止，摩揭摩国的频婆娑罗王获悉他的身份，到山中相访，要推国相让。太子怕节外生枝，立即离开灵鹫山，到各处参访-​-本来，'志士入山恐不深，人知已是负初心'，太子出家，为的是解决生老病死忧悲苦恼的问题，如欲为王，自已本来就是王储，又何必出家呢？

许多经典上说：'太子出家，六年苦行'，可能不是如此。在前一段时间，他必是到各地访问各宗派的沙门集团，去了解他们的哲学理论。他也曾从数论派的先驱、阿逻逻伽罗摩、和郁陀伽罗摩等修习禅定。最后他到王舍城西南方、伽耶山附近的尼连禅河畔的树林中修苦行。

本来，婆罗门教就有修苦行的方式，而沙门集团出现后，又有了多种的'苦行外道'-​-如自饿、投渊、赴火、自坐、禁语、持牛戒狗戒等等。不过广义的说，在林中沉思冥想、参究真理也就是修苦行。我相信太子修的苦行是属于后者，而不是外道的苦行。

太子在苦行林中，参究真理-​-组织他自己的思想体系。最后，他坐在菩提树下，作思想上最后的突破。据说，魔王波旬此际曾来威胁利诱，横加干扰。并要他的三个女儿染欲、悦人、可爱乐以美色诱惑太子。太子在金刚座上。战胜魔军。其实所谓魔(梵文Mara，本译为磨，后来梁武帝改磨为魔)，不是来于外境，而是生自内心。这是我人内心深处的种种欲念-​-爱欲、贪婪、权力、财富等种种欲念的化装表现而已。

太子在菩提树下，苦心参究，终于在某一日淩晨，面对满天繁星，思想豁然贯通，证悟了真理。这在佛经上称为'睹明星而证道'。

太子成道了，自此成为佛陀Buddha-​-觉者。就是真理的证悟者。

*  第四讲　僧伽-​-僧团的成立与发展

** 一、初转法錀

据 《过去现在因果经》　上说，悉达多太子，在尼连禅河畔菩提树下，入定思维：'第三夜分，破于无明，明星出时，得智慧光，断于习障，成一切种智。'成为证悟真理的觉者-​-佛陀。

佛陀证道后，并没有立即离开菩提树他往，仍在原处禅定思维，他反覆思维自证的境界，自己受用法乐。同时思考，为未来行止颇为踌躇：究竟是深入人间，去宣扬真理，普度众生呢？ 还是明哲保身，独处山林，自享法乐呢？ 反覆思维的结果，终于决定还是深入人群，度化众生。《过去现在因果经》中，说是受了大梵天王的启请，佛陀答大梵天王释提桓因曰：'我亦欲为一切众生转于法錀，但所得法，微妙甚深，难解难知，诸众生等不能信受，生诽谤心，堕于地狱，我今为此故默然耳。'

佛陀所悟之法，微妙甚深，难知难解，恐众生不能信受，固然是使其踌躇的原因之一，另一方面，当时的客观环境，可能也是佛陀考虑的因素。佛陀悟道时，印度社会是一个思想混乱，邪说充斥的时代。传统的婆罗门教，祭司们藉著主持祭祀，解释经典的权力，勒索财物，欺压百姓。虽然如此，但它根深蒂固，不可动摇(后来佛陀传教，始终没有进入婆罗门教的根据地-​-阎牟那河地区，由此可见一斑)。

而新的沙门集团，所谓六师外道、九十六外道、三百六十三论师等等，虽然各创新说，但有的否定业报因果，有的一切归于宿命，邪说谬论，不一而足。但也各有其信徒和群众，也各有其地盘和势力范围-​-后来僧伽一直和外道斗争，须达多长者在舍卫城建祗园精舍时，曾为外道所阻止；大目健连晚年出外传道，为外道乱石砸死；甚至于外道买通淫女，'带盂谤佛' ，可见斗争激烈的一斑。观乎此，佛陀最初的踌躇就不为无因了。

不过最后他还是决定了入世度化。最初度化的物件，是他在苦行林中修道时，净饭王派去照应他生活的五名侍者。五侍者后来见太子接受农家女奉献的乳糜，以为太子退转道心，就离他而去。五人此时在恒河北岸、波罗奈国的鹿野苑修苦行。波罗奈距佛陀证道的伽耶山，有近三百公里的路程，佛陀赤足徒步，由伽耶走到鹿野苑。

所谓五侍者，是以年长的乔陈如为首，另外四人的名字是摩诃那摩、跋波、阿舍婆阇、跋陀罗阇。这五个人原是净饭王宫中的执事人员，都信婆罗门教。佛陀为他们讲解以'缘起'为基础的具体理论'四圣谛'-​-苦、集、灭、道四圣谛。由于这是佛陀初次传道，佛经上称此为'初转法论'。又因佛陀对五人以不同的角度讲解了三遍，佛经上称之为'三转法论'。佛陀还为他们讲解'中道'-​-既反对任情纵欲，也避免极端苦行，行于'中道'，才是正确的解脱方式，他们五人皈依了佛陀，成为僧伽中最初的五名比丘-​-关于四圣谛，后文再详为介绍。

这一年，佛陀在鹿野苑度过了雨安居。在此期间，还有一段插曲。伽尸城有一位'大富长者'俱梨迦，他的独子耶舍，生于富家，终日酒食征逐，在女人堆里打滚。他家中蓄有歌妓，一日饮酒作乐，醉后沉睡，夜半醒来，见那些歌妓在枕席间横七竖八沉睡。脂粉零落，口涎直流，使他有如置身死人堆中的感觉。他一阵憎厌，披衣而起，一口气跑到城外，口中喊著'烦死了、烦死了'。本来，财色名食睡的五欲之乐，可以使一个人麻醉、堕落，但填补不了一个人心灵上的空虚。

耶舍就是这样，他跑到城外，无巧不巧的正跑到鹿野苑，遇到了正在'经行' 的佛陀。佛陀见一青年，衣衫不整，急步奔走，不停的喊著'烦死了、烦死了'就拦住他一问究竟，问明原委后，说：

'青年人，这儿有安静处，寂灭会脱雏烦恼'。

于是领他到房内，为他讲解苦集灭道四圣谛的道理。耶舍原本是天分颇高的青年，只是无人领他走入正途，他听了佛陀的正法，逐渐觉悟，当下皈依于佛陀座下，出家修道，后来，耶舍的五十多名亲友，都随佛陀出家，成为继五比丘后的一群出家弟子。后来耶舍的父母也皈依了佛陀，因为年迈不能出家，乃做了在家的优婆塞和优婆夷。

** 二、僧伽-​-早期的佛教

佛陀初转法錀，五侍者皈依，成为最初的五名比丘，据佛经上说至此三宝齐备，'佛教'由此诞生。三宝者，佛、法、僧。佛、是释迦牟尼佛陀； 法、是四圣谛； 僧、是五比丘。不过，由五名比丘到初具僧伽规模，应该是三伽叶皈依以后的事。

佛陀在鹿野苑度雨安居时，想到摩揭陀国伽耶山附近的优娄频罗村，住有一个婆罗门种姓的事火外道，名叫优娄频罗伽叶。他座下有五百名弟子，他有两个兄弟，座下也各有二百五十名弟子。这三兄弟是摩揭陀国的有名的宗教家，甚为摩揭陀国人所敬重。如果把这三兄弟度化过来，则有助于教团的发展。雨安居过后，佛陀向座下的五十多位弟子说：

比丘们呀！我脱离了人天世界所有的芥蒂，你们也脱离了人天世界的所有芥蒂，而得到解脱。该是游行(传道)的时侯了，为了人们的利益和幸福，为了人天的利益和幸福，一条路不必走两个人。比丘们呀！无论开头也好，中间也好，末了也好，都好好讲说具备理路和表现的说法。而且，要说圆满和清净的梵行。众人之中，也少有染污尘者，如果不能听到法，将要堕落。比丘们呀！为了说法，我也到优娄频罗村去吧。

这一段话，可以说是初期僧伽的传教宣言。

最初的僧伽，和外道的不同之处，就是教团成立之初，即深入社会群众中，积极的展开了传教活动。这是佛教以后能超越国界，成为世界三大宗教原因之一。因为当时的婆罗门教是国教，除了首陀罗的奴隶族外，是全国上下一致的信仰。六师外道等其他沙门集团，都是为了自身解脱而出家修道的，弟子投靠到师父座下，师父才予以传授，并不向外传道。所以深入群众从事教化，是僧伽的特色。'一条路不必走两个人'，是为了扩大影响，使更多的人能够听到正法。

佛陀又托钵徒步行走了两百多公里，到了他修苦行的伽耶。他以借宿为名，住入了老伽叶-​-年已一百二十岁的优娄频罗迦叶的圣火堂中，以神通力降服了圣火堂中的毒龙，老迦叶敬服万分，带著五百名弟子皈依于佛陀座下。他的两个弟弟都提迦叶和伽耶迦叶，也各带两百五十人皈依佛陀。这是构成僧伽的基本成员。后来在王舍城时，舍利弗和大目健连也各带了百名弟子皈依佛陀，再加上鹿野苑的五十多名弟子，就是佛经中所说的：'一时，佛在某某国某某园，与大比丘僧，千二百五十人具'。

本节中屡屡提到'僧伽' 二字，这僧伽二字究作何解？

僧伽，是梵文 Sangha　的音译，亦有译为僧□，僧企耶。义译为众和会、和合众，含有群众的意义。僧伽一词，在佛教兴起以前，印度社会早已流行使用。原来恒河中游，在西元前五、六世纪，随著农业和手工业的发达，连带著运输、销售业也发达起来。这就兴起了许多以工商业为主的新都市。像恒河北的迦尸，就是有名的工商业城市。恒河南岸的巴吒理村，最初只是一个渡口，后来也发展成为水陆要冲的都市-​-华氏城。

由于工商业发达，工商界人士依其职业性质组成不同的职业团体-​-有如现代的同业公会，这种职业团体，称做僧伽。甚至于当时毗舍离城人民所有的政治团体-​-会议政治的体制，也称做僧伽。这种社会通用的名词，后来也为宗教团体所采用。如当时各外道的沙门集团，也称为僧伽。佛陀的教团，由五名比丘开始，随著人数的成长，也成了僧伽。

佛教传入中国后，僧伽二字，成为佛教出家众专用的名词。

** 三、象头山的开示

三迦叶的皈依，是早期僧伽的大事，有了上千名修道者加入教团，奠定了教团的基础。但是，上千名比丘，不能在伽耶附近的聚落托钵乞食，必须到人口众多的城市中才能生存。佛陀初出家时，在灵鹫山和频婆娑罗王相遇，频王曾有'他日道成，愿先见度'之约，佛陀决定带著众比丘到王舍城去。　

佛陀带著众比丘首途，一行人登上伽耶山-​-伽耶山，又名象头山。时近黄昏，晚霞灿烂，佛陀游目四顾，这里有他许多回忆。东北山麓是伽耶的街市，东边有尼连禅河在山下迂缓的流过，远处，有著他证道之地的菩提树..这时，山下有野火在燃烧，火光熊熊，辉耀夺目。佛陀即以燃火为喻，对众比丘开示说：

比丘们呀！万物皆在燃烧，且烧的很炽烈，你们必须知道这个事实。\\
比丘们呀！万物皆在燃烧有何种意义呢？比丘们呀！人们的眼睛不是正在燃烧吗？\\
不是在对它的物件燃烧吗？\\
人们的耳朵不是正在燃烧吗？人们的鼻子不也是正在燃烧吗？\\
舌头不也正在燃烧吗？ 心又何尝不是正在燃烧？\\
所有的都对他的物件，炽烈的燃烧著。\\
比丘们呀！　这些何以会燃烧？\\
那是为贪欲的火焰所燃烧，为嗔恚的火焰所燃烧，为愚痴的火焰所燃烧。\\

火焰在燃烧，事实上是我们的心识在燃烧，我人内心的贪婪之火，嗔恚之火，愚痴之火，种种的烦恼之火，较原野上的火燃烧的更炽烈。因此，我们所有的感受、知觉、意念、认识，都是燥热的火种。我们时时刻刻、都受著这些烦恼之火的熬煎。

贪婪、嗔恚、愚痴，是我人心头上的三把毒火，我们必须熄灭了心头上这些烦恼的火焰，才能解脱得到寂静与清凉。佛教中的'涅槃'，就是由此万物皆在燃烧的思想中产生的。

据说，千名比丘听了佛陀'万物皆在燃烧'的开示后，皆开悟而证得须陀洹果。

后来西洋人研究佛教，把这一段象头山的开示，比之为耶稣的登山宝训。

** 四、恒河南北的两大教区

佛陀带著千名弟子，步行走向王舍城，到得城郊，在一处地名杖林的地方停下来。这时摩揭陀国的频婆娑罗王，已经获知沙门瞿昙证了道果，带著弟子到了杖林，他以最隆重的礼节迎接佛陀，据说王舍城的人倾城而出，都要瞻仰一下这位证果的圣者。频王把佛陀迎入宫中，以最丰美的饮食供应佛陀和千名比丘，佛陀也于食后对频王说法-​-说施论、戒论、生天论的三论；和苦、集、灭、道的四圣谛。频王皈依于佛陀，他对佛陀行最尊敬的跪拜接足礼。这以后，凡是皈依佛陀的国王大臣，都行这种最敬礼。频王皈依后，感激而又愉快的说：

当我还是太子的时侯，我有五个心愿，今日得以全部成就了。第一就是愿自己能够灌顶为王，这已经得以成就了；
第二是愿圣者来到我国，也已经得以成就了；
第三愿自已能够师事圣者，已经得以成就了；
第四愿圣者能够为我说法，也已经得以成就了；
第五愿我能够领悟圣者所说的法，今日也得以成就了。我的五个心愿，因佛陀而得以全部成就，佛陀啊，接受我的供养，居留在摩揭陀吧！

频婆娑罗王在王舍城的东南郊，一处名叫迦兰陀竹园的地方，为佛陀起造了精舍，请佛陀和千名比丘居住，这就是后来佛经上所称的'竹林精舍'。 -​-于此要把'精舍' 二字加以说明，说到精舍，使我们误以为是精美的房舍。其实不是，精舍的正确意义，是：'精舍者，为精行者之所居，非精妙之谓也。' 其重点在行者精进，不在房舍之华美。

当时的沙门集团，平时在树林中修行，一到雨季，便各行其适，雨季过后再回到林中。雨季时在精舍中集中修行，是僧团的创举。由于这一座竹林精舍，使僧团在王舍城扎了根，这对僧团以后的发展是一件非常重要的事。果然，沙门瞿昙的僧伽，很快的在大王舍城地区发展起来，连六师外道之一的删阇耶吠罗胝子，他座下的大弟子舍利弗和大目犍连，也都带著两百名弟子皈依了佛陀，有名的学者摩诃俱希罗，大伽叶，也投入佛陀座下，至于民间青年子弟之投入僧伽的，更是不计其数。甚至于一度为王舍城造成恐惶不安-​-许多做父母的、以为沙门瞿昙夺走了他们的儿子，做妻子的以为沙门瞿昙夺去了他们的丈夫，满城议论纷纷。《四分律》三三中载有一首当时流行的偈子，语译后的意思是：

在摩揭陀国众山环绕的都城里，

出现了一个名叫瞿昙的大沙门，

他先引诱了删阇耶的二百徒众，

以后还要引诱那些人家的子弟呢？

当然，这只是一阵风潮，风潮过去也就平静了。

大约是佛陀成道两三年以后的事，拘萨罗国舍卫城有一位须达多长者，到王舍城探望他的老友迦兰陀长者，由伽兰陀长者的引见，他在竹林精舍拜谒了佛陀。他在佛陀庄严慈悲的威仪下，为佛陀开示的教法所感动。他当时向佛陀表达出他的心愿，他希望在舍卫城也建造一座精舍，请求佛陀带著弟子们去度化，使舍卫城的人也能沾到佛陀的法益。佛陀慈悲接受，须达多长者满心欢喜的回到舍城去筹建精舍。

须达多，乐善好施，人称给孤独长者，'祗树给孤独园'的故事尽人皆知，不再赘述。不过大家所未注意到的，精舍建造之初，须达多请佛陀派一位弟子去监造，佛陀派了舍利弗前去。开工不久，当地的外道、探知是为释迦族的沙门瞿昙所造，大为不平，许多外道去游说须达多长者，要求中止这项工程。须达多不为所动，外道提出一个要求，他们要与瞿昙的弟子开一次辩论会。须达多长者颇为担心，而舍利弗却一口答应下来。原来舍利弗出身外道，辩才无碍，在佛弟子中号称智慧第一，在辩论会上他折服众外道，工程得以继续进行。

据说在佛陀证道的第五年，佛陀带著弟子游化拘萨罗国，住进舍卫城的祗园精舍。这以后，佛陀在恒河南北各有一处弘法据点，他经常率领弟子往返南北，到各地游行教化。

** 五、戒律的制定

僧团成立之初，尚没有律的制定。佛陀也为皈依者说戒，说的是基本五戒。基本五戒并非僧团所独有，像尼乾陀若提子领导的耆那教，也有五戒的制定。耆那教的五戒是不杀生、真实语、不盗、不淫、无所有。无所有，是指不持有财物。僧团的五戒前四者相同，而第五戒是不饮酒。不淫一戒，对在家弟子说，改为'不邪淫'。

据说，住进竹园精舍精舍未久，舍利弗曾要求佛陀制定戒律，以为团体的规范。佛陀说：

舍利弗，我此众中，未曾有法；
我此众中，最小得须陀洹果。诸佛如来，不以未有漏法而为弟子结戒。

佛陀的意思是： 在弟子们没有犯过失以前，如果先订出一套限制别人行为的戒律来，是对弟子们人格的不信任和不尊重。不过，上千人聚居居一处，也总应有一套生活公约似的东西。这生活公约可能就是'六和敬'。如旧译本的《仁王经》称：

住在佛家修六和敬，所谓三业，同戒、同见、同学。

《祖庭事苑》曰：

六者是何，一身和、共住；二口和、无诤； 三意和、同事； 四戒和、同修；五见和、同解； 六利和、同均。 戒、律的制定，大约在僧团成立三四年以后，佛陀游化跋祗国，在毗舍利结夏，是年灾旱，弟子们分散到各地就食。其中一个名叫须提那的比丘，家住毗舍利伽兰陀村，他回到家中，禁不住妻子的挑逗，破了戒体。事后深为奥悔，回到毗舍离向佛陀忏悔。佛陀为僧团前途著想，感到有制定戒律的必要，于是开始制定戒律-​-当然，戒律不是一次完成的，是遇到问题发生，由佛陀加以处理，这就成了一个案例。如此一件一件累积而成的。

本文中刚才说到'结夏'，结夏就是'雨安居'。这并不自僧团开始，是印度传统的习俗。印度夏季多雨，外出不便，在森林中修行的婆罗门或沙门，雨季也要离开森林，各　自所适。而僧团中的比丘，平时在外乞食、传道，到雨季来临时要结夏安居。不过与外道不同的，雨季并不分散，而是集中在精舍中精进修行。雨安居的期间，视雨季来临的早晚，而有前安居和后安居之分。前安居是自四月十六到七月十五； 后安居是自五月十六到八月十五。

僧团中有'自恣'的制度。每年夏安居期满的次日晚间，比丘齐集一堂，检讨各人在三个月结夏期间，在言行上有没有违反戒律。各人自行反省，也可以互指别人过失，若有反戒者，要当众忏悔。《增一阿含》上载有'佛自乞僧举过
'，说是佛陀在自恣日的会堂中对众比丘说：'我有没有过失呢？ 我有没有反身口意三业呢？如果有的话，你们可以举出来，以便我反省忏悔。'

僧团中还有'布萨'之制。布萨，梵文Uposatha，义为净住、善宿、长养。其实就是每半个月一次的定期集会。时间在每月初一和十五，即太阴历新月之夜和满月之夜，在一定的区域内，出家众都要参加。由比丘轮流诵出波罗提木叉-​-戒律。参加的比丘要各自反省，在这半个月内有没有反戒，没有反戒者可保持沉默，反戒者要在大众前坦白出来，表示忏悔。

*  第五讲　佛陀证悟的真理-​-缘起

** 一、诸法因缘生

原始佛教的基本教理，有受印度传统思想影响的-​-与外道共通的部分，有不与外道共通，而为其本身所特有者。因为一种宗教，或一种思想、学说，不能自外于历史传统或时代背景之外。伟大如释迦牟尼，虽然特立独证悟真理，开创印度思想界的新时代，但他仍不能与他所处的时背景脱节。所以佛教的教理，有受时代背景所影响者，有从俗容摄而加以改者，亦有不与外道相通，而为佛陀所自创的。

原始佛教的独特思想，即是佛陀在菩提树下证悟的真理：'缘起'。于此，先讲一个舍利弗皈依佛陀的故事，这个故事载在《佛说初分经》中。

舍利弗是摩揭陀国王舍城人，家住迦罗臂拿迦村，婆罗门种姓，出生于一个学术气氛浓厚的家庭。他的父亲提舍，是当代有名的论师；
他的母亲舍利也是知名的学者。他自幼受传统教育，诵四吠陀及五明之学，成年之后，辞别父母，出外访师学道。后来投入六师外道之一、删阇耶吠罗底子门下。删阇耶是一位怀疑论者，对于思想界争论的重大问题，如空间有无极限，时间有无始终，如来死后存不存在等形而上的问题，既不承认也不否认，对一切持怀疑态度。这种理论当然不能使舍利弗感到满足，他时有另投明师的打算，他和同学目犍连相约；如遇明师，要彼此相告。

一日，佛陀弟子乌斯西那比丘，著衣持钵，入王舍城乞食。那乌斯西那威仪整肃，诸　根调寂。这时舍利弗也在途中，他见乌斯西那威仪殊胜，叹未曾有。心中颇为欣慕，乃上前问讯曰　：'何以法像衣服与众不同，宁有师宗，可得闻乎？
'

乌斯西那答道：'我师是大沙门瞿昙，于大众中，宣说无上广大囧琺门。'

舍利弗曰：'汝今可能于彼法门，若多若少，为我宣说？'

乌斯西那答：'我年幼稚，受学日浅，尚不能领会我师妙法深义。'

舍利弗再请曰：'慈悲方便，略说一二。'

乌斯西那曰：'我师所说，缘生法者，谓一切法从因缘生，从因缘灭，复以是义，说伽陀
(偈) 曰： 诸法因缘生，法亦因缘灭，是生灭因缘，佛大沙门说。

经上说：'舍利弗闻是法已，远离尘垢，得法眼净。'
-​-法眼净，是能观察真理的清净法眼。舍利弗欢喜不已，辞别乌斯西那，回去找到目犍连，说明经过，二人同时皈依于佛陀座下。何以舍利弗听了乌斯西那四句偈子，就舍去自己多年所学，投入佛陀门下呢？实是因为'若法因缘生，法亦因缘灭'二句，是宇宙人生的真理。舍利弗修道多年，心中不能解释的疑团，都由此得到答案。得到了什么答案，我们且看下文。

** 二、缘生与缘起

佛陀青年时期，因感于生、老、病、死的烦恼而出家修道。所以他证悟的真理-​-缘起，也是纯就人生的生死流转的观点立言。在
《过去现在因果经》
中，记载著佛陀在尼连禅河畔的菩提树下，证悟缘起的经过。经中称：

尔时菩萨，至第三夜，观众生性，以何因缘，而有老死，即知老死，以生为本；
若离于生，则无老死。又复此生，不从天生，不从自生，非无缘生，从因缘生..

这'从因缘生'
一语，就是'缘起'立论的由来。不过最初的缘起，只限于有情生死流转的'内缘起'，后来才扩及于万法生住异灭的'外缘起'。

内缘起，即是生命流转的缘起-​-十二缘生观，此留待以后再讲，现在先就'缘生'与'缘起'
这两个名词加以探讨。

缘生就是缘起，这是略称，具足又称'因缘生'或'因缘起'
。《良贲疏》曰：'言缘生者，缘为众缘，生者起也，诸有为法，皆从缘生'。大致说来，缘生就是缘起。至于具足所称的因缘生，因是'造'　义，也是'亲生'
义。 《大毗婆沙论》 曰：'造是因义'，《大乘义章》 曰：'亲生义，目之为因'
，这是说，以因而能致果，因是能生，果是所生。于此，也把缘生和缘起加以区别。
《瑜伽师地论》 五十六曰：'因名缘起，果名缘生'。印顺导师于 《佛学概论》
一书中，对这两个名词作了更明白的解释：

缘起是动词，缘生是被动词的过去格，即被生而已生的。所以缘起解说为
'为缘能起'；
缘生可解说为'缘所已生'，这二者有因果的关系。但不单是事象的因果，佛说缘起时，加了'法性，法住，法界安住'的形容词。所以缘起是必然理则；缘生是因果中的具体事象。

现实所知的一切法，是缘生法；这缘生法中所有必然的因果理则，才是缘起法。缘起与缘生，即理与事，缘生说明了果从因生；
对缘生而说缘起，说明了缘生事相所以因果相生，秩序不乱的必然理则，缘生即依于缘起而成。

明白了缘生与缘起的差别，我们再来探讨缘起的意义。

缘起 Pratityasamutpady，梵文的意思是
'由彼此关涉而生起'、或是'现象界的生命与世间彼此关涉所由之道
'。也就是说：
现象界中，没有孤立存在的事物，都是彼此关涉、对待而生起、存在的。所以原始经典(　如杂阿含二九三、及二九七经等
)上屡说：

此有故彼有，此生故彼生。

此无故彼无，此灭故彼灭。

这种关涉、对待之间的依存关系有两种，一种是同时的依存关系，一种是异时的依存关系。异时的依存关系，即所谓'此生故彼生'，此为因而彼为果。同时的依存关系，即所谓'此有故彼有'，此为主而彼为从。而此因果主从，也不是绝对的，换一个观点来看，因果主从又可以倒置过来。所以经中说：

佛说：
譬如有两根束芦，互相依倚才能植立。朋友们，缘名色而有识，缘识而有名色。此生则彼生，此灭则彼灭，正复如此。朋友们，两根束芦，拿去这根，那根便竖不起来；拿去那根，这根也竖不起来。名色灭则识减，识减则名色灭，正复如此。

束芦，是印度出产的一种植物，中国以乎没有。识、名色，留待后文再解释。我们主要探讨这种关涉、对待、依存的关系。所以，缘起的缘，就是事物生起存在的各种条件。再者，宇宙万象，没有孤立存在的事物，也没有永恒不变的事物。这些关涉和变化，必须在一定的条件下才能生起、存在、变异、坏灭。因此，所谓'诸法因缘生，法亦因缘灭'，因就是主要的条件，缘则是次要的条件。这就是楔经所云：

有因有缘集世间，有因有缘世间集。

有因有缘灭世间，有因有缘世间灭。

离开因缘，就没有所谓宇宙与人生。

** 三、内缘起与外缘起

缘起，是佛陀以有情生死流转的立场所证悟的真理，所以杂阿含(二九八经)称：

尔时，世尊告诸比丘：　我今当说缘起法，法说、义说。谛听，善思，当为汝说。云何缘起法法说？
谓此有故彼有，此起故彼起，为缘无名行，乃至纯大苦聚..

这种有情生死流转的缘起，具足的说，就是
'缘无明行，缘行识，缘识名色，缘名色入，缘六入处触，缘触受，缘受爱，缘爱取，缘取有，缘有生，缘生老死、忧悲恼苦，如是如是纯大苦聚集..'的十二有支流转。后来，由有情生死流转的缘起，扩及于万法生灭变异的缘起，而把前者称'内缘起'；
后者称为'外缘起'。如后来的大乘经典　《入楞伽经》 称：

佛言：
大慧，一切法因缘生有二种，谓内及外。外者谓以泥团、水、杖、轮、绳、人工等缘合成瓶，如泥钵，缕垒、草席、种芽、酪苏、悉亦如是，各外缘前后转生；内者谓无明、爱、业等生蕴、界、处法，是谓内缘起，此但愚夫之所分别。

经文中的内缘起，是指生命流转的缘起；外缘起，是指物质变化的缘起。关于内缘起，留待后面再说，兹先探讨外缘起。所谓外缘起，是指世间一切物质现象的生起
(当然也包括著变异和坏灭)
。前面说过，宇宙万有，没有永恒不变的事物，也没有孤立存在事物。一切都是仗因托缘，互相关涉对待而生起存在。好像我们以泥土与水加以调和，再加以木杖、轮子等工具，就可以做出泥罐、泥钵等陶器来；我们用纱缕织成布，用草编成席子，也都要加上工具，人工等相关的的条件。更具体的说：我们有了或瓜或豆的种子，但种子只是因缘的条件之一，必须把种子埋在土壤中，再加上阳光、雨露、人工等助缘，种子才能萌芽生长。当然，如果我们再除去杂草，施以肥料，种子萌出的芽会生长的更茁壮。所以种子生出豆苗瓜蔓，决不是种子单一的条件，要依赖其他许多相关的条件。这许多相关因素而生起存在的事物，就叫做
'因缘生'；
而许多因素条件生起事物的必然理则，就是'因缘起'-​-简称缘起。

许多因素条件生起的事物，有时间上与空间上两种相对待的关系。自时间先后来说，就有了因果关系；
自空间相待来说，就成了依存关系。譬如一棵大树，自时间上说，先前的种子为因，而有现在大树的果；
自空间上说，大树要依赖土地而生长，土地要依赖周围的土地来支援，周围的土地要依赖更周围的土地来支援。反过来说，土地固然支援了大树，大树的根也保护了土地，这就成了关涉对待的依存关系。所以，广义的缘起，任何事物的生起、存在、变异、坏灭，其依存与因果的关系，可说是横遍十方，纵贯三世。

** 四、缘起与实相

缘起，有其纵向的和横向的两种关涉对待关系。自纵向关系来观察事物，就有了前因后果的关系；自横向关系-​-就时间的某一点上来观察事物，就有了彼此对待的关系。'此生故彼生'是纵向的因果关系； '此有故彼有'是横向的对待关系。后世发展的佛教，莫不重视缘起，以缘起为佛教的基本教理。但较多重视纵向的因果关系缘起，而忽略横向相待关系缘起。后来这种横向关涉对待的缘起被称为
'实相'Dharmata。实相，即一切事物真实的、常住不变的本性。这是平等的、最高的真理。

事实上，缘起的本义，就是探究实相。龙树菩萨出世，鉴于小乘有部之说诸法实有，而揭示出
'空'的概念。即'三是偈'所称： '因缘所生法，我说即是空'。空就是诸法实相。因为宇宙之间，没有永恒不变的事物，即凡是由因素条件集合而生起的存在，都具有成、住、异、灭四相，缘集则成，缘散则灭，此即是无常；而凡是因素条件集合生起的存在，都没有独立的自性
(定性)
，不能决定自己的存在，此即是无我。换一个方式来说，由众多关涉条件生起的事物，其本身并没有一个固定的主体，所以
'无我'；
在关涉条件发生变化的时侯，此一法就会变异或坏灭，所以'无常'。而此无常无我的本性是空-​-即是性空或空性。而缘起法中即含蕴著空性，所以说
'缘起性空'。

实相-​-此一切事物真实的、常住不变的本性，也就是真如。即是说，自缘起法来说，一切法都是待缘而生起，故无自性　(也即是无固定不变之性)
，无自性即是性空，这是诸法的本质，是本来如此的、不增不减的法性，这就是真如。

《中论疏》　曰：'缘起者，体性可起，待缘而起。'所谓'体性可起'
，是指真如法性中、法尔具足染净二法之因，在因缘具备的条件下即可生起；所谓'待缘而起'
，是指因缘具足，方能生起诸法，有因无缘、有缘无因，均不能生起。若详细一点说，一法之生起，力强者为因，是必不可缺的条件；力弱者为缘，是或有的条件，但一法的生起，必视缘具缘不具。因此，诸法生起称缘起而不称因起。

实相、真如、即是法性-​-缘起法之实性。于此，我们对此法'字加以探讨。

在佛经中，法之一字，有种种界说。自宽泛处说，法指宇宙万有，所谓
'宇宙万法'，'蕴、处一、界
'诸法，'五位七十五法'。如果说到佛陀的言教-​-教法，则仅指佛陀说的法，即指经典而言。如果说到缘起法，则法即代表真理。中阿含　《象喻迹经》：'若见缘起便见法，若见法便见缘起'。
《稻芊经》
曰： '见缘起则见法，见法则见佛'。由此可见，缘起、即是实相，即是真如，即是法性，即是永恒的真理-​-佛陀的法身。

** 五、见缘起则见法

缘起，是佛陀在菩提树下，观察有情生死流转，'非无缘生，从因缘生'，以此所证悟的永恒真理。这是人生与世间必然的理则，不是佛陀之所创造或制定，所以阿含经中说：
'非佛自作，亦非余人作'。杂阿含二九六经
上说：'若佛出世，若未出世，此法常住，法住法界。'

而当时印度的思想界，却有种种不同的论调。佛陀曾将当时婆罗门教及沙门集团、种种的错误主张，归结为下面数种：

'一'，神意论：　这是婆罗门教的主张。人的命运和吉凶祸福，以至于世间万有，全是最高神所创造。人为神所创造，人的意志也为神的意志所左右，人根本没有自由意志，所以人只要恭谨如仪的祭祀便可达到解脱。其他种种为解脱烦恼所作的努力与修行、全是徒然的。人既然没有自由意志，人对自已的善恶行为便没有责任可言。

'二'，宿作因论：　此说认为：
我人今生的吉凶祸福，全是前世所作所为的结果；
今世的穷达寿夭，于出生之时即已决定。今世的善恶行为，可以影响来生的命运，但不能改变今生的命运，其实这就是宿命论。

'三'，结因论：　这可以说是另一种宿命论。此说认为：
世界和人生，是由地、水、火、风、苦、乐、灵魂等元素结合而成，由其结合状态的良窳，以决定其一生的命运。所以人的命运，在出生即决定，人的一切努力，终归徒然。

'四'，无因论：　无因论即是偶然论，此说认为：
人生的命运，并不是神力所主宰，也不是善恶业报所支配，一切皆出之于偶然。不然，社会上何以有为恶者享乐，为善者却受苦的事情呢？由此可见吉凶祸福并无一定原则，全出于偶然罢了。

以上种种邪说，就是当时流行的思想。否定因果，否定善恶，否定个人努力和意志。果然如此，人生还有什么目标和希望？
而缘起法，认为宇宙人生间的一切，横向的有互相对待的关涉条件，竖向的有理事相应的前因后果。肯定个人的努力，肯定善恶与业报，这样，才予人间以光明，予人生以希望。

我们在此说缘生，说缘起，实在全是戏论。佛陀说　：'缘起甚深'。缘起法，是'甚深最甚深，微细最微细，难通达极难通达'之法。我们对缘起法的了解，只不过沧海中一滴飞沫而已。

*  第六讲　生命流转的连锁环-​-十二缘生观

** 一、非无缘生，从因缘生

佛陀青年时代，以人生生老病死的烦恼，而舍亲割爱，出家修道，经过六年苦行，在菩提树下证悟真理-​-缘起。佛陀当时所证悟的缘起，是以人生论的观点，探索生命流转的缘起，这在《过去现在因果经》中，有非常详尽的记述，上一讲已略为提及，于此则录其全文，以窥生命的奥秘。经文曰：

尔时菩萨，观众生性，以何因缘，而有老死，即知老死，以生为本；若离于生，则无老死。又复此生，不从天生，不从自生，非无缘生，从因缘生；
因于欲有色有无色有业生。

又观三有业从何而生？
即知三有业从四取生。又观四取从何而生？即知四取从爱而生。又复观爱从何而生？
即便知爱从受而生。又复观受从何而生，即便知受从触而生。又复观触从何而生？
即便知触从六入生。又观六入从何而生？即知六入从名色生。又观名色从何而生？
即知名色从识而生。又复观识从何而生？
即便知识从行而生。又复观行从何而生？ 即便知行从无明生。

若灭无明则行灭，行灭则识灭，识灭则名色灭，名色灭则六入灭，六入灭则触灭，触灭则受灭，受灭则爱灭，爱灭则取灭，取灭则有灭，有灭则生灭，生灭则老死忧悲苦恼灭。

如是逆顺，观十二因缘，第三夜分，破于无明，明星出时，得智慧光，断于习障，成一切种智。

上一段经文，是佛陀证悟缘起的经过。于此，有两个名词先加以解释，就是'因于欲有色有无色有业生
'一句中的三有。三有，梵文tri-bhava，bhava
即是有、存在的意思，所以欲有、色有、无色有就是三种存在的领域，此又称为三界，即欲界，色界，无色界。另一句'三有业从四取生
'的四取，取、梵文 upadana 是烦恼的异名，四取即四种取著的烦恼：
欲取-​-贪著于色、声、香、味、触五境；见取-​-于五蕴中妄执我见、边见等而生恶见；戒取-​-是修习非理的戒禁；
我语取-​-是执著自我而起我见、我慢。

于此附带说明：
所谓三界，可能是佛教从俗的承袭婆罗门教天空地的三界说、而加以组织的。与其把它认作是实有世界，毋宁说是精神世界。即欲求杂多的就是欲界，初禅至四禅的禅定状态叫做色界，更寂静精神统一状态就是无色界。后来的部派佛教为了具体的说明业力论，把三界实体化，说成是实有的世界。

十二缘起，有流转缘起和还灭缘起二门。流转门的缘起，在《杂阿含二九三经》中说：

所谓缘无明行，缘行识，缘识名色，缘名色六入，缘六入触，缘触受，缘受爱，缘爱取，缘取有，缘有生，缘生老死、忧悲恼苦、如是如是纯大苦聚。

至于还灭门的缘起，自然就是《过去现在因果经》中所说：

若灭无明则行灭，行灭则识灭..生灭则老死忧悲恼苦灭。

有情生死流转，穷达寿夭，不是神意创造，不是宿命所定，不是偶然而成，不是无因而生，唯是有因有缘，才有人生与世界；
而我人的人生与环境，可以由个人及社会众生的意志和努力，加以改善及净化，肯定杜会道德，肯定个人意志，这就是缘起说不同于其他邪说之处。

** 二、生命流转的连锁环

有情生死流转，从因缘生，此因此缘，有十二个阶段。这在佛经中称为十二因缘，也称为十二有支。由这十二个既念，构成一条生命流转的连锁环。不过这十二有支，是后来发展完成的。在早期经典记载中，有说为五支、九支、十支或十二支，后来固定为十二支，北传的大乘佛教，乃以此为定说。《杂阿含二九八经》中说：

尔时，世尊告诸比丘：我今当说缘起法..谓缘无明行者，彼云何无明..

什么是无明呢？ 兹将以下部分，简化并语译如下：

什么是无明呢？
就是我们不知过去，不知未来，内而不知心识，外而不知环境，不知业报，不知佛、法、僧；
不知苦、集、灭、道，不知善恶罪福，不知学习佛法，不知六根六尘..这就是痴阇，没有智慧，这就叫做无明。

什么叫做行呢？ 行有三种，身行、口行、意行；有行为才有心识。

什么叫做识呢？ 识就是六识身-​-眼、耳、鼻、舌、身、意的六识身。

有识才有名色，名就是四无色阴-​-受、想、行、识四阴，色就是地、水、火、风四大。由四大构成的物质叫做色，色再加上四无色阴叫做名色。

有名色才有六入处，什么叫做六入处呢？
就是六内入处-​-眼入处、耳入处、鼻入处、舌入处、身入处，意入处。

有六入才有触，什么叫做触呢？
触就是六触身-​-眼触身、耳触身、鼻触身、舌触身、身触身、意触身。

有触才有受( 感受　)，什么叫做受呢？
受就是三受-​-苦受、乐受、不苦不乐受。

有受才有爱，什么叫做爱呢？ 爱就是三爱-​-欲爱、色爱、无色爱。

有爱才有取，什么叫做取呢？ 取就是四取-​-欲取、见取、戒取、我取。

有取就有有( 存在　)，什么叫做有呢？ 有就是三有-​-欲有、色有、无色有。

有有就有生( 生命　)，什么叫做生呢？ 生就是在不同类的众生中受生，得阴
(五阴身) ，得界( 十八界 )，得入处( 十二处 )，得命根( 轮回的主体
)，这就叫做生。

有生就有老死，什么叫做老呢？
老就是发白面皱，头垂背偻，呻吟短气，柱杖而行。这就是老； 什么叫做死呢？
死就是不同类的众生，由于时光迁移，身坏寿尽，暖( 体温
)离色身，生命消逝，这就是死。

** 三、在惑、业、苦中旋转的人生

生命的流转，以无明始，以老死终。老死只是一期生命的终止，并不是生命永久的终止，如果永久终止，岂不就是断灭论了？老死只是另一段新生命的开始。生命像是一条连环的锁链，一环扣一环，使有情不得不顺著它周而复始的旋转。《心地观经
》曰：'有情轮回生六道，犹如车轮无始终'，就是形容生命流转的情形。

关于十二缘起，历来各种经典中的解释甚多，《佛说稻芊经》中说：

五情违害名为身苦，意不和适名为心苦，如是等众苦聚集，常在□冥，名为无明；造作诸业名为行，分别诸业名为识；
有所建立，名为名色； 六根开张，名为六入；对缘取尘，故名为触；
受觉苦乐，故名为受； 如渴求饮，故名为爱；能有所取，故名为取；
起造诸业，故名为有； 后阴始起，故名为生； 住世衰变，故名为老；
最后败坏，故名为死。

后人对十二缘起，有各种不同的角度的注解，有以有情的生理过程来注解的，有以和业果轮回观点来注解译，现在综合二说，它的大意是：

'一'，无明： 无明是愚昧，是由烦恼而起的惑。

'二'，行：
行即是业，是在迷惑之下盲目行动造作的后果。这二支，是过去世所造下的业因。

'三'，识： 是轮回的主体，小乘佛教称六识身，大乘佛教发展为第八阿赖耶识。

'四'，名色：'纳识成胎'后，精神的主体和物质相结合-​-即受精卵。

'五'，六入： 受精卵发育成胎儿，六根-​-眼耳鼻舌身意具备。

'六'，触：
婴儿出生后，根、境接触而生认识作用，唯尚无强烈的分别心，只是以无分别的'赤子之心
'来触对外境。

'七'，受：
儿童年龄渐长，有了分别心，这就有了苦乐爱憎的感受。以上五支，是由过去世所造的业因，今生承受的苦果。

'八'，爱：
儿童发育成人，生理成熟，'贪妙资具淫欲现行'-​-就是有了性欲的需要，但对其他方面犹未广为追求。　

'九'，取：
年岁渐长，贪欲增长，由爱而取，周遍驰求，执著不舍。爱与取二支，是今生的迷惑。

'十'，有：
因驰求执取，贪得无厌，这就积集下了引来生之果的业因。这与上爱、取二支合起来，就成了今生所造的业因　

'十一'，生： 以现世的业力，报尽命终之后，复引轮回主体、即业识的受生。

'十二'，老死：　未来受生之后，再循著名色、六入诸支而步向老死。生与老死二支，是未来世所承受的苦果。

照以上所说，无明是前世之惑，行是前世之业，感招来今世的识、名色、六入、触、受五支的苦果。而爱与取是今世之惑，有是今世之业，而感招来世生与老死两种苦果。这样，在惑、业、苦的循环中，就形成了三世两重因果。三世两重因果，出自《俱舍论》，系就惑、业、苦上区分，后来大乘佛教立两世一重因果之说，系就因缘上区分，这都是以后发展出来的理论，此处从略。

** 四、十二有支诠解

本讲对于十二因缘，介绍了阿含经的经文，小乘佛教以因果轮回立论的诠解。在此我们再以现代的观念，对十二因缘重新加以诠解：

'一'，老死：
老死是人生的终结，老死忧悲苦恼，为人生所不可避免的命运。但何以会有老死呢？这是佛陀在菩提树下观察的起点。观察的结果，认为老死是由生而有，因为有生，所以才有老死。因此老死是以生为缘。

'二'，生：
生是人生的开始，但何以会有生呢？诚如经上所说：'非无缘生，从因缘生'。生的因缘虽然不一，但主要的条件是有。此处所说的有，是含有宗教概念的特定含义，即所谓业-​-前生思想行为的总和，即所谓业有。因此，有(　业
)为生之缘。

'三'，有： 自抽象概念言之，有是'存在
'的意思，若无存在，亦没有所谓生。存在又是什么？
存在的就是业。此业是由'取
'-​-对人生和物欲热切的追求，由此造成必得后报的业力。它有如十二支中的'行
'，行是过去善恶行为经验累积的总和，此经验累积且有潜伏力。而有则仅具潜伏力而不包括行为经验-​-此处的善恶行为是'爱
'和'取'，所以取是有的缘。

'四'，取：
取是以爱为缘-​-由爱而生起的追求、执著、选择和舍弃。试看世人对于所喜欢的-​-财富、权势、名誉、地位、以至于女人或男人，攫取它、拥有它。而对于憎厌的，则避之唯恐不及。但爱憎是情绪上的判断，所以是盲目的，其贪爱追求也是错误的。而这种爱憎取舍的行为就形成了业。因此，'爱与取'
，与'无明、行' 二支，有相似之处。

'五'，爱：
爱是取之缘，有些经典中译为渴爱。此处所说的爱，不是佛家的慈悲，也不是基督教博爱，而是由错误观念所衍生的贪爱-​-以生存欲为中心的食色之爱。所以四圣谛中把'苦集圣谛
'归之于渴爱。此渴爱有三种，即欲爱、有爱、无有爱。欲爱特别著重于男女之爱，有爱是对于生存的贪著，无有爱是对存在的灭无、这种灭无状态的爱执-​-以人生苦和无常的不安，而急切想脱离此火宅似的世界，而臻于'无有
'的世界、 (
佛陀住世时，印度下阶层民众-​-如奴隶贱民、对于充满痛苦的生命感到绝望，而追求一个'无有
'的世界。)

'六'，受：
受是身心感受，此感受以触为缘-​-由六根与六境的接触而产生。受在佛经上有三受、五受之说，谓苦、乐、舍三者为前五识(　生理上的
)的感受； 而忧、喜二者为第六识( 心理上的
)的感受。事实上，前五识触外境，仍待五俱意识的了别，所以全是心理上的感受。感受是主观的判断，所以是感情的，而非理智的。由受而有爱与取的生起，可见爱与取的基础是错误的。

'七'，触：
佛经上说，'六入缘触'。六入是眼、耳、鼻、舌、身、意六根，根、境相对而生识，根、境、识三者和合而生触。所以触是由感觉、认知的过程中而生起。然而，'触境系心
'，由于触而生起苦、乐、忧、喜、舍的受，受的下一步就是爱憎取舍、攫取占有了。而触是由六入而起，所以六入是触之缘。

'八'，六入： 经云'识缘名色，名色缘六入
'。名色是肉体与精神的统一，即是有意识活动的生命体-​-人。人之认知与判断，有赖六入-​-眼根、耳根、鼻根、舌根、身根、意根以完成。所以名色与六根，必须同时和合始能完成其工作，是以六入以名色为缘。

'九'，名色：
色是有情的肉体，名是四无色阴-​-受、想、行、识四蕴。其中，识是认知的主体，色、受、想、行是识所认知的对像。而主观的能认识的识，与客观的所认识识的境相对待，始有所谓人生、世界。经云：
'缘名色而有识，缘识而有名色'。而名色之生，是以识为缘。

'十'，识： 识是名色之缘，'识缘名色，名色缘识
'，互相依存。婴胎初凝，在没有完成六根阶段，要有识的执持，才能不坏而增长；
而识也要依托名色，才能发生作用。而此识，指眼耳鼻舌身意六识，六识可分为两部分，前五识是感觉作用，第六识有认知判断等功能。十二缘起中的识，即包括此两部分作用。而此识何以'纳识成胎
'？ 是由过去业力( 行 ) 的引发，所以'行缘识'，识是以行( 业力
)为缘而生的。

'十一'，行：
行是行为，是造作，是身口意三者活动的总和。我人过去的一切活动，各有其经验痕迹留下来(　即所谓薰习
)，建立我人现在的智慧、性格，形成了现在的自我。而现在的活动经验又影响到将来的自我。这种活动经验的累积，在宗教意义上即是所谓'业力
'。而我们世人的活动，是由无明而来，所以才在生命连锁中轮回；若反乎此，由佛陀正法而入于清净之行，就成为离苦得乐之行了。

'十二'，无明：　明、是觉、是智慧。而无明是明之反，是不觉，是愚痴，是迷昧不明换句话说，无明就是蒙昧、迷惑，事实上就是我人苦恼不安的原因。我人的烦恼，来自贪婪、嗔恚、自私、执著，而我们却自以为聪明绝顶，算无遗策。

由于我们愚昧不明，所以终日在苦恼不四安中讨生活。内而不了解自己，外而不认识环境。得意时趾高气扬，不可一世；
失意时怨天尤人，全不反省。以学佛为例，佛者觉也，我们学佛的目的是学觉悟，求智慧；
而不是烧香膜拜，求佛庇护、求佛保佑。我们不必说学出世间法智慧，即以世俗世间来说，立身处世，要有自知之明，也要有知人之明。如对事有先见之明，更可以趋吉避凶，减少烦恼。然而，自以为有'明
'的人，又有几个是'正觉'之明呢？ 所以，无明、正是世俗世界的最后本质。

** 五、业果轮回

无明是有情生死的根本，'无明缘行
'，就是愚昧的意志冲动。哲学家伏尔泰谓：'万事起于惑'；
某哲学书上说：'错误加盲动，等于人生
'。无明是惑，盲动就是行。迷惑下的行动-​-长时间累积的行为经验，就是佛学术语所称的业。

业，梵语Karman，汉译'造作
'，也就是行为。梵文原意本来单指行为，后来与因果关系结合，就成为'业力
'-​-能够遗留、持续下来的一种力量。行为有身、口、意三方面，这三方面的行为都有善有恶，可感召后有的果报。事实上，就是行为残余的潜在力量。这潜在力量由过去遗留下来，一直存续下去，以引生未来的结果，这即是'业果'。业力有支配生命未来趋向的力量，这就形成了'业果轮回
'理论。

印度早在《梵书》末期，业果轮回说已经萌芽，在早期《奥义书》时代而渐趋完备。佛陀住世时代，从俗的接受了业果轮回这一名称，建立了以缘起法为立论基础的内容。但佛教的业果轮回说与外道不同之处，即不承认有一轮回的主体-​-灵魂，而主张是业力自身的轮回。到后来大乘佛教瑜伽行学派，建立了以第八识为轮回主体，中国佛教以此为定说。

佛经上把有精神作用的有情(　有情识、情见的众生
)，分为五趣-​-天、人、畜生、饿鬼、地狱( 有加修罗趣而称六道者
)。此处为篇幅所限，就不往下细说了。

* 第七讲　缘起的组成架构-​-三法印

** 一、三法印、四法印

在原始佛教中，'三法印
'是佛法的基本教义。这是说明宇宙人生现象的三项定律，也是衡量一切教法的标准，凡是符合三法印尺度的，是了义佛法，若与此三法印相违的，即使是佛陀亲说，也是不了义法。

所谓三法印，是'诸行无常'，'诸法无我'，'涅槃寂静
'。也有在诸行无常之后，加上'一切皆苦'法印，而成为'四法印
'者。但'无常'的本身就是苦，了知无常真相，苦即在其中，似不必另加一法印，所以通常仍说三法印。

法印，梵文
dharma-uddana，法者指佛法，印是印记或标志-​-印有真实、不变之义，有如官府的印信，能做证明，所以法印就是佛法标志。

三法印，是佛陀自有情的自身说起的。佛陀住世时代，婆罗门教和其他外道，有主张生死五蕴身中有一个真实常住的我；
亦有主张离五蕴身外有一个真实常住的我；
佛陀以有情是五蕴和合而有，是缘法起法。依缘起法则说，宇宙间没有永恒不变事物-​-此即所以无常；宇宙间没有孤立存在的事物-​-此即所以无我。所以佛陀的三法印、是指藉四大五蕴而有的有情说的。如《杂阿含》第十经称：

如是我闻，一时，佛住舍卫国祗树给孤独园。尔时、世尊告诸比丘：
'色无常，无常即苦，苦即非我，非我者即非我所；
如是观者，名真实正观。如是受、想、行、识无常，无常即苦，苦即非我，非我即非我所；
如是观者，名真实正观。圣弟子如是观者，于色解脱，于受、想、行、识解脱，我说是等解脱于生老病老、忧悲苦恼'。时诸比丘闻佛所说，欢喜奉行。

经文中说'无常即苦，苦即非我'。何以说苦即非我呢？
因为照佛教法义的解译，'我谓主宰
'-​-我即是能做得了自己的主，做不了自己的主，自然不是我。所以佛教指五蕴和合之我为假我。《佛地论》一曰：'我谓诸蕴世俗假者
'。因此才说：'苦即非我'。

原始经典中也说到四法印，如《增一阿含》二十三称：

诸比丘，欲得免死者，当思维四法本。云何为四？
一切行无常，是谓初法本，当念修行。一切行苦，是为第二法本，当共思维。一切法无我，此第三法本，当共思维。灭尽为涅槃，是第四法本，当共思维。如是比丘，当共思维此四法本。所以然者，便脱生死病死愁忧苦恼，此是苦之原本。是故诸比丘，当求方便，成四法，如是诸比丘，当作是学。

《大智度论》　卷二十二，解译三法印说：

问： 何等是法印？

答曰：
佛法印有三种。一者一切有为法，念念生灭皆无常。二者一切法无我。三者寂静涅槃。

行者知三界皆是有为，生灭作法，先有后无，今有后无，念念生灭，相续相似生故，可得见知；
如流水、灯焰、长风、相似相续故，人以为一。

众生于无常法中常颠倒故谓去者常住，是名一切作法无常印。

一切法无我，诸法内无主，无作者、无知、无见、无生者、无造业者、一切法皆属因缘；
属因缘故不自在，不自在故无我，我相不可得，如破我品中说，是名无我印。

问曰： 何以故但作法无常，一切法无我？

答曰： 不作法因无缘故，不生不灭，不生不灭故，不名为无常..

寂灭者是涅槃，三毒、三衰火灭故，名寂灭印..

论文中的意思是说：
凡是有为法-​-即因缘和合的造作之法，这种互相关涉对待生起的事物，没有自性(定性)，没有自性就有生灭，有生灭就是无常。这种关涉对待之法，'属因缘故不自在，不自在故无我
'。涅槃，梵文nirvana，原意是'火熄灭的样子
'。贪婪、嗔恚、愚痴三种毒火的熄灭，就是涅槃，此留待后面再详述。

三法印或四法印，是建立在'缘起'的理论基础上；也可以说，缘起是建立在三法印或四法印的架构上-​-本来一切法都是互相关涉对待而生起，于缘起理论本身也不例外。诸行无常，是告欣我们世间没有永恒不变的事物，一切现象都不断的迁流变化；诸法无我，是说明世间没有孤立存在的事物，一切都是在时空里彼此关涉，相互依存；
至于诸受皆苦，是告欣我们生命的本质是焦虑不安，同时也是无常的、是无我。

** 二、五蕴世间

三法印的第一、第二法印，是'诸行无常'、'诸法无我
'。但是要了解无常与无我，必须先要了解'四大'与'五蕴
'。所以此处要先从五蕴世间说起。佛陀住世时代，各种外道对于世界人生的学说，有神意论、宿命论、无因论等，此外还有一种'结因论
'，认为世界和人生，是由地、水、火、风、苦、乐、灵魂七种元素结合而成，由元素结合之良窳而决定人的一生命运，这是另一种宿命论。

佛教的理论，认为世间有两种，即'有情世间'与'器世间
'。有情世间-​-即所谓'众生
'，是精神和物质的组合，其组合的元素称为五蕴-​-色、受、想、行、识；
器世间，完全是物质的组合，其组合的元素称为四大-​-地、水、火、风。而这四大五蕴两类元素，并不是固定的，而是经常变动不居。现在就探讨这四大五蕴的内容：

'一'，色蕴：
色蕴是物质的组合，其组合内容就是四大-​-地、水、火、风。地水火风，是印度古代对于物质的分类，称作四大；这就像中国古代把物质分为金、木、水、火、土，称作五行一样。四大或五行，不是指四大或五行的实物，而是指其物性-​-如地大性坚，支援万物；
水大性湿，收摄万物；火大性暖，调熟万物；
风大性动，生长万物。这四者，能造作一切色法，所以称为'能造四大
'。四大所造的有人体侍五根，外境的五尘，尚有一部分观念上的物件-​-法尘，这就构成了整个物质世界。

'二'，受蕴；
受蕴包括了我人身个器官对外界接触到的感觉，即由眼耳鼻舌身意的六根，与外境色声香味触法的六尘相对而产生的感觉。这些感觉有愉快的(　乐受
)、不愉快的( 苦受 )、及非愉快非不愉快的( 舍受 )。

'三'，想蕴； 想蕴是知觉作用，经中称其'于境取像为性，施设种种名言为业
'。也是由内六根与外六境相对、所产生的辨别认识作用。

'四'，行蕴； 行蕴是我人的意志活动，这种意志活动就造成了或善或恶的'业
'。行蕴其实就是'心所有法
'中的思心所，《俱舍论》称思心所：'思谓能令心有造作
'。造作就是在意志发动下的行为-​-包括著身、口、意三种行为在内。

'五'，识蕴； 识蕴是'于所缘境了别为性
'，其实就是我们认识作用的主体。识在原始佛教只说眼耳鼻舌身意六识，后来大乘佛教发展为八识-​-意识之后尚有第七末那识，第八阿赖耶识-​-关于末那识与阿赖耶识，以非本讲范围，此处从略。　色蕴-​-色-​-物质-​-有情生理方面的身体-​-即眼耳鼻舌身五根受、想、行、识四蕴-​-非色-​-名-​-心-​-有情的精神作用。

五蕴若自其认识作用分析，其分组的情形是：

识蕴-​-主观的能认识的识体-​-心-​-我

色、受、想、行四蕴-​-客观的所认识的物件-​-我所

五蕴是因缘和合之法，它生灭变异，迁流不住，所以它无常，无我。

** 三、诸行无常

佛陀时代说三法印，是自有情生死流转观点立论。那个时侯的各派外道，以为在生死五蕴身中，或生死五蕴身外，有一个真实常住的'我
'存在。佛陀以缘起立场，以有情是因缘和合而生起，因缘和合之法，变化不居，无常是必然的理则；
诸法关涉对待而存在，其中当然没有一个主体的自我。至于苦，无常即是苦。唯是众生执著有一个真实常住自我的存在，所以起惑造业，生死流转。果然了悟到无常与无我，惑业不起，则即能趋向涅槃。

五蕴和合的众生既然是无常无我，则四大所成的器世间自然也是无常无我。所以龙树菩萨说：
'三界皆是有为
'-​-有为即是因缘和合的造作之法，无常无我无宁是必然的事实。'大智度论
'中称：'一切有为法，念念生灭皆无常'。无常有两种，一是'刹那无常
'，一是'一期无常
'。刹那无常就是念念生灭的无常，一期无常则是有情一期寿命的无常，事实上，一期无常就是由刹那无常累积而来的。　

诸行无常的行，狭义的说、是念念生灭的心行，广义的说、是五蕴中行蕴的行-​-万法生灭变异的行。凡事于极短时间内发生变化者，莫如我人的心念，如《宝雨经》所说：

'此妄心如流水，生灭不暂滞。如电，刹那不停'。

其实，万法迁流不息，不仅心识为然，我们生理的色身也是如此；毛发爪甲的代谢，血液淋巴的循环，是无时或止的。时时刻刻有新细胞的产生，时时刻刻也有老细胞的死亡。十岁时的我，全然不是五岁时的我，三十岁的我，也全然不是二十岁的我。所以佛陀有言：
'一见不再见'； 庄子云：'交臂非故'； 孔子曰：'逝者如备夫，不舍画夜'；
禅宗语称：'婴儿垂发白如丝'，这都是无常的注脚。

在诗人的笔下，无常的句子更是不胜枚举。如曹孟德《短歌行》：'对酒当歌，人生几何，譬如朝露，去日苦多
'。去日苦多，是生命无常；
杜子美《离乱诗》：'时难年饥世业空，兄弟羁旅各西东，田园寥落干戈后，骨肉流离道路中。'
骨肉流离，是聚散无常；李太白《越中览古》：'越王句践破吴归，满朝文武尽锦衣，宫女如花春满殿，只今惟有鹧鸪飞。'由宫女如花到鹧鸪飞舞是盛衰无常；刘禹锡《乌衣巷》：'朱雀桥边野草花，乌衣巷口夕阳斜，旧时王谢堂前燕，飞入寻常百姓家。'王谢燕子，入百姓家，是世事无常。

无常，不仅指有情心识或社会人事，器世间的色法亦是如此。我们讲堂中使用的桌椅，去年在使用，今年在使用，明年仍可使用，看起来似乎是常住的。事实上，它们正在刹那刹那在损耗。肉眼可见的如木料的虫蛀、腐朽，肉眼不可见的，构成木料的原子中，电子正以高速绕著原子核在旋转；
原子是如此，天体的运转又何尝不是如此？
四时运行，功成者退，这不也是迁流代谢？

由以上种种事实看来，有情的生老病死，万法的生住异灭，世界的成住坏空，全是在刹那刹那，迁流变化，何尝有常住之法？苏东坡《赤壁赋》中的句子：'自其变者而观之
，则天地万物曾不能以一瞬'。《金刚经》中有名的偈子：
'一切存为法，如梦幻泡影，如露亦如电，应作如是观
'，这就是宇宙人生的真像。　

说到无常，使我们感到颓丧、悲观，、或绝望。事实不然，由有到无，由老到死，由盛至衰，由聚至散，固然是无常；
但是反过来说，由无到有，由幼到壮，由衰至盛，由离至合，又何尝不是无常？
语云：'不有所废，何有所兴
'；'四时运行，功成者退'。自人事来说，富有者以奢侈而沦为贫贱，显贵者以骄横而失去权势，固然是无常，但贪困刻苦向上而成为富有，微贱者发奋立志而至于显贵，又何尝不是无常？
如果万法常住，则富者永富，贪者常贪；贵者永贵，贱者常贱，则贫者贱者人生还有什么希望？
万法必须受因缘支配，因缘和合，则有生、有成、因缘散离，则有坏、有灭，这样才有生死流转，迁流变异；也必须如此，所以才有寒来暑往、阴睛圆缺的天象；
所以才有生老病死、悲欢离合的人生； 所以才世间。

** 四、诸法无我

佛教的三法印之一，是'诸法无我
'。要明白诸法何以无我，先要明白'我'是什么。

佛陀出世之前，印度的传统宗教婆罗门教，主张有一个常、一、主、宰的、以自在为性的自我-​-个人内在本元的我
Atman。奥义书哲学即强调这种意义的自我。这个我与宇宙灵魂大我的梵天，有著同一的本质，即所谓'梵我一如'。这个我，是永远不灭的本体的自我。当时的许多外道，亦以这个我是灵魂、是实体的自我。佛陀以缘起的立场，否定这种永恒的、形而上的自我。所以说：'诸法无我'。

佛陀所说'无我'的我，是指五蕴和合的假我之中，并没有一个常、一、主宰的'神我
'。如《杂阿含》一二零二经：谓

汝谓有众生，此则恶魔见，唯有空阴聚，无是众生者。

如和合众材，世名之为车，诸阴因缘和，假名为众生。

经文的意思是说：　集合了木材车轮等，组成了车； 由诸阴( 五蕴
)的因缘和合而有了众生，其中何尝有车或我的自体存在？
这在一二零三经中也有相似的解说：

此形不自造，亦非他所作，因缘会而生，缘散即磨灭。

如世诸种子，因大地而生，因地水火风，阴界入亦然。

因缘和合生，缘离则磨灭..

上文'此形'二字，指的是有情；'阴、界、入
'三字，阴是五阴-​-即色、受、想、行、识的五蕴；
入是十二入-​-即眼、耳、鼻、舌、身、意六根，加色、声、香、味、触六尘的十二处；界是十八界-​-即十二处再加上眼、耳、鼻、舌、身、意六识，合称十八界。五蕴已如前述，十二处、十八界是由五蕴开展而来的。这些全是因缘和合之法，所以'缘尽则磨灭'。缘尽则灭，此中何尝有一个常一主宰的自我？《杂阿含》三十四经谓：

尔时世尊告余五比丘：
'色非有我，若色有我者，于色不应病苦生，亦不得于色欲令如是、不令如是。以色无我故，于色有病有苦生，亦得于色欲令如是、不令如是..受、想、行、识，亦复如是..'

由此可见，这里所说的我，指的是婆罗门教的神我　Atman
，因为神能主宰一切、支配一切。'我'也被当作具有此种自由意志的存在；
因此，如色是自由自在的自我，应该能使自己免于疾苦。色既然没有这种主宰的能力，那么色毕竟非我，色中亦毕竟无我。受、想、行、识亦复如是，所以五蕴无我。

** 五、无常无我的意义何在

佛陀说诸行无常，一切皆苦，诸法无我，使人感到消极、颓丧。事实上，三法印另有其积极、正面的意义，而为人所忽略。所谓无常，并不仅是由好变坏，反过来说，由坏变好也是无常。如由贫而富，由贱而贵，由愚而智，由迷而悟，又何尝不是无常？唯其无常，才予苦难众生以光明和希望。

诸法无我，说的是五蕴和合的我中，没有一个常一主宰的神我，而缘生之我毕竟存在。我人有自的意志，由我的勤奋努力，进德修业，可以改善自己的环境，可以增进社会的文明。我若一心向道，糈进不懈，我可以转迷成悟，可以证得涅槃。

至于一切皆苦，苦是人生的真相，是佛陀深入观察抉择证得的真理。但这不是沉迷在五欲六尘中的有情人人所能了解，而仅为有智慧者所能体会。唯其一切皆苦，才促使智者的向道之心-​-'厌苦
'才是修道的原动力。

三法印或四法印，其中'一切皆苦'，与'涅槃寂静'印，留在'四圣谛
'中，与'苦圣谛'、'苦灭圣谛'合讲。

* 第八讲　缘起说的具体表达-​-四圣谛

** 一、三转法錀

四圣谛，是佛陀证道后，到波罗捺国鹿野苑度化五侍者，'初转法錀'时所说的。

佛陀在菩提树下证悟的真理，原本是缘起，佛陀为五侍者说法，为什么不说缘起、而说四圣谛呢？那是因为'缘起甚深，无信云何解'？
缘起法是：'甚深最甚深，微细最微细，难通达亟难通达'的妙理，不是未起信的人所能了解及接受，所以权巧方便，把缘起的妙理重加组织，以'四圣谛'表达出来。因为苦、集、灭、道四圣谛，不仅在因明学-​-逻辑上推理可得，并且也是实践行持的法门，尤其著重在道可修这一谛上。

四圣谛是什么意思？
原来圣者正也，以理正物名圣；谛是真实，真实之理，不虚不妄，而此真理为圣者所证，故曰四圣谛。《佛遗教经》曰：'月可令热，日可令冷，佛说四谛，不可令异'。佛陀住世时，一再要求他的弟子，要不断去学习四圣谛，如果真正理解、实践四圣谛，则由八正道就可建立阿罗汉的解脱知见和一切胜行，而证入阿罗汉果。

于此，我们自原始经典中、找出几段佛陀的教示：　《杂阿含》三八零经：

尔时，世尊告诸比丘：'有四圣谛，何等为四？苦圣谛，苦集圣谛，苦灭圣谛，苦灭道迹圣谛'。

《杂阿含》三八四经：

尔时，世尊告诸比丘：'有四圣谛，何等为四？谓苦圣谛..若比丘于苦圣谛已知、已解，于苦集圣谛已知、已断，于苦灭圣谛已知，已证，于苦灭道迹圣谛已知、已修，如是比丘名阿罗汉，诸漏已尽，所作已作，离诸重担，逮得已利，尽诸有结，正智善解脱'。

在《过去现在因果经》中，记述佛陀在鹿野苑'三转法錀'的过程，内容如下：

尔时世尊，观五人根堪任受道，而语之言，乔陈如，汝等当知五阴盛苦，生苦、老苦、病苦、死苦，爱别离苦、怨憎会苦、所求不得苦、失荣乐苦。

乔陈如，有形无形，无足一足，二足四足多足，一切众生，无不悉有如是苦者。譬如以灰覆于火上，若遇干草，还复燃烧，如是诸苦，由我为本。若有众生，起微我想，还复更受如此之苦，贪欲嗔恚，以及愚痴，皆悉缘我根本而生。

又此三毒，是诸苦因，犹如种子能生于芽，众生以是轮回三有，若灭我想及贪嗔痴，诸苦亦皆从此而断，莫不悉由彼八正道，如人以水浇于盛火，一切众生，不知诸苦之根本者，皆悉轮回，在于生死。

乔陈如，苦当知、集当断、灭当证、道当修。

乔陈如，我已知苦、已断集、已证灭、已修道故，得阿褥多罗三藐三菩提。

是故汝今应当知苦、断集、慕灭、修道。

以上就是三转法錀。三转中第一次称示转，第二次称劝转，第三次称证转。一说再说，无非是使众生知苦、断集、慕灭、修道。

四圣谛，包括流转缘起与还灭缘起两门，前者是苦、苦集二谛，后者是苦灭与苦灭之道二谛。换句话说，苦圣谛、是说明人生是苦的真像，集圣谛，是说明人生之苦的原因，苦灭圣谛，是涅槃寂静的境界，苦灭之道圣谛，是达到涅槃境界的方法。

** 二、苦圣谛

四圣谛的第一圣谛是苦圣谛，《因果经》以人生八苦-​-生苦、老苦、病苦、死苦，爱别离苦、怨憎会苦、求不得苦、五阴炽盛苦为代表。事实上，苦的种类很多，范围极广。《俱舍论》卷二十二中有云：'诸有漏行，皆是苦谛
'。有漏行的范围，包括(1) 非可意的有漏行法-​-如苦受； (2)
可意的有漏行法-​-如乐受；(3)
余有漏行法-​-如不苦不乐受。以上三受，其性质全是苦。即苦苦、坏苦、行苦，这就是佛经中所说的三苦。三苦，是依苦的性质而分类的。三苦的梵文是　tri-duhkhata
，其中tri是三，duhkhata
是苦的性质，或苦之为苦的要素。所以三苦的原意，指的是其通于苦的特性，而非指三种俱体的苦。这三苦，是苦苦，坏苦，行苦，兹分述如下：

'一
'，苦苦：　苦苦，这是我人生理上-​-即肉体上的苦，也就是我们常识上所说的痛苦。如生病时肉体上的痛苦，受创伤时肉体上痛苦，甚至于棒击鞭挞时的痛苦，这即所谓'苦受
'。这种神经感觉上的痛苦，以各人感觉的锐敏或迟钝而有所不同，假如施以药品或麻醉剂，则其痛苦即可减轻或消失。这就是苦苦。

'二
'，坏苦：　这是心理上-​-即精神上的苦，也就是乐境的消逝或坏灭所引起的苦。如亲人死亡，钱财损失，名誉受损等，精神上即感到极大的痛苦；
或者说，出国旅行，到风景区游览，空气清新，风光如画，感到可意而快乐；但如果一直游下去，游到两腿□痛，疲倦万分，就由可意变成不可意，因感到厌倦而生苦。这时找到一家饮料店，坐下喝著饮料休息。刚坐下休息感到可意而舒适，但坐久了同样会感到厌倦而生苦。由此可知，可意之境的'乐受
'，会变坏、消失，这就是坏苦。

'三
'，行苦：　行苦，是由因缘和合，迁流变异所生起的苦，也是一种微细而不易察觉的苦。行苦的行，就是'诸行无常
'的行。行的梵文是 samskriyate，它的意思是'依此而被形成
'，或者是'此是被形成者
'。这是以由形成的力与被形成的物二义所成立，在汉译经典中解释为'造作
'，即是指现象界的生起存在，都是相依互存，彼此关涉而有的。生起存在是如此，变异与坏灭也是如此。这在'诸行无常
'中已有所叙述。

原来宇宙万有生住异灭的过程，在前期是相辅相成，在后期却是相斥相反。而由相辅相成转化到相斥相反，其因素不是来自外界，而是来自内部。照哲学家黑格尔的说法：'有限事物的诸限制，并非单是来自外界，一事物之自身的本质，就是消灭其自身的原因，凭它自己的活动，它可以转化为与自身相反之物
'。基于以上的理解，任何的幸福与快乐，在诸行无常的公例下，不能常住，终归是苦。这就是行苦。

三苦之说，并非世俗世间的众生人人所能理解或体会，但人生真相确是如此，这是佛陀深入观察证得的真理，能否觉察或理解，就在众生各自的智慧了。

** 三、苦集圣谛-​-苦之生起

苦集圣谛，是说明人生是苦的原因。《增一阿含经》十七称：

彼云何名为苦集谛？ 所谓苦集谛者，爱与欲相应，心恒染著，是名为苦集谛。

苦的原因，是'爱与欲相应'，由爱与欲相应而产生了三种爱-​-欲爱、有爱、无有爱。这三种爱称作渴爱，如口渴时要饮水似的强烈追求。欲爱是肉体上的爱欲，有爱是对于存在(幸福快乐的存在)的渴求，无有爱是对无存在的渴爱(认为现实是苦，为脱离苦对于虚无境界的渴爱)。以上三种爱，都与当时印度的社会背景有关。佛陀时代，印度社会风气堕落，视欲爱为人生最大之幸福与理想，以至醉生梦死，追求片刻之欢。另一方面亦有认为现实的存在就是苦因，所以渴求虚无的境界，因此就有否定这些思想三种爱的名称。

在顾法严居士所译的《佛陀的启示》一书中，把人生痛苦根源的'渴爱'，分析的十分透彻：

苦的根源，就是'渴(爱)'。它造成'来世'与'后有'；与强烈的贪欲相缠结，随地随处舍取新欢。这渴爱有三：'一'、感官享受的渴爱(欲爱)，'二'、生与存的渴求(有爱)；'三'、不再存在的渴求(无有爱)。

这以各种形式表现的'渴求'、欲望、贪婪、爱著、就是生起一切痛苦、及使得生死相续不断的根源。但却不能将它视为最初因，因为按照佛法说，一切都是相对的、相互依存的。遁这苦之根源的渴(爱)，也是依其他条件而生起的。这条件就是受，而受又依触而生起，辗转相依，即构成所谓十二缘起。这在下文再为详论。

由上可知，'渴(爱)'并不是苦之生起的最初或唯一的原因、而是最明显、最直接的原因，也是最主要与最普遍的事实。因此，在巴利文原典的某些地方，集谛的定义中，除了以渴(爱)为主要的原因以外，还包括了其他的烦恼不净法，无法详论，只请牢记一点，这渴(爱)的原因，就是从无明生起的虚妄我见。

'渴(爱)'一词的意义，不仅是对欲乐、财富、权势的贪求与执著，也包括对意念、理想、观点、意见、理论、概念、信仰等的贪求与执著。根据佛的分析，世间一切困扰纷争，小至家庭个人之间口角，大至国与国间的战争，无不由这自私的'渴(爱)'所引起。从这一观点看，一切经济、政治、与社会问题的根本，都在这自私的渴爱。大政治家们想仅从经济与政治方面去解决国际纠纷，讨论战争与和平，只触及问题的表面，而不能深入到根本症结之所在。佛就曾告欣罗叱波罗：
'世人常感不足，梦寐以求，乃成为'渴(爱)'的奴隶。'

'渴(爱)
'并不是苦之生起的唯一原因，还包括其他的烦恼不净法，那就是佛经中所称的'二惑
'-​-见惑、思惑；'十使
'-​-贪、嗔、痴、慢、疑，身见、边见、邪见、见取见、戒禁取见等等，限于时间，就不能一一细说了。

** 四、苦灭圣谛-​-苦之止息

四圣谛中的苦圣谛、苦集圣谛，是流转缘起。但佛陀开显的教说，重点是在后面二谛-​-苦灭圣谛与苦灭之道圣谛的还灭缘起。第三圣谛的灭，就是涅槃，也即是三法印中的涅槃寂静。

涅槃是梵语，梵文　nirvana，音译涅槃、泥洹、泥畔等，义译灭、灭度、寂灭。它的原义是'从一切系缚中解脱出来、灭除再生于迷妄世界的种种业因'　的境界。换句话说，灭的意思是：
有情可以从相续不断的苦中得到解脱、解放、自由，而在中国经典中方正严肃的翻译和解释之下，就使我们初学者满头雾水，不知是怎么一回事了。我们随手在经典中找出几段注解的文字，来看对涅槃的解说：

'译名涅槃，正名为灭，取其义类，乃有多方。总为义翻，称为圆寂，以义充法界，德被尘沙曰圆，体穷真性，妙绝相累为寂'。《华严大疏钞》五十二。

'涅者言不、槃者言织，不织之义名为涅槃。槃又言覆，不覆之义，名为涅槃。槃言不定，定无不定，乃名涅槃。槃言新故，无新故义，乃名涅槃..'《涅槃经》

'槃名为趣涅名为出，永出诸趣名为涅槃、、、、、、永无臭秽诸烦恼故涅槃'《大婆沙论》

大乘经典中有所谓四种涅槃：　自性清净涅槃、有余依涅槃、无余依涅槃、无住大涅槃。限于时间，不能一一细说-​-说也说不明白。我们还是从顾法严居士、自巴利文原典里所译的有关涅槃的定义和说明：

'涅槃是彻底断绝贪爱；放弃它、摒斥它，远离它、从它得到解脱 。'

'一切有为法的止息，放弃一切污染，断绝贪爱、离欲、寂灭、涅槃。'

'比丘们啊！什么是绝对(无为)？它就是贪的熄灭、嗔的熄灭、痴的熄灭。这个，比丘们啊！就叫做绝对。'

'罗陀啊！熄灭贪爱，就是涅槃。'

'比丘们啊！一切有为无为法中，无贪最上。就是说；远离乔慢，断绝渴想，根除执著，续者令断，熄灭贪爱，离欲、寂灭、涅槃。'

'放弃、消灭爱欲与对此五蕴之身的贪求，就是苦的止熄。'

以上摘录关于涅槃的说明，予我们以概念上认识。有些地方，佛陀说涅槃就是真理：

'他这筑在真理上的解脱，是不可动摇的。比丘啊！凡是虚妄不实的，都是假法。凡是真实的、涅槃的，才是真理。因此，比丘啊！有这种赋禀的人，才是赋有绝对真理。因为绝对的圣谛就是涅槃，也是实相。'

绝对的真理是什么呢？
绝对的真理就是：世间没有绝对的事物，凡所有法都是相对的缘起的、无常不永恒的；而没有恒常不变、亘古永存的绝对实体。希腊哲学家海拉克来图谓'万法皆无常，常者唯有此万法无常之理
'，也是这个意思。

涅槃的境界究竟是什么？
我们不必讨论，那是讨论不出结果的。因为涅槃是证得的，不是说得的。那是佛经中所说：'言语道断，心行路绝'的境界。不过《佛陀的启示》一书中有一段话，是这么说的：

在几乎所有的宗教中，至善之境只有在死后方能达到。涅槃确可以当生成就，不必等到死后方能'获得
'。

凡是亲证真理、涅槃的人，就是世间最快乐的人。他不受任何'错综( complex )
'、迷执、忧、悲、苦恼等苛虐他人的心理状态所拘缚。他的心理健康是完美的。他不追悔过去，不冥索未来，只是扎扎实实的生活在现在里，因此，他能以最纯净的心情欣赏与享受一切，而不参杂丝毫的自我成分在内。他是喜悦的、雀跃的、享受著纯净生活。他的感官怡悦，无所烦忧，心灵宁静而安详。他既无自私之欲求、憎恚、愚痴、乔慢、狂傲以及一切染著，就只有清净、温柔，充满了博爱、慈悲、和善、同情、了解与宽容。他的服务精神是最纯正的，因为他不为自己设想。他不求得、不积储、甚至于不积储精神的资粮；因为他没有我的错觉，而不渴求重生。

** 五、苦灭之道圣谛-​-八正道

四圣谛的第四圣谛，是苦灭之道圣谛，简称道谛。原来苦的止息，是修道而证得的，所以灭谛的证悟是果，道谛的修行是因。佛陀一生游行教化四十五年，他以不同的方法、不同语言、不同的措辞，对不同的物件宣说这一真谛，在原始经典中，很多地方都说到八正道，此处且举《八正道经》为例，以见八正道的内容：

八正道者，一正见、二正思惟、三正语、四正业、五正命、六正精进、七正念、八正定。正见者，谓如信作布施，礼沙门道人，供养佛及孝顺父母之一切善法后世得福。正思惟者，谓念道不嗔，守忍辱不相侵。正语者，谓不犯妄语、绮语、恶口、两舌之口四过。正业者，谓不、不盗、不淫。正命者，于饮食、床卧等不贪，离非法。正精进者，谓行精进。正念者，谓念念不妄。正定者，谓守意护意而不令犯也。

这是说教方式之一，另外、《杂阿含》七八四经，对八正道的解释不分世间出世间，而七八五经，则分成世间出世间两种解释，世间八正道没有思维修习四圣谛、及无漏思维的道理，出世间八正道则要修习者不断思维四圣谛、及无漏思维的道理。经文过长，不再列举。如果予以简化，可得下列八项定义：

'一'正见： 正实的知见。'二'正思： 正确的思维。

'三'正语： 正直的言语。'四'正业： 端正的行为。

'五'正命： 正当的职业。'六'正勤： 正专的努力。

'七'正念： 正净的意念。'八'正定： 正统的禅定。

八正道的中心，以正见为主。正见是对善、恶、净、染的分别。八正道兼顾世间善法及出世间解脱法，自世间法来说，它是一种伦理学，导引世间信徒去恶向善：
自出世间法来说，由八正道就可建立解脱的知见、而证得涅槃。

如何依八正道修行证得解脱，留待下节再讲。

* 第九讲　证得涅槃的大道-​-八正道

** 一、佛陀的中道思想

印度的传统宗教婆罗门教，向来有以修行而达到身心苦恼之解脱的思想。奥义书哲学的最终目的，即在于以修行而求得解脱。该书中尝曰：

脱离住于彼胸一切之爱欲时，是时死为不死，而体现为梵。破坏胸中一切之系缚时，是时死为不死-​-此实(
优波尼沙陀
)教旨也。奥义书中所列的修行德目，有真实苦行、梵行、不杀生、慈善、诚实语等。

耆那教立二谛说，建立精神原理的生命(　有命、灵魂 )，和物质原理的非生命(
无命，非灵魂
)，这是心物对立的二元论。自性清净的生命被非生命所掩蔽-​-即微细物质流入生命，名之为业。此业系缚生命，轮回诸趣；必修苦行，使旧业消灭，新业不生，生命完全和物质分离，上升到超世间，就是解脱-​-涅槃。

有耆那教的自苦派，亦有纵欲快乐的顺世派。六师外道中，富兰那、阿夷多等就是属于快乐主义者，甚至于有谓爱欲之乐为人生最高理想，即是涅槃者。由古代印度的女神崇拜，到后来印度教的性力崇拜，都与这一思想有关。而苦行尤为外道普遍的修行方法。如当时的'六种苦行外道
'，修自饿、
投渊、赴火、自坠、寂坐，或持牛戒狗戒等修行方法。《本行集经》二十四称：

'或有裸形，或卧棘上，或卧板上..或卧冢间，或蚁蛭内，犹如蛇居..或复有用沙土烟尘，以涂坌身，正立而住，或不梳洗头首面目，发如螺髻，拳挛而住，或复拔发，或拔髭须..'。

以上种种修行方法，目的无非是求得生天或解脱。但这些苦行或欲乐，都是一些极端的行为，两者对于达成人生的理想目的全无益处，皆非证道之因。佛陀在王宫为太子时　，当有过欲乐经验，出家之后，六年苦行，知两者俱非真义，当摒去苦乐极端，行于中道。

所以佛陀证道之后，首次在鹿野苑为五侍者说法时，就为他们开示中道德目。这在南传的中阿含《罗摩经》、和汉译的《过去现在因果经》中都有记述。如《因果经》卷三记述，佛陀抵达鹿野苑时，五侍者以佛陀在苦行林中，接受农女的乳糜供养，似为退转道心，五人不告而别，到鹿野苑修苦行。此际遥见佛陀抵达，相约互不起立礼敬。及至佛陀到达，五人不觉均从座起，礼拜奉迎，互为执事。佛陀教示五人曰：

尔时世尊，语乔陈如言：　汝等莫以小智轻量我道成与不成，何以故，形在苦者，心则恼乱，身在乐者，情则乐著，是以苦乐，两非道因。譬如钻火，浇之以水，则必无有破暗之照；
钻智慧火，亦复如是。有苦乐水，慧光不生，以不生故，不能灭于生死黑障。今者若能弃舍苦乐，行于中道，心则寂定，堪能修彼八正圣道，离于生老病死之患。我已随顺中道之行，得成阿褥多罗三藐三菩提。

佛陀的中道思想，首次是在此提出的。以后在大乘佛教中，发展为空宗以八不为中道，有宗以三性为中道，天台以实相为中道，华严以法界为中道。而最初的中道，是指远离苦行与欲乐两种极端的修行行方式，以不苦不乐的中正稳健的态度，修持八正圣道。

** 二、八正圣道新诠

八正道是八种正道，何以用'八正道'一词而盖括之？
因为在实践修行上，八正道有其互相资助的关系，必须是齐头并进，缺一不可，所以把八正道看成'单一名词
'。如《杂阿含
》七八七经谓：'正见者能生起正志、正语、正业、正命、正方便、正念、正定..'，七八八经中亦有相似的教示。现在根据原始经典的教示，予以简化及语译如下：

'一'、正见：正见的意思是：正确的见解，正确的人生观。自世间法来说，做为一个佛教信徒，要正确的认识善恶业报，三世因果。并且崇信三宝，孝顺父母，守五戒，行十善，这是世间正见；以出世间正见来说，就是彻见缘起法、四圣谛的智慧，用正觉去观察，用正思维去抉择，向涅槃之路精勤修持。

与正见相反的是邪见，就是一切错误的见解。诸如怀疑因果，否定业报，不知缘起法、四圣谛，执著于身见、边见、戒禁取见等等。正是因为当时印度社会邪说充斥，所以佛陀说八正道，首先以正见总其纲领。

'二'、正思维：　思维是思量分别，正思维、是由正见所引起的正确的思量分别，这是指三业中的意业而言。自世间法及出世间法来说，都是指无欲、无嗔、无害心三种想法。即是说在思维上远离一切贪、嗔、痴、慢、疑等烦恼，而保持心理上的纯正。这种无贪、无嗔、无害之心的纯正意志，表现出的行动就是正语、正业与正命。

'三'、正语：
是正确的、如法的语言。这是指三业中的语业而说的。经典上说，妄语、绮语、两舌、恶口，是十恶业中的四种语业。妄语就是虚伪不实的慌话，绮语就是有挑逗性的轻薄话，两舌是挑拨离间、破坏他人感情或从中谋取利益的假话，恶口是粗暴鄙俗、或尖刻恶毒的的骂人话。修道的人，远离以上四种口业，以诚实语、质直语，柔软语和诤语对待他人，以启发他人的向道之心。

'四'、正业：
是正当的、如法的行为，这是三业中的身业而说的。经典上说，杀生、偷盗、邪淫是身体的三种恶业，杀生不仅指杀人，包括故意杀害一切生命；偷盗是窃取他人财物，虽一针一线之微，不告而取即谓之偷；
邪淫，是不正当的性行为。熹离以上三种恶业，进一步爱护生物，布施资财，宣扬正法，保持夫妇的正常关系(　出世间法要完全断绝爱欲
)，这就是正业。

'五'、正命：
正命是正当的生计，也即是远离邪命，佛陀住世时代。社会上有'五邪命
'-​-五种以诈欺为手段谋生的职业，是：'诈现异相、自说功德、占相吉凶、高声现威、说得供养
'。这就像现在的江湖术士，看相算命，风水地理，以至于乩童神棍，自称通灵，或自称有神通，有鬼神附体等等，来谋取钱财。

正当的资命生计，不但不开赌场、开妓院、贩买毒品，同时也不从事屠宰、捕鱼、打猎等伤害生命的行业。更进一步说，间接伤害生命如贩买猎枪渔具，也是义不当为。

'六'、正精进：　正当的努力。依正见、正思维、正语、正业、正命来修行，相续无间，勇猛策进，是正精进。《大智度论》中以'四正勤
'为精进目标，即已生恶为断除，未生恶使不生，未生善为生起，已生善使增长。不仅修道上努力精进，在世间法上说，或研究学问，或经营事业，或从事任何职业，都应该精进不懈，始能有所成就。如果游手好闲，懈怠堕落，虚度一生，与草木同朽，实在可悯。

'七'、正念、正念是正净的忆念，修道的人以'四念处
'为正念，即观身不净、观受是苦、观心无常、观法无我。以世间法来说，时时提高警觉，保持冷静清醒，以免因疏忽而造成重错误。如攀高失足，驾车肇祸，都是不能保持正念所致。

'八'、正定：
正定，是精神集中、与心境平静。这在出世间法说，是正确的，正统的禅定。禅定不是几句话就能说明白，留在后面再说。在世间来说，一个有修养、或担大任的人，亦必有相当的定力。《大学》一书谓：'知止而后有定，定而后能静，静而后能安，安而后能虑，虑而后能得。'由此可见，定力是一种精神修养。如果遇事惊慌失措，六神无主，如何能担当重任呢？

** 三、三十七助道品

佛陀在菩提树下所证悟的真理，是澈见缘起法。而四圣谛是体悟缘起的方便法门。所以佛陀一生教化，以四圣谛为教法纲要。而四圣谛中尤为重要的，是道之实践，由修八正道而达于涅槃。所以原始佛教经典中，曾以不同的方式，在不同的地方讨论这个问题。后来部派佛教以八正道为基础，组织成'三十七助道品
'，作为实践的纲领，兹略述如下：

三十七助道品，亦名三十七支，或三十七菩提分法。简分为七科，名目如下：

'一'、四念住：亦有译为四念处者。念是忆念，住是安住，即忆念安住于以下四者：

(1)观身不净。(2)观受是苦。(3)观心无常。(4)观法无我。

'二'、四正勤：　亦有译为四正断者。正勤是以正见的基础上勤求精进。四正勤即：

(1)已生善令得增长。(2)未生善令得生起。

(3)已生恶令得断除。(4)未生恶令不生起。

'三'、四如意足：亦有译为四神足者。足为所依之义，如意为所愿皆随。四如意足是：

(1)欲如意足。(2)勤如意足。(3)念神足。(4)思神足。

'四'、五根：
根有生长及护持两种意义，如树之有根，能开花结果；修道者依此五根，能成道果；
树根能护持其枝叶鲜润，此五根能护持道念不令丧失。五根是：

(1)信根。(2)进根。(3)念根。(4)定根。(5)慧根。

'五'、五力：
力者，于前五根，有增长发生之力量，能排除一切障碍，不为他法所伏，而能摧折他法。五力是：

(1)信力。(2)进力。(3)念力。(4)定力。(5)慧力。　

'六'、七菩提分：　菩提译为觉，故又名七觉支。这是由前之根力既固，由慧力发出正智，善能觉了。这七觉支是：

(1)择法觉支。(2)精进觉支。(3)喜觉支。(4)除觉支。(5)舍觉支　。(6)定觉支。(7)念觉支。　

'七'、八正道分：　此即(1)正见。(2)正思维。(3)正语。(4)正业。(5)正命。(6)正精进。(7)正念。(8)正定。

其实，三十七道品前面的二十九品，部分仍是自八正道开展而来。如四念住，就与八道中的正念相同。四正勤，也就是八正道中的正精进。七觉支中的精进觉支，与四正勤全部，五根中的精进根，五力中的精进力，以及八正道中的正精遁进全都相同。四念处又与五根中的念根，五力中的念力，七觉支中的念觉支，八正道中的正念重复。八正道中的正定，又见之于四如意足中的定如意足、五根中的定根、五力中的定力等等，认真对照，不重复的不过十二三个专案而已。

** 四、戒定慧三学

实践修行的德目，基本上仍是以八正道为基础。八正道可摄入戒、定、慧三学，所以修戒、定、慧，也就是修八正道。其统摄的情形是：

正语、正业、正命、正精进四支即是戒学。

正念、正定二支即是定学。

正见、正思维二支即是慧学。

在《翻译名义集 》中，为戒、定、慧三学下界说是：

道安法师云：
世尊立教，法有三焉，一者戒律，二者禅定，三者智慧。斯之三者，至道之由户，泥洹之关要..罗什法师云：
持戒能摧伏烦恼，令其势微；禅定能遮烦恼，如石山断流；
智慧能灭烦恼，毕竟无余。

一般说来，戒是止恶修善，依此资定；定者息缘静虑，依此发慧；
慧可破惑证真，依

此证果。兹再分述如下：

'一'、戒学：
戒学依律而立，佛陀住世时，订下种种戒律。佛涅槃后，大迦叶主持结集，由优波离以八十次诵出，称为八十诵律，后来分为五部，就是三藏中的律藏。

戒有在家戒与出家戒之分。在家正信士持五戒，出家沙弥持十戒，比丘持二百五十戒，比丘尼持三百四十八戒，不能一一细述。戒的目的，在于除恶向善，改正恶习。所谓修行，无非是修正我人不当的行为、习性。我们在家信众，如果能认真的守五戒，行十善，先在社会上做一个堂堂正正的公民，继而进解脱之道。

'二'、定学：
定即禅定，原语禅那，原意是从思考而来，所以汉译为静虑、或思维修。思维修是指'思维教法
'，即是冥想； 静虑是'息虑凝心
'，使精神集注。佛陀住世时代，印度的婆罗门教和外道都修习禅定，佛陀初出家时，即随阿逻逻伽罗摩和郁陀伽罗摩学习禅定。禅定是获得涅槃的手段，而不是目的。当时修禅定者，有'四禅八定'的层次。即是色界四禅-​-初禅、二禅、三禅、四禅；及无色界四禅-​-空无边处、识无边处、无所有处、非想非非想处的八种定。限于时间，不能细述。

'三'、慧学：
慧学之慧，即智慧之慧。而此智慧，不是世智辩聪，而是般若正智，即澈见缘起法、四圣谛的智慧。学佛的目的就是求得智慧，因为智慧能破烦恼，证涅槃。

** 五、修道之过程与证果

佛陀住世时代，佛弟子循八正道实践修行，就可建立阿罗汉的解脱知见和一切胜行，而证入阿罗汉果。据原始经典所载，僧团中出家比丘修行，除乞食传道外，主要是打坐修定。比丘共住之时，尚有所谓'法谈
'-​-共同讨论佛法义理。所以僧伽生活，言则'法谈
'，行则寂默-​-即是修定。比丘舍亲割爱，剃度出家，目的就在于开悟证果。

在修习的进程中，在形式上证果分为四个阶段，称为罗汉道四果。这四果是：

'一'、须陀洹：　是梵语须陀槃那 Srotapauna
的音译，义译预流，是预入圣贤之流的的意思。得此果者，长则七次轮回于人间天上，即得涅槃。

'二'、斯陀含：　是梵语 Sakkadagami
的音译，义译为一来，以其尚须一度入人道或天受生，故名为一来。

'三'、阿那含：　是梵语 Anagami
的音译，义译为不还，以其死后不再来人间受生，即于天界得涅槃，故名不还。

'四'、阿罗汉：　是梵语 Arahan
的音译，义译为应供，此为最高解脱果位，适应于人间天上的供养，故得应供之名。即所谓'我生已尽，梵行已立，所作已作，自知不受后有'-​-我已经从烦恼、生死中解脱出来；清净的梵行已经建立，一切义务职守都已做完，自己证知不会再入轮回中接受果报。

以上四果，前三者尚为有学果，故称为有学圣者，阿罗汉则所作已办，亦无所学，故称为无学圣者。

涅槃是可以当生成就的，即所谓'有余涅槃
'。但证得阿罗汉果的圣者，与常人有何不同之处呢？
由经典上探索，主要在于其精神境界。这就是情执解脱的结果，如其心境开朗，超越于苦乐、毁誉、得失，即所谓'八风吹不动
'的境界。尤其是当遭遇变故、拂逆的时侯，则可看出与常人不同之处。如佛陀涅槃时，多数弟子悲泣哀痛，失其常态；
而少数证果的弟子，则默念佛陀遗教，'生者必死，成者必坏，盛者必衰，合者必离
'。虽佛亦不能逾此缘起法则，而在筹谋遗教相续之计。

有两则小故事，可以看出证果者的境界。佛弟子中有一个名叫沙弥底崛多的，在修行中患了癞病，四肢溃烂，十分痛苦。佛陀到病寮中去看他，为他说受为苦感，五蕴非我。沙弥底崛多精进修行，获得解脱，他死前自作偈曰：

'前生所为业，今生受此苦，他生之苦因，今则已灭尽'。

另有一位已证果的优婆先那比丘，一日在山洞中坐禅，为毒蛇所咬，毒气立即周遍全身，他自知不免于死，喊同修比丘把他移到洞外。这时舍利弗见到了，见他面部表情温和，与平常无异，问其原因，优婆先那说：

'因悟五根六界，一切均非我及我所，肉体之死，殆无所关　。'

遂从容死去。舍利弗作偈赞叹曰：　

'久殖诸梵行，善修八正道，欢喜舍寿命，如人愈重病'。

这种于濒死之际，容色如常，高谈法义，从容而逝，真是置身于物外了。

*  第十讲　四十五年游行教化

** 一、波斯匿王的故事

佛陀大约在成道后的第五年，率领弟子到拘萨罗国的舍卫城游化，住在须达多长者所建的祗园精舍-​-又名祗树给孤独园，沙门瞿昙的教团到拘萨罗国传道，是轰动舍卫城的一件大事，多少人为他新颖的教义所吸引，到祗园精舍皈依，做佛陀的弟子。未几，拘萨罗国的波斯匿王也知道了，他想不出沙门瞿昙何以有如此大的号召力，多少人都去皈依他。有一天，波斯匿王轻车简从，到祗园精舍去访晤佛陀。波斯匿王与佛陀同岁，生得健壮勇武。他和佛陀见面，见对方竟是一个年轻沙门-​-佛陀具足三十二相，不留须、也不缠头，看来自然年轻些。年轻气盛的国王，一开口就以不太信任的语气问到：

'瞿昙，听说你宣称已证得无上正觉了吗？'

佛陀答到：'大王，如果有人宣称已证得无上正觉的话，那个人就是我。'

《杂阿含经
》中记载著佛陀回答波斯匿王的话：'大王，世有四事，小不可轻。何者为四？
一者王子虽小，最不可轻； 二者龙子虽小，亦不可轻；
三者火虽小，亦不可轻；四者比丘虽小，亦不可轻。'

这是一个软钉子，把波斯匿王的话碰了回去。

波斯匿王当然不会因这几句话而折服。他一连串的提出当代知名的六大思想家-​-即六师外道的理论和佛陀辩论。那时，六大思想家的哲学理论，是当时的潮-​-当时最时髦的理论，高阶层人士都挂在嘴上，以示渊博。并且，六大思想家出世较早，成名亦久。可以说是'权威人士
'，国王想以此来压倒佛陀。佛陀究竟如何答辩，经典中没有说明。但到最后，波斯匿王心悦诚服的皈依于佛陀座下，和佛陀建立了深厚的友谊，终其有生之年，敬佛陀如师如父，对僧团也十分支援与维护。下面有两个小故事，可见他对佛陀尊敬的一斑。第一个故事出在《杂阿含经》，经文十分有韵味，就不再语译了。

一时，佛在舍卫国祗树给孤独园，时波斯匿王，其体肥大，举体流汗，来诣佛所，稽首佛足，退坐一面，气息长喘。

尔时世尊，告波斯匿王：'大王身极肥盛。'

大王白佛言：'如是，世尊，患身肥大，常以此身极肥大故，惭耻厌苦。'

尔时世尊，即说偈言：

'人当自系念，每食知节量，是则受诸薄，安消而保寿。'

这以后波斯匿王特命一个小童，每当他吃饭的时侯，就为他诵这一首偈子，使他有所节制。果然他体重渐轻，身材减细，为此他曾特别向佛陀道谢。

波斯匿王晚年，对佛陀敬慕之情有增无减。《中阿含法庄严经》有一段故事，说波斯匿王有一天在宫苑中散步，在一株有浓荫的大树下停留下来，心中想到佛陀，悠然神往。他自言自语的说：'我曾在这样的树荫下，会见过佛陀。'想到这里，他回顾侍者问道：

'世尊现在何处？'侍者回称，佛陀到离此不远的冥陀伦巴村去了。国王立刻坐车赶到冥陀伦巴村，到佛陀住处敲门。佛陀迎出来，国王跪下捧住佛足，行了最恭敬的头面接足礼。

就座之后，佛陀问国王，何以匆匆赶到此处，而对我又如此恭敬。国王回答：

'世尊呀！你知道我宫中那两个木匠吧！　我给他们生业，他们因我而博得名望，可是他们对我的尊敬，远不如对世尊的尊敬。有一次在军旅之中，我带他们在一间狭小的房子里过夜，他们两人讨论世尊的教法，谈到半夜，及至上床睡觉时，两人把头向著据说是世尊所在的方向，将脚向著我的方向，这使我既惊讶、又感动。

他们两个人是我的仆人，但他们对我的尊敬，远比不上自己的尊敬，这可能是他们在世尊的说教里，获得了无上的法益。'

在这一则故事之后，波斯匿王连续说了六个深刻感人的小故事，最后他说：
'由此之故，我由衷的恭敬世尊为真正的正觉者。'

** 二、回到迦毗罗卫国度化

佛陀成道之后，第二年曾回迦毗罗卫国一次，据说并未受到故乡父老的一致欢迎。所以《本生经》上说：'瞿昙初不容于故乡。'何以故呢？
也许家乡父老以为他放弃王储之位，丢下父母妻子，出家云游。多年之后，却以比丘-​-乞士的身份回来。他所带的一群弟子，身著坏色之衣，手持乞食之钵，这使一向以族姓高贵自豪的释迦族父老深为反感。

佛陀在舍卫城传道的两三年以后，这时佛陀已经是国际知名的学者，在波斯匿王的护持下，许多国王大臣都皈依佛陀为弟子，迦毗罗卫全国上下也都知道了佛陀的成就。净饭王也派出大臣优陀夷到舍卫迎接佛陀还国-​-这优陀夷后来也出家做了比丘。

佛陀这一次还乡，受到全国上下热烈的欢迎。佛陀在王宫中为净饭王及百官眷属说法也会见了姨母波阇波提和妃子耶输陀罗。当佛陀要离开王宫，回往他驻锡尼拘律园时，佛陀的独子、年已十五岁的罗侯罗跟在佛陀的身后-​-当然他是由母亲授意而做的。他对佛陀说：'世尊，我是您的儿子，请您把财产给我吧！'他所说的财产，指的是王储之位。

佛陀望了他一眼，没有回答，罗侯罗继续跟著说：
'世尊，请把您的财产施给我吧！'

佛陀转身牵著罗侯罗的手，慈祥温和的说：
'罗侯罗，你何必求世上那些不能长久、必定消灭的东西呢？
让我给你那些世上永久不会亡失的东西吧！那是我在菩提树下聚积到的财宝，我可以全部给你做财产。'

就这样，佛陀把罗侯罗带出王宫，回到尼拘律园，要舍利弗尊者做罗侯罗的亲教师，为罗侯罗剃度，教育他如何修道。罗侯罗年岁太小，不能算是比丘，因此成为教团中第一个小沙弥。

佛陀于度化罗侯罗后，下一个度化的物件是难陀-​-他的异母弟、他继母波阇波提的儿子。也许，这是佛陀下一次回乡的事。一天，佛陀故意托著钵走到难陀的家门前，因为是佛陀亲临，守门者忙进去通报，难陀匆匆赶到门口，向佛陀行礼问侯。佛陀问他：

'难陀，你最近忙些什么？'

'我和孙陀利快要结婚了，她是国内有名的美人，我得整天陪著她，以免她不开心。'

佛陀也不说话，把手中的钵放在地上，转身往尼拘律园而去。难陀忙拿起钵，入内装满了饭菜，追在佛陀身后到了尼拘律园。他想放下饭菜，赶回去陪孙陀利。

当他把钵送到佛陀面前时，佛陀对他说：　

'难陀啊！你是我的弟弟，我照顾一切众生，就不能不照顾你，你了你永久的幸福，你随我出家好不好？
'　

难陀以为佛陀是试探性的问话，他就随口应到：'好啊！'

佛陀马上命身旁的弟子为难陀剃度，难陀见佛陀竟然认真，不禁大吃一惊，但他在佛陀面前也不敢反抗，就这样心不甘情不愿出了家。

据说，做了比丘的难陀，仍然整日想念孙陀利姬，佛陀以神通力带难陀到天界，令他看美貌如花的天女，问他：'这些天女和释迦族的女子比较起来，那些比较美丽？'

'比起这些天女来，世间女子就有如猿猴一般了。'难陀回答。

佛陀说：'难陀！　努力修行，我保证你将来可以得到这些天女。'

以后难陀果然精进不懈。后来他终于开悟了，他主动去见佛陀，取销前约。佛陀知道，开悟后的难陀，给他天女他也不要了。

或问，佛陀出家时，他的父亲净饭王已十分伤心，如今在老父老迈之年，又把他的次子、幼孙也带去出家，是不是有点不近人情？要解释这一点，就要从当时的国际情势说起。那时国际兼并，习以为常。迦毗罗卫蕞尔小邦，而族人骄矜自大，自诩为日之种姓，高人一等。加以朝中君老臣惰，一味奢侈宴安。年轻一辈的王子，履丰席厚，不辨麦菽，王弟难陀，庸碌无能，沈缅女色；
罗侯罗年幼无知，难当大任。佛陀为了国家前途，唯有接引二人出家，俾国家由贤者继任，或可挽救国家之危亡。这就是佛陀所以接引二人出家的原因。观三十年后，释迦族卒以骄惰亡国，为拘萨罗国毗琉璃王所灭，城破之日，王族被杀，几无遗类，可见佛陀之先知。

** 三、游化中的小故事

佛陀一生游行教化，发生过不计其数的小故事，都充满了趣味性和启发性，我们于此选录出几段来看看。

佛陀在鹿野苑度化五比丘之后，往伽耶度化三伽叶，途中天气炎热，在一座树林的大树下休息。这时，一群青年人闯进来，东寻西找的，看见佛陀坐在树下，就问佛陀道：

'有没有看见一个女人，逃到这里来？'

佛陀询问之下，原来他们都是附近的良家子弟，今天都带著妻子到这里来游玩。其中一个还没有结婚的青年，他找了一个妓女带著来参加。不意大家正玩得高兴时，那妓女偷了他的财物逃走了，因此他们才来追寻那个妓女。

佛陀说：'年青人呀！　你们以为，是寻回逃走的女人要紧呢？
还是寻回自已要紧呢？'

有一个青年人回答：'当然是寻回自已要紧啊！'

'年青人呀！你们坐下来，我来教你们如何寻回自己。'

一群青年人坐下来，佛陀很严肃的为他们讲说：　什么是正当的生活，什么是四圣谛和八正道。这群青年人都还相当纯洁，听了佛陀的说教，都皈依在佛陀座下。

另一个小故事，发生在王舍城附近，佛陀在灵鹫山精舍的时侯。

有一个富家子出家的输那比丘，也在山中林间修行，他十分精进，日以继夜的勤修。但由于修持过急，反而不易开悟。他心生退转，对同修说：'我这么努力，还不能开悟，何如回家过世俗生活，一方面享受欲乐，一方面拿财产做点布施功德。'

佛陀知道了，就到他修行的林中去看他，问他何以对修道有了悔意。输那很坦白的说出了自己的心事。佛陀问他：'输那呀！听说你在家的时候会弹琴，是吗？
'

'是的，世尊，懂得一点弹法。'

'那么，我问你，弹琴的时候，如果琴弦拉得太紧，会怎么样呢？'

'太紧的话，拉不出好音色。'

'那么，琴弦太松了又会怎么样？'

'太松了也弹不出好音色，世尊。'

'怎样才能弹出好音色呢？'

'世尊，弦不能太紧，也不能太松，要调整得适当合调，才能发出好的音色。'

'输那呀！修道也是如此。操之太急，就心烦气燥；放之过松，又会陷于懈怠。你要不急不缓，行于中道，这样才是正当的功方法。'

经过了这一番教训，输那掌握了正确的修行方法，后来终于断除烦恼，达到悟境。

** 四、婆罗门的抵制

在印度，婆罗门教是传统的宗教，是上三种姓一致的信仰-​-首陀罗是奴隶族，没有信仰宗教的权利。但由于僧团发展迅速，许多婆罗门种姓的子弟，也都皈依到佛陀座下，这就引起了婆罗门的妒忌与敌视。所以佛陀一生游化，并不全是所到之处，天人拥护，也常遇到婆罗门种姓的抵制。据阿含经所载，佛陀有一次在婆罗门族的五苇村托钵，一粒米也没有要到，那叫做：
'带著干净的钵回来
'。有一次到那罗聚落乞食，一个名叫婆罗豆婆遮的婆罗门说：'沙门呀！我们播种、耕田才得到食物，你为什么不播种耕田呢？
'

以上只是抵制，还有找上门挑衅的。佛陀在王舍城竹林精舍，有一天，一个婆罗门气势汹汹的到了精舍中，在佛陀面前粗言恶语的大骂-​-因为他族中有一个青年，皈依佛陀出家，他忍不下这口气，故而来找佛陀挑衅。

佛陀听著他诟骂，默然无言，直到那婆罗门骂够了，人也平静下来了，才平静的问他：'婆罗门呀！你家中偶而也有亲友来访的时候吧！'

'自然有呀！那又怎么样？'婆罗门说。

'那时候你会不会以酒食款待客人呢？'

'那是当然的事呀！　瞿昙。'

'如果你备下菜肴，而客人不接受你的款待，那些菜肴应该归于谁呢？'

'如果他们不吃的话，那些菜肴当然仍归于我呀！'

'婆罗门呀！'
佛陀注视著他说：'你刚才所骂我的那些话，我决定不接受它，还是归之你自己吧！如果我和你对骂，就如同主客相对用飧一样，因此，我不接受这菜肴。'

经典中这种小故事很多，不再列举。当时，不止婆罗门对僧团抵制，各种外道也处处与僧团作对。如'旃阇带盂谤佛
'的故事，就是一例。

** 五、何谓贱者

印度的四姓制度中，上三种姓是再生族，依宗教生活可以获得新生命。而首陀罗种姓是奴隶，是贱民，没有权利进入宗教生活，没有来生，所以叫做'一生族
'。

佛陀的教团中，没有种姓出身的限制，所以佛陀弟子中，有婆罗门学者，有刹帝利王族，有农工商业人士，也有贱民和奴藜。像十大弟子中持戒第一的优波离，就是奴隶种姓的理发匠出身。佛陀认为：
当我们说到'尊贵'或'卑贱'的字句时，我们所指的应该是'个人
'，而不是全体种姓。不能以出身阶级来决定一个人的尊贵或卑贱。下面就有一则佛陀和婆罗门争辩'何谓贱者
'的故事：

一天，佛陀著衣持钵，在王舍城内乞食，到了一家婆罗门的门前。乞食时的惯例，到了那家门口，要先唱偈子，这就是传道。这时，佛陀尚未开口，房内一个名婆罗豆婆遮的婆罗门，正端著供品，要行祭祀仪式。他看到有托钵的沙门上门，便粗言恶语的喝斥：

'去、去，我正在做神圣的祭祀，贱者是不能进来的。'

佛陀出身刹帝利种姓，并不是贱者。也不会因对方轻视自己而有嗔恚之心。但这是原则问题-​-基于众生平等的原则，不能不辩。佛陀反问对方：

'你可知道，什么样的人是贱者？什么样的人是人格低下的贱者？'

这一问，使那位婆罗门瞠目结舌，回答不上来。他这时也认出上门托钵的沙门是谁了，他也用反问的方式说：'我不知道，沙门瞿昙，你知道吗？
你说说看。'

'我知道。'佛陀说。那婆罗门忙敷座请佛陀坐下，请佛陀为他解释何为贱者。佛陀乃为他说偈曰：

'嗔恚心怀恨，隐覆诸过恶，犯戒起恶见，

虚伪不真实，如是等士夫，当知领群特。'

像这样的偈子，佛陀共说了二十七首之多，归纳起来，主要是说：

对人嗔怒且怀恨者。

伪装为善且无惭愧心者。

伤害生命而无慈悯心者。

行为损人利己者。

掠夺有主无主之物而据为己有者。

妄语欺人诈取财物者。

作恶而自行覆隐者。

贡高我慢而藐视他人者。

自造过恶而诬谤他人者。

父母年老而不善加奉养者。

沙门婆罗门如法乞食而诃责不与者。

生于婆罗门种姓，习诵婆罗门经典，而行诸恶业者。

具有以上行为之一者，就算是领群特-​-领群特，是贱民的意思。最后的结论是：

不以所生故，名为婆罗门，业为领群特。

意思是说： 没有天生的圣者，也没有天生的贱民。应该是以其行为(　业
)来决定其为圣者，还是贱者。

* 第十一讲　佛陀的遗教-​-以己为洲、以法为洲

** 一、佛陀的容色言行

佛陀住世时代，没有照相术，没有画像，佛陀涅槃，没有留下任何遗影。我们现在所看到绘制的、雕塑的种种佛陀像，全是佛陀入灭数百年后，历代后人想像出来的，所以不禁使我们想到，佛陀的容色，究竟是什么样子？

《论语》一书中，有几处刻画孔子容色的句子，十分传神：

《述而篇 》： 子温而厉，威而不猛，恭而安。

-​-厉是严肃，不是严厉。

《子张篇 》： 君子有三变，望之俨然，即之也温，听其言也厉。

-​-望之俨然，是庄重貌。听其言也厉，厉在此是言辞正确的意思。

《子罕篇 》： 颜渊喟然叹曰：
仰之弥高，钻之弥坚，瞻之在前，忽焉在后，夫子循循然，善诱人..

《论语》，是孔门弟子记录夫子的言行录。而《四阿含经》，是佛陀弟子是记录佛陀的言行录。何以前者生动，而后者却是千篇一律的：'如是我闻，一时，佛在..'呢？那是因为孔子时代，我国有普遍使用的文字和书写的工具；
而佛陀的言行，是以口传耳传下来的，不得不把格式固定下来，以便于记忆。所以，我们如果想从经典中捕捉佛陀的容色，我们可以从文字的精神中，来想像佛陀的庄严与慈悲。

佛陀身心健康，感情理智平衡-​-即所谓'悲智圆融
'。经典中说，佛陀证道后，有十种法乐。如： 永恒而绝对信心所产生的法乐；
最深禅定境界所引发的法乐； 无限慈悲心所引发的法乐；
解脱系缚和烦恼而获得的法乐..。因此，经典中有赞佛的偈子曰：

佛面犹如净满月，亦如千日放光明，圆光普照于十方，慈悲喜舍皆具足。

佛陀有如孔子，望之俨然-​-庄严；即之也温-​-慈悲。佛陀领导僧团，从不以'教主
'自居。佛陀说：'我不摄众
'。意思是领导僧团的，不是佛陀个人，而是如来的教法和戒律。佛陀有教无类，诲人不倦，是伟大的教师；佛陀演说正法，拯人慧命，是众生的慈父。可是很遗憾的是，由于后代弟子对佛陀的崇敬与怀念，因而不断的圣化、神化、偶像化，模糊了佛陀的真面目，也拉远了佛陀与众生的距离。在《四阿含经》和《四分律》中，记载了许多很有人情味的小故事，如佛陀为病比丘洗浴，佛陀为肓比丘穿针，佛陀扫地，佛陀自修房门等等，都十足刻画出人间佛陀的真面目。兹举一例，以见其余：

佛陀住祗园精舍的时候，僧团中有一比丘生病。佛陀去探视他，见病比丘身有污垢，佛陀就扶他到池边，为他洗浴，洗拭毕，并为他洗衣；
然后到病比丘住处，把卧处旧草丢弃，打扫干净，墙壁破处以泥浆补好，铺上新草，扶病比丘睡卧好，再为他盖上袈裟。

以上这个故事，出之于《四分律》。玄奘三藏的《大唐西域记》称：'祗园东北有塔，即如来洗病比丘处。'

** 二、十大弟子

佛陀证道之后，教团成立之初，有弟子一千二百五十余人。以后一生游行教化，四十余年，究竟有多少出家弟子，经无明文，不得而知。大约说，总应发展至初期人数的十倍或更多。在这众多弟子中，有一些极为杰出的弟子，即早期经典中所称的'十大弟子
'，他们各有专长，在教团中号称第一，兹介绍这十大弟子的事迹如下：

一，智慧第一的舍利弗：　他是王舍城迦罗臂拿伽村人，婆罗门种姓，父亲提舍是有名的论师，母亲舍利也是有名的学者。他的舅舅长爪梵志，就是后来皈依佛陀的摩诃俱希罗。他早年出家学道，是删阇耶吠罗胝子的弟子，因不满于删阇耶的怀疑派理论，就皈依于佛陀座下。在教团中，他是佛陀最得力的助手。祗树给孤独园，就是他负责监修的。佛陀晚年，提婆达多背叛，带著数百名比丘另成立新教团。从来于新教团一次开会时，舍利弗突然出现于会场，以义正辞严的言词说服了附和提婆达多的比丘，大部分的比丘又回到佛陀座下。佛陀晚年，他先佛陀入于涅槃，使佛陀颇为伤感。

二，神通第一的目犍连：　他也是婆罗门种姓，和舍利弗同师事删阇耶，后来和舍利弗一同皈依佛陀。据说他修得神通第一，佛陀晚年，拘萨罗国的毗琉璃王带兵灭亡迦毗罗卫国，目犍连以神力飞入迦毗罗卫城，把五百名释迦族青年男女摄入钵中，飞出城外开钵一看，钵中人已化为血水。这是神通不抵业力的明证。他晚年出外传道，途经山区，为倮体外道向山上推下乱石砸死。这是舍利弗逝后不久的事。

三，说法第一的富楼那：　富楼那辩才无碍，善于说法，且有忍辱的精神，他要到输那国去传道，佛陀以为输那国文化落后，民性凶悍，劝阻他不要去。富楼那声称无论他们打我骂我，刀杖加身，他决不与他们反目，且怀著感恩之心。佛陀赞叹他说：
'善哉！富楼那，良哉！富楼那。你有如斯忍辱之心，必然能到那边陲的输那国，达到你的心愿，去吧！富楼那。'

四，解空第一的须菩提：　他出身于婆罗门富家，生性慷慨，好济助穷人。他随佛陀出家，善解法义。有一次佛陀外出，回到鹫岭精舍时，别人争相迎接，须菩提想：
佛陀的法身，并不在四大和合的肉体上，我奉行佛陀教法，体证诸法空理，不该为事相迷惑才对。他就不去迎接。佛陀回到精舍，弟子们争相迎接，其中有一个莲花色比丘尼，跑到人前，跪接佛陀，并说：
'世尊，弟子莲花色第一个来迎接您。'

佛陀慈祥的说：'莲花色，你不是第一个迎接我的人，须菩提才是第一个迎接我的人
。他在石窟中观察诸法空性，见法的人，才是第一个见到如来、第一个迎接佛陀的人。'

五，论议第一的伽旃延：　伽旃延是南印度阿槃提国人，父为国师，他曾从阿私陀仙人受学，仙人临命终时，要他去皈依佛陀。他善于论议，言辞简明。一个外道问他：'在这世间，人们不断的斗争，是为了什么呢？'他回答：'是我见和贪欲作崇。'

'请问，什么人才能离开我见和贪欲呢？'

'只有佛陀，他是无上正等正觉者，他没有贪欲烦恼，没有我见执著，他是天人的导师　。'迦旃延肯的回答。那问话的外道，就此去皈依了佛陀。

六，头陀第一的大迦叶：　大迦叶生长婆罗门富豪之家，但随佛陀出家后却修头陀苦行。住于冢间林下。有一次，他去见佛陀，身著粪扫衣，发须杂乱，新比丘根本不认识他。佛陀在座上看到了，喊他：
'大伽叶，你过来，我这里留了半座给你。'可见佛陀对他的重视。大迦叶年老时，佛陀劝他放弃苦行。舍利弗也劝他回僧团从事弘法利生。他说：

'弘扬正法，教化骄慢恶智的众生，我没有这份毅力和勇气。我只能树立一个修苦行的榜样，让后学者对于少欲知足的头陀苦行、知道遵从和实行罢了。'

佛陀涅槃后，大迦叶主持第一次结集，并继续领导僧团。

七，天眼第一的阿那律：　阿那律是甘露饭王的儿子，是佛陀的堂弟。他随佛陀出家后。因在佛陀说法时打瞌睡，受到佛陀的呵斥。他发誓精进修行，通宵不眠。终以用功过度，致双目失明。佛陀教导他修定可以重见光明，他如法修持，终于获得了天眼。他热心于布教活动，到没有人弘法的地方去度化。许多人受了他的感化而皈依了佛陀。

八，持戒第一的优波离：
优波离是首陀罗种姓的贱民，在释迦族的王宫中做理发匠。王宫中的七王子出家时，他也随著出了家。他个性拘谨，佛陀制定的戒律，他一丝不苟的遵守，他也常向佛陀请示戒律的问题，一一的记下来。所以在僧团中他持戒第一。他年老时，经常调处僧团中的纠纷，由于态度公正，受到大众的遵敬。后来大迦叶主持结集时，律藏部分就是他诵出来的。　

九，多闻第一的阿难陀：　阿难陀是白饭王的儿子，是佛陀的堂弟，据说他小于佛陀三十岁，二十余岁出家，随在佛陀身边做侍者二十五年之久。佛陀在精舍说法，或出外游化，他随时都在身边，所以成就了他多闻第一。《增一阿含经》
中称：'我声闻中，第一比丘，知时明物，所至无疑，所忆不忘，多闻广远，堪忍奉上，所谓阿难比丘是。'

阿难相貌端庄，性情和善，佛经上说他：
'相如秋满月，眼似净莲花，佛法如大海，流入阿难心。'第一次佛经结集时，经藏部分是他诵出来的。

十，密行第一的罗侯罗：　他是佛陀的独子，十余岁出家，在僧团中做小沙弥，舍利弗是他的亲教师。佛陀怕他因身分特殊而心生乔慢，不时告诫他要忍辱修行，不得有乔慢心。据说，有一次他的住室为一个比丘占住了，他不敢告欣佛陀和舍利弗，竟在厕所中端坐了一夜。他默默修持密行-​-修三千威仪，八万细行，因此被称为密行第一。经典中说罗侯罗早逝，不到三十岁就入涅槃了。

** 三、落寂的晚年

随著岁月的消逝，渐渐的，佛陀进入志耄之年了。

许多不如意的事都发生在佛陀晚年，大约都发生在佛陀七十岁以后那段时间。

第一件事是提婆达多的叛逆。提婆达多是阿难的哥哥，也是佛陀的堂弟。他早年随佛陀出家，最初也颇为精进。但到佛陀老年时，提婆的野心增长了，他想取代佛陀的地位，成为僧团的领导者。这时摩揭陀国发生政变，阿阇世王子拘禁了他父亲频婆娑罗王，而取得政权，据说提婆也是支援政变的人。提婆曾公开要求佛陀交出僧团的领导权，为佛陀斥退，他就带著附和他的数百比丘离开了僧团。

另一件事，是佛陀祖国的灭亡。原来拘萨罗国波斯匿王未继王位前，向释迦族求婚，释迦族自诩为日之种姓，骄傲自大，不肯把王族之女下嫁别族，但又不敢拒绝，乃以女奴茉莉，伪称是王族之女，下嫁波斯匿王子。后来波斯匿继位为王，茉莉夫人生有一子，就是后来的毗琉璃王。毗琉璃王子十余岁时，波斯匿王命他到迦毗罗卫城外家习骑射，那时适当佛陀某一次返乡之前，族人特建了一座讲堂，供佛陀说法之用。这讲堂被视为圣地，不许外人入内。毗琉璃王子一时好奇，就走了进去。事为释迦族人所见，认为女奴之子亵渎了圣地，将毗琉璃王赶了出去，并将他所经之地，挖地换土。毗琉璃太子认为是奇耻大辱，发誓言曰：'有一天我要灭掉迦毗罗卫国，杀尽释迦族人。'

大约二十多年后，波斯匿王年已老迈，而毗琉璃太子正当壮盛，他逼迫父王逊位，自已继位为王。他想起多年前的誓言，乃整顿四兵，讨伐迦毗罗卫。他大军行进中，前哨回　报说：
佛陀坐在前面道旁的枯树之下。毗琉璃王对于释迦族虽然怀恨，但对佛陀仍是十分尊敬。他策马到了前面，下马到佛陀坐处，行礼问讯，并说：

'世尊，那边有很多枝叶繁茂的大树可以遮阴，世尊为何坐在枯树下呢？'

'大王，枝叶繁茂的大树可以遮阴，但是亲族之荫更胜树荫。'

-​-佛陀是说：　拘萨罗和迦毗罗卫是亲族之邦，何必自相残杀呢？

毗琉璃王虽然暴戾，但也为佛陀沉痛的比喻所感动，他为了敬重佛陀，乃下令收兵。

经典上说，佛陀对于祖国的被攻，如是作了三次营救，但毗琉璃王第四度出兵时，佛陀不能再去阻挠，毗琉璃王大军攻下迦毗罗卫，释迦族人几无遗类。

佛陀晚年，另外几件打击，是几个大弟子先他而入涅槃-​-死亡。

佛陀六十岁以前，他的独子罗侯罗就逝世了。但在将近八十岁的时候，佛陀倚为左右手臂、舍利弗和目犍连的逝世，使他感到落寂而凄怆。舍利弗和佛陀年岁不相上下，也快八十岁了，他生了病，回到王舍城的伽罗臂拿伽村疗养。一天，舍利弗的侍者均头，捧著舍利弗的遗物，找到佛陀住所，阿难出来迎住他，均头哭欣舍利弗逝世的经过。阿难去禀告佛陀说：'世尊呀！沙弥均头来告，他说舍利弗去世了。他携来了舍利弗所遗留的钵和衣服。世尊呀！听到这个不幸的消息，我禁不住全身颤抖，觉得四方顿成黑暗。'

佛陀骤然闻知，内心悲怆可想而知，他强忍悲怀，晓谕哭倒在地的阿难说：

'阿难呀！我不是平常就教导你们吗，和心爱的人，总有别离的一天。世界上没有一件东西是永久不变的，一株大树，它的一枝可能先行枯朽，和这道理是一样的。阿难呀！你们要以自己为洲，依靠自己，不可依靠他人；以法为洲，依靠法，不可依靠其他。'

舍利弗逝后不久，又一噩耗传来一目犍连为教殉难了-​-目犍连晚年在外传道，在经过伊私阇山区的时候，为裸形外道发现，自山上推下乱石，目犍连无从躲避，被砸死了。这对晚年的佛陀来说，又是一件痛心的打击。过了不久，在一个月满之夜，举行布萨仪，佛陀在月光下，环视周围众多比丘，不见舍利弗和目犍连的面孔，不禁落寂伤感的说：

'比丘们呀！自从舍利弗和目犍连逝世以后，这个集会，对我而言，真是空虚不堪。不见他们两人的面孔，使我寂寞愁伤。'

佛陀一生，总是安慰悲伤的人，予这些人以慰藉和勉励，他自己从不曾有过如此落寂。不过，佛陀是人间觉者，不是沈缅于愁伤的人。他继续的说：

'但是，比丘们呀！　在这个世界上，没有一个人，或一件事物，是永久不变的，这才是真理。比丘们呀！大树也会有几支枝干先行枯萎，和这个道理一样，他们两个人先我而去了，因为这个世界上，绝对没有永远不变的东西。比丘们呀呀！　所以我说：'以自己为洲，依靠自己，切勿依靠他人；
以法为洲，依靠法，切勿依靠其他。''

-​-洲，是河中之岛，能予舟楫以依靠。以己为洲，以法为洲。就是'自皈依，法皈依。'以上两段教谕，见于《杂阿含经》，也见于《相应部经典。

** 四、最后游化

佛陀最后的一次游行教化，是他八十岁时候的事。《根本说一切有部毗奈耶杂事》记载著佛陀这一次游化的情形：

尔时世尊，告具寿阿难曰：　我今欲往波吒离邑。阿难陀言：
如是，世尊，即与诸毖刍随从世尊，发摩揭陀国渐次游行，行至波吒离邑住底制边。时彼邑人闻佛来至，悉皆聚会至底制边处..

波吒离，是恒河南岸的渡口，即是后来阿育王时代的华氏城。第二天，在渡口上挤满了为佛陀送行的人潮，摩揭陀国大臣禹舍也是送行者之一。他随在佛陀身后，依依不舍的说：'世尊呀！我想在今天世尊经过的地方造一座门楼，命名为瞿昙门，把今天世尊经过的渡船场，命名为瞿昙渡船场。'

禹舍面前所立的，是一个高龄八十的衰病老人，他身著坏色之衣，手持乞食之钵，他没有权势，没有财宝。然而，大臣禹舍和无数送行者，都以最诚挚的心情，最崇高的敬意，来为他送行惜别-​-这就是世尊、这才是真正的世尊，为世人所尊崇的佛陀。

佛陀一行人渡过恒河，向北前进。他们行程极慢，日行十余里，后来到达跋耆国的首毗舍离城。这时已到了雨季，气侯酷热潮湿，佛陀命随行比丘到各地度雨安居，他自己由阿难陪著住入了城外的大林精舍。但八十岁的佛陀，经过长途跋涉之后，受不了酷热和霉雨，竟自病倒了-​-他风湿痛复发，胃肠也不适。佛陀以定力克服肉体的痛苦，挣扎了两三个月，雨季结束，健康渐渐恢复。但是佛陀自己知道，入涅槃已为时不远了。

一天，佛陀在树荫下设座憩息，在旁随侍的阿难说：
'世尊呀！庆幸世尊痊愈，在世尊病重那些日子里，我有天地昏暗无光的彷徨感觉。但想到世尊对僧伽的事情，还没有遗训，一定不致于就此涅槃，我心中才感到安堵。'

佛陀回答他说：'阿难呀！你所期待的是错误的。僧伽还对我期待什么呢？
我已从各种角度，把应说的全说了。在我的说教里面，并没有隐瞒弟子，没有俗说的'老师还保留一点儿'　的秘密奥义。'佛陀继续说：'而且，阿难呀！我不以为我是僧伽的领导者，或是以为所有的比丘都依赖著我；
因此，在我死后，并没有道理由我来指定僧伽的继承人。'

最后，佛陀强调的说：
'阿难呀！你们应该以自己为洲，依靠自己，不要依靠他人；以法为洲，依靠法，切勿依靠其他。阿难呀！现在或者当我去世后，能够以自己为洲，依靠自己，不依靠他人；以法为洲，依靠法，不依靠其他的人，此人即是僧伽中的最高者。'

** 五、大般涅槃

佛陀病愈后，各地结夏的弟子也都回到大林精舍。佛陀带著一行人离开毗舍离，向拘萨罗国的舍卫城前进。途中经过班陀村、诃帝村、祥婆村等地，这一天，到了末罗国的波婆村。波婆村有一个锻冶工人纯陀，是佛陀的在家弟子。他闻知佛陀经过该地，为了表示敬意，他备下了丰盛的午餐，请佛陀一行人光临。

据说纯陀供养的食物中，有一种菌类的蘑菇，汉译经典中叫做'旃檀耳
'的，佛陀吃了这种东西，不久就腹痛如绞(
据巴宙教授所译《南传大般涅槃经》所载：
佛陀食前曾告　知纯陀，将旃檀耳尽奉给他一人吃，其他食物分给众比丘。并且，他食剩余的旃檀耳，命纯陀埋藏于地下，不令他人食　)。佛陀摄心自持，语阿难曰：'我等去拘尸那罗吧！'

佛陀涅槃后，当时各地流传著一首偈子，是这样说的：

我听说是这样的：　吃下了苦工纯陀的供应，世尊得了病-​-是足以致死的重病。

吃下了供养的蘑菇，得了腹痛的病。

而泻肚的世尊说到：　我们到拘尸那去吧。

这首朴实的偈子，是当时各地弟子，对佛陀由发病而涅槃传闻的定型。

佛陀一行人往拘尸那进行，到了中途，佛陀体力已尽，对阿难说：

'阿难呀！我已经疲倦了，到林下休息吧！'

阿难说：'遵命，世尊。'一行人进入一片树林，佛陀说：
'阿难，我今背痛，汝将袈裟折为四重，我欲偃卧以自休息。'阿难在两株并排的沙罗双树下，铺上一个简单的垫褥，佛陀右胁而卧，阿难以一件折为四重的袈裟垫在佛陀背下，以减轻其背痛。

-​-《阿舍经》上说，这片树林名叫牛角沙罗林，在拘尸那城东数里之处。经典上所

的'沙罗双树
'，事实上就是两株并列的沙罗树。这两株树，因佛陀涅槃而名垂千古。

佛陀最后的一句话，是：'人能受法，能行法者，斯乃名曰供养如来。'

说完这句遗言，佛陀进入涅槃。

* 第十二讲　佛经结集与佛教流传

** 一、佛经结集

一代圣哲释迦牟尼世尊，在拘尸那城外的牛角沙罗林涅中，于沙罗双树下大般涅槃，经典上说：'大地震动，流星昼现，诸方炽然，于是虚空中诸天击鼓..'。

佛陀涅槃，随行的弟子，大多数伤感异常；只有少数证果的弟子静坐冥想，默念佛陀教法：'成者必坏，盛者必衰，生者必死，合者必离。'感叹著虽佛陀亦不能逾此法则。这时有一个名叫跋难陀的比丘，他是 '六群比丘'中的一个，竟当众宣称：'诸位同修们呀！不必悲伤了，佛陀在世的时候，时时以戒律约束我们，使我们不得自由，如今佛陀不在了，从现在起，我们可以随心所欲了。'

当时心情悲伤的众比丘听了都保缄默，而上座弟子大迦叶听到却十分忧心。他恐僧团戒律废弛，'如来甚深妙法成灰烬
'，应把佛陀遗教，结集制为成典，庶可永久做弟子们的指导，于是在为佛陀治丧完毕后，发起遗教结集。此事得到摩揭陀国阿阇世王的支援，僧团中也选出五百名上座比丘，在王舍城郊外的毕波罗窟进行结集。

结集，我们想像中是'编辑 '的意思，事实不然，那是五百比丘共集一堂，选出一名比丘，背诵佛陀说过的教法或戒律。一段一段的背诵出来，由上座长老鉴定无误，再由全体合诵，如无异议，就算'定稿 '。在这次结集中，由大迦叶任'主席 '，由持戒第一的优波离诵出律藏，由多闻第一的阿难诵出经藏-​-原始圣典《四阿含经》 (即长阿含、中阿含、增一阿含、杂阿含)　。为期三月结集完成。此称为五百结集或上座部结集。

据说，在毕波罗窟结集进行之际，未与斯选的千余比丘，亦别为集会，由师婆迦主持，另行结出了经、律、论、杂、禁咒五藏，此称为窟外结集，或大众部结集。

佛陀灭度后，僧团由大迦叶领导。大迦叶苦行第一，齿德俱尊，众无异言。二十年后，大迦叶传法于阿难。阿难这时已七十多岁，他多闻第一，众人翕服。这以后，阿难传法于末田地，末田地传法于商那和修，商那和修传法于优婆鞠多。佛经上说：'百年之间，五师相传，法水一味。'僧团仍然维持著佛陀住世时的教风。但在佛陀灭度后一百一十年的时候，由于'十事非法诤 '事件，教团开始了第一次分裂。 -​-近代学者称未分裂前的教团为原始佛教，亦有称佛陀住世时的教团为根本佛教。而分裂后的佛教，后世称之为部派佛教。

十事非法诤事件件，发生在毗舍离城，是该城比丘在戒律上的偏差行为。毗舍离城的比丘，于每月的八日、十五日等几天，持著盛了水的钵，站在街头向路人募化，声称投钱入水者可获吉祥。路人有投钱者，亦有非议出家人不该向人募化财物者。据说的耶舍长老途经该地，获知此种情形，不以为然，乃加以制止。该城比丘不服，反而共逐耶舍。耶舍奔走各地，欣诸上座长老。诸长老一致谴责，毗舍离比丘也遥为声辩。

事实上，毗舍离城比丘违犯戒律的行为不止这一件，计有十项之多。《五分律》中记戴著'十事非法诤 '的内容，其名称是： 一，盐姜合共宿净。二，两指抄食净。三，复坐食净。四，越聚落食净。五，酥油蜜石蜜和酪净。六，饮阇楼伽酒净。七，作坐具随意大小净。八，习先所习净。九，求听净。十，受畜金银净。

以上十条，都是不合戒律的，违犯者是不净。而这些比丘们认为是'净' ，那就是化非法为合法。那时佛灭未久，竟有比丘提出这种主张，就难怪上座部长老们认为事态严重。最后双方协定重行结集，以论是非。这次结集在毗舍离城召开，与会者七百人，由耶舍长老主持，双方各举出四人为审辩，会中重诵戒律，逐事审辩，结果断定毗舍利城比丘非，上座长老获得胜利。据说该城比丘不服，另行集合了上万人自行结集，自此僧团分裂为上座、大众两部，各行其是。

又过了一百二十多年-​-西元前二五一年，印度孔雀王朝阿育王在位时代，又有第三次结集的举行。原来阿育王崇信佛教，对僧伽的供养十分丰厚，一般外道穷于衣食者，也改换僧装，混入僧团，一方面获得衣食供养，同时把外道的教义混入佛法经义中。阿育王为辨别真伪，乃有第三次结集之举。地点在国都华氏城-​-即早年的波吒离邑。由长老目健连子帝须主持，千名精通三藏的比丘参加。据说，这一次结集，会中诵出经、律、论三藏，目犍连子帝须以会中辩论的记录，编辑为一部　《论事》 ，计有千条之多，记下了正反面辩论的意见。后来有两百六十多条传下来，这时上座部大众部又各自分裂，《论事》 中已有化地部、犊子部的名称。

在佛陀入灭后六百年间，贵霜王朝迦腻色迦王时代，还有一次第四次结集。以世友菩萨为上首，有五百大德比丘及五百菩萨(在家优婆塞)参加，造出注释经律论三藏的释文各十万颂-​-即《优婆提》十万颂以注镦一释经藏，《毗奈耶毗婆沙》十万颂以注释律藏，《阿毗达磨大毗婆沙论》十万颂以注释论藏。后来只有《大毗婆沙论》流传下来，其他的已失传了。

这一次结集有了文字记录，据说是镂于铜片之上，封于石函之中，不许妄传国外。

** 二、部派佛教时代

由佛陀灭度后一百一十年，以'十事非法诤'导致佛教分裂(另一说谓佛教分裂系大天五事所致)，到西元一世纪中叶，这四百年左右，在佛教史上称为部派佛教时代。

在第一次结集时，就有上座部和大众部名称的出现，但真正分裂是第二次结集以后的事。所谓'上座'二字，是以比丘出家久暂计算的。由初出家到九年以内名曰下座，出家十至十九年名曰中座，二十年至四十九年名曰上座，五十年以上则称长老。而上座比丘及长老，，多为老成持重，思想较为保守者；至于'大众'二字，则多为下座年轻比丘，人数众多，多为思想较开明而进取者。最初分裂，只分为上座大众两部，后来这两部又各以对法义见解之不同，由大众部中又分裂出八部，由上座部中又分裂出十部，加上座大众本部，共有二十部之多，一般之为小乘二十部。此处限以篇幅，不能一一细述，略举具有代表性者如下：

在上座部中，以最早分裂出来的说一切有部为代表。上座部本来是继承大迦叶的遗教，首弘经教，次弘律论。佛陀入灭后三百年间，长老迦多延尼子，为对抗大众部盛倡新说，强固本部理论，他主张首弘论藏，经、律为次，以此与上座部分裂，自成说一切有部。他造《阿毗达磨发智论》，组织有部教义。第四次结集时所造的《阿毗达磨大毗婆沙论》，就是以《发智论》为主依，《六足论》为旁依而编纂完成的。有部哲学理论，主张'我空法有'，并且是'三世实有，法体恒有'。最具体扼要阐述有部理论的著作，是世亲菩萨所造的《阿毗达磨俱舍论》，也就是中国俱舍宗所依的论典。

大众部的理论，与上座部是对立的。例如该部最早分裂出来的一说部，认为'一切我法唯有假名，都无实体'。而'名' 就是'说' ，故名一说。大众部还分出了一个说出世部，认为佛说的法，都是出世间之法，故名说出世部。大众部还分出了一个多闻部，后来在多闻部出家的诃梨久跋摩，造《成实论》，其学说就是'我法皆空'，也是后来中国成实宗所依的论典。

** 三、大乘思想的兴起

佛陀灭度后五百年顷，大约在西元第一世纪间，大乘思想兴起，大乘经典逐渐出现。

所谓大小乘的'乘'　，是运载的意思。小乘是小的交通工具，如鹿车羊车，只能用以自载； 大乘如牛车象车，自载兼以载人。而所谓小乘，是大乘佛教兴起后，所加给以前佛教贬抑性的名称，而不是部派佛教自居为小乘。

大乘思想的兴起，自历史观点来看，仍是从部派佛教发展出来的。当然并不是由部派佛教演变为大乘佛教，而是大乘佛教受到部派佛教的影响，这其间，受到大众部的影响尤大。大乘思想的特征，在于其利他精神-​-即所谓菩萨乘的精神。照大乘学者看，小乘之所以为小，在于其思想保守，墨守成规，对经典的解释固定化，对戒律的条文一成不变。具有大乘思想的无名学者认为：与其追求经典文字表面的意义，无宁追求经典文字背后的精神。在这种观念思想影响下，大乘经典逐渐出现，而最早出现的是般若一系的经典。

如此说来，大乘经典岂不是非佛陀所说了么？ 诚然如此，'大乘非佛说'不是新课题，它在国际学界已讨论了数百年之久。不过，当初编纂经典，冠以'佛说' 的那些无名天才学者，他们并没有伪造经典的意识，他们充满信心的认为：唯有这样说，才是佛陀的本怀。在出现于四、五世纪间的《大乘庄严经论》卷二中称：'有人嶷此大乘经典非佛所说，云何有此功德可得，我今决彼疑网，成立大乘真是佛说、、、、、'。论中列举出了八点理由，其中有一条大意说：如此深广的妙法，不是佛说，谁能说得出呢？

本来，佛法不一定须由佛亲口所说，因为宇宙间本然的理则，是佛所证悟，而非佛所制定。佛陀曾说：'如来出世，若不出世，诸法法性法住，法界安住。'佛说的法，是宇宙真理，佛弟子与佛所证的真理，程度上虽有不同，而真理的本质无异。佛弟子以其所证悟的真理对众宣说，也可称之为佛法。因此，佛经中载有佛法系由五种人所说，即佛说，佛弟子说，天人说，神鬼说，化人说。 不过，编纂大乘经典的学问僧们，以婆罗门种姓出身的学者居多，他们自幼都受过婆罗门教育，以后才皈依佛教出家，所以后世的佛经有明显的'梵化' 倾向。并且对佛陀的圣化也逾趋明显，这就模糊了人间佛陀的本来面目。

** 四、中观学派与瑜伽学派

西元第一世纪兴起的大乘佛教，一般都把他分为三期。首先是大乘经典次第出现，继般若一系的经典之后，宝积、华严、法华、维摩、及净土经典也先后出现了。而在西元三、四世纪间，以龙树菩萨创立的'中观学派'
为大乘佛教的主流。中期大乘，约当西元五、六世纪二百间，涅槃、胜鬟、菩萨藏、解深密等经先后出现，无著、世亲的'瑜伽行学派' 成为此一时期的主流。晚期大乘，约当西元七至十世纪，此时期内密教经典出世，密宗盛行，到了西元十一世纪末期，印度佛教就灭亡了。

印度一代大哲龙树，住世年代约在西元一五零至二五零年之间，他是南印度婆罗门种　　姓，自幼受婆罗门传统教育，后来皈依佛教。当时南印度已有大乘经典流行，他读之不以为走足，传说他游行北印度时，自雪山地区一个老比丘处得到一部分大乘经典，又在大龙族聚居之地得到许多大乘经典，这样就更充实了他的大乘理论。他回到南印度，把早期的般若思想组织起来，完成了'缘起性空' 的宗教哲学体系。

原来龙树住世时代，印度思想界的潮流，一方面是外道的诸法或常或断思想，一方面是小乘有部的'我空法有' ，且'三世实有，法体恒有' 思想。他造诸论典，'破邪显正'　，这种思想表现在《中观论》一书中。如'八不偈'所称：

不生亦不灭，不常亦不断，不一亦不异，不来亦不出，

能说是因缘，善灭诸戏论，我稽首礼佛，诸说中第一。

八不，其实就是全盘否定-​-自诸法空性上，否定小乘、外道的生灭、常断、一异、来出诸戏论。诸法空性，亦表现在
'三是偈'上。即所谓：

诸因缘生法，我说即是空，亦为是假名，亦是中道义。

关于缘起，见本文第五讲，此处不赘。龙树的著作很多，有千部论主之称，除 《中观论外，主要的尚有 《十二门论》 ，《大智度论》 等。继承龙树学说的，是他的弟子提婆。提婆所著的　《百论》 ，与龙树的 《中论》 及 《十二门论》 ，合称三论。是后来我国三论宗所依论典。而龙树、提婆这一系的理论，在印度被称为'中观学派' ，亦称'空宗'。

龙树、提婆的空观，是以诸法无自性立论，并非徒持空见，妄计一切皆空。惟传至后世，则流为'顽空' -​-学者执一切皆空，于世俗谛，不施设有； 于胜义谛，真理亦无。此谓之'恶取空'　，亦称'沈空' 。佛灭后九百年倾，无著、世亲两大论师出世，为矫治当时沈空之弊，而标示'有' 义。此有，非是小乘外道之诸法实有，而是破我法二执后所显示的'真空妙有' 。这在印度称为'有宗' ，亦称'瑜伽行学派' 。

无著住世年代，约为西三九五至四七零年之间。据说天宫兜率内院的弥勒菩萨，应无著之请，在中印度阿瑜遮那国，为无著说 《瑜伽师地论》、《分别瑜伽论》 、《大乘庄严论》、《辩中边论》 、《金刚般若论》　五部大论，无著承弥勒之说，与其弟世亲把五部大论做了一番综合整理工做，依此建立'瑜伽行学派' 。但弥勒不是历史上实有的人物，也许世间另有一个名叫弥勒的人。或者，五部大论根本是无著的著作，假托弥勒之名行世的。更可能的是，早在无著之前，就有许多无名的饱学的瑜伽师，而无著是继承他们学说而加以发扬的。

西元七世纪，玄奘大师游学印度，带回此学派经典，依此建立了中国的法相唯识宗。

印度的大乘佛教，以此中观、瑜伽二派为代表。唐代义净于　《南海寄归内法传》称：

'所云大乘，无过二种，一则中观，二乃瑜伽。中观则俗有真空，体虚如幻；瑜伽则外无内有，事皆唯识。'

** 五、南传佛教与北传佛教

近代欧洲的佛学研究者，以印度为中心，把佛教区分为南传佛教和北传佛教。南传佛教，最早是以锡兰为中心，包括以后传布的缅甸、泰国、柬埔寨、寮国等地区；

北传佛教最早是以中国为中心，包括著以后的西藏、日本、朝鲜等地区。所谓南传北传，只是地理上的区别，并不以大小乘佛教为区分，大致上说，南传者为小乘佛教-​-他们自己则称为上座部佛教；而北传者则均为大佛教。

南传佛教中心锡兰之有佛教，始于西元前三世纪中叶，阿育王在位时代。阿育王时代曾有第三次结集，结集之后，阿育王派遗了九组传教师赴国内外各地传布佛教，其中派往师子国 (锡兰古名) 的一组，是摩泗陀长老。摩泗陀是阿育王之子，在上座部出家，所以传入师子国的是上座部经典。当时也是以口传口的说诵，并没有文字记录。到两百余年后，才以文字记录下了摩泗陀长老口的三藏。到西元五世纪中叶，中印度大学者佛音到了锡兰，把原来的三藏经典译为巴利文，并加以注释，就是流传到现在的'巴利文圣典' 。加巴利文下圣典巴利文圣典，也分为经、律、论三藏，其内容如下：

律藏：

(一) 戒本篇： 1、波罗夷-​-破门罪。　2、波逸提-​-赎罪。

(二) 戒因缘篇： 1、大品-​-大集。　 2、小品-​-小集。

(三) 律藏后篇：　附属。

经藏： 又称巴利五部。

(一) 长部经典：　三十四种。

(二) 中部经典：　一五二经

(三) 相应部经典：　七七六二经。

(四) 增支部经典：　十一集，九五九七经。

(五) 小部经典：　含《法句经》等十五分。

论藏： 含《法集论》、《分别论》、《界论》、《双论》、《发趣论》、《人设论》、《论事》等七种。　

藏外： 含《弥兰王问经》、《大王统史》、《小王统史》、《岛王统史》、《净道论》、《善见律注》等六种。

北传佛教，最早是经由西域诸国传到中国，时间约在西汉末年-​-西元世纪开始之初。而佛经的翻译，一般是认为东桓帝时代，安息国沙门安世高抵洛阳　(西元一四八年) 后开始的。自此之后，历经魏晋时代佛经的翻译，南北朝时代法义的传播，到隋唐两代开花结果。大乘八宗次第建立，教理宗义灿然大备，完成了具有中国特色的佛教。

惟自唐武宗会昌法难以后，佛教盛极而衰。唐代末年，沈镇割据，烽火四起；五代十国，王朝交叠，战乱频仍。这时佛寺荒废，经籍散逸，隋唐两代鼎盛三百年的教，至此零落殆尽。宋代建国，太祖有意复兴佛教，唯此时 (西元九六八年以后)　印度可供传译的经典已少，中土弘扬法义的高僧渐稀，以致后继乏力，成就有限。宋室南渡，佛教益发不振。元人入主中国，崇奉喇嘛教，中土僧侣，唯有抠亦接足，丐其按颅摩顶而已。

明季以民间秘密宗教盛行，政府为镇压邪教，法令严苛，以此也限制了佛教的发展。满清入关，继元人作风，崇奉喇嘛教以笼络边疆民族，中土佛教益发衰微。清季乾嘉之世，北方有川陕楚三省教匪之乱、天理教之乱； 咸同年间，南方有太平天国之乱，兵连祸结，举国荡然，佛教亦受到无情摧残，不绝如缕，几到了濒于灭绝境地。

清末民初，缁素两众中人才辈出，法义之学重见弘扬，僧侣教育蓬勃日上，佛教重见复兴之望。未几八年抗战爆发，继之内战复起，以至大陆变色，佛教遭遇空前浩劫，迄今尚未复原。近二十年来，台湾佛教隆盛，堪比盛唐，然亦不无若干隐忧存在。如何护持正法，延佛慧命，就有待于我们佛们弟子共同努力了。

