#+OPTIONS: toc:nil ^:nil
#+TITLE: 佛经小故事
#+begin_export md
---
layout: post
title:  "佛经小故事"
date:   2019-12-30
tags:
      - 佛学
---
#+end_export
#+TOC: headlines 1
* 苏卡的故事
  :PROPERTIES:
  :CUSTOM_ID: 苏卡的故事
  :END:
如果没有从本源上认清身心，就会导致自我感的产生，而自我感会招引贪欲、痛苦、生死以及无休无止的轮回.\\
　　佛陀时期，有一位七岁的小沙弥，名字叫做「苏卡」。\\
　　有一天，他随着舍利弗拖钵路上看到农夫正在引水灌溉，他问舍利弗：\\
　　「尊者！水可以被引导到任何地方吗？」\\
　　舍利弗说：「是的，只要懂得技巧。」\\
　　接着，他看到制作弓箭的人，用火锻烤竹子，使弯曲的竹子变成直的。也看到木匠正在切割木材，用来制作车轮。苏卡心里想着：\\
　　「这些没有意识的河水、竹子和木材，都可以加以调伏，做成有用的东西，而拥有意识的我，为什么不能调伏自己的心呢？」\\
　　经过这番思考后，他向舍利弗请求回到禅堂禅修。回到禅堂后，他不断地观察自己的身心，终于调伏了无明习性，灭除了痛苦，成为一位圣者。

* 伊估达那的故事
  :PROPERTIES:
  :CUSTOM_ID: 伊估达那的故事
  :END:
佛陀时期，在舍卫城郊区的一个果园里，住着一位比丘，名字叫做”伊估达那”。\\
他只能熟记一首佛陀所教的偈颂，但是彻底体会其中的道理。每次他读完这个偈颂，果园的树神们就热烈的鼓掌称赞。有一次，两位博学多闻，并且常常说法的比丘，带着一群徒弟经过这个果园，问伊估达那在这么偏僻的地方，会有人来听法吗？他说：果园的树神都会鼓掌称赞。因此，这两位比丘便在园中说法，舌粲莲花，滔滔不绝，如长江大河。但说完后，果园里却是静悄悄的，连树叶落地的声音也没有。他们就请伊估达那说法。他一读完这个偈颂，园里一如往常地向起热烈的掌声，并且大声叫好。这两位比丘的徒弟们认为这些树神偏心，对伊估达那比较友好，因为他所讲的根本就很平常，不如他们师父的精彩。佛陀听到了这件事，就对弟子们说："比丘们！我不认为听了许多经典常常说法的人，就一定精通佛法。相反的，虽然听得不多，却能体会真理，经常保持正念的人，才是真正精通佛法的人。"从佛陀的开示，我们知道法的核心在于亲身体证，要能一直保持觉性，活在当下，才是真正的受用到佛法，并且真正护持着佛法。

* 提沙的故事
  :PROPERTIES:
  :CUSTOM_ID: 提沙的故事
  :END:
有一天，佛陀宣称四个月后，他就要入灭了。很多尚未证得圣位的比丘，感到很伤心，就整天紧紧追随在佛陀的身边。但是有一位比丘名字叫做”提沙”却没有整天跟着佛陀，反而到静僻的地方禅修。其他的比丘带他去见佛陀说：
"世尊！提沙比丘不像我们这样敬爱您、尊重您。他躲在一边，自行其是。"
提沙比丘说："我只是加紧用功，希望在佛陀入灭前，证得圣位，达成灭苦的目标。"
佛陀听完后，加以赞叹说："凡是敬爱和尊重我的人，应该效法提沙比丘。比丘们！奉行我所教导的出世间法，精进禅修的人，才是真正的尊敬我。已经尝到佛法的滋味而喜悦的人，将免于恐惧和邪见。"

* 朴娜的故事
  :PROPERTIES:
  :CUSTOM_ID: 朴娜的故事
  :END:
佛陀时期，有一位女仆名字叫做”朴娜”。有一天为主人桩米，晚上继续加班，看到比丘们很晚才休息，她心里想着："我因为命苦，必须工作到这么晚。这些比丘们为什么要这么晚才休息呢？"\\
第二天一早，她做好糕饼，走在路上，看到佛陀正拖钵而来，就将糕饼供养佛陀。\\
用完了餐后，佛陀告诉朴娜："你因为必须工作，因而缺少睡眠时间。比丘们因为必须常保持觉性，所以才晚睡。但是不管什么人，都应经常保持清醒，使觉性不断。"

* 波斯匿王的故事
  :PROPERTIES:
  :CUSTOM_ID: 波斯匿王的故事
  :END:
佛陀时期，印度憍萨罗国的国王叫做”波斯匿王”，长得身体肥胖。
有一天，波斯匿王吃完丰富的早餐后，坐车到祗树给孤独园聆听佛陀说法。他全身冒汗，气喘喘的来到佛陀跟前，听没几下子，就开始点头，猛打瞌睡。\\
他对佛陀说："我吃完早点后，身体一直不舒服。" \\
佛陀告诉他："过量的饮食，会使身体不舒服。" \\
接着建议他安排一位专员，在每次用餐前就提醒波斯匿王："大王！减少食量，身体就会健康而苗条。"波斯匿王很听话，便安排了一位专员。几个月下来，果然国王减肥成功，变得精力充沛，行动迅速，听经不再迟到，而且整堂课都能保持觉性，下课时充满法喜。那位专员也被加了薪。\\
后来，波斯匿王证得了流果的圣位，具足了”四证净”，也就是具足了对佛、法、僧的净信以及圣戒成就。

* 年青比丘的故事
  :PROPERTIES:
  :CUSTOM_ID: 年青比丘的故事
  :END:
佛陀时期，在舍卫城里有一位年青的比丘去找一位长老比丘住在一起，这位长老比丘是他的舅舅。
住了不久，年青的比丘生起了还俗的念头。\\
这一天，他正在服侍着长老比丘，内心想着："还俗后，我就卖掉衣物买一只母羊，接着母羊生了许多只小羊，不久就存有足够的钱可以娶妻生子。然后，我就驾着车，带着太太和儿子来看舅舅。途中，我想抱着儿子一起来驾车，太太却说：不可以！要专心的驾车。我坚持把儿子拉过来，在拉扯之间，儿子掉下车子，给车轮辗过了。我非常生气，就拿起木条打太太，太太立刻闪到一边去。"\\
这位长老比丘有”他心通”，知道年青比丘的心念，就叫道："你自己打不到老婆，怎么来打舅舅？"年青比丘不好意思，就跟他舅舅到佛陀那儿。佛院说："人们的心到处乱跑，甚至跑到非常遥远的地方。要努力调伏自己的心，从贪瞋痴的烦恼魔中，解脱出来。" \\
听了佛陀的开示，这位年青比丘好好地收摄心思，不久就证得了预流果的果位。\\
因此，在禅修时以及平常时，都要一直保持觉性，不要胡思乱想，要好好的活在当下，一直觉知自己的动作，能够如此，目的地就不遥远了。

* 车匿的故事
  :PROPERTIES:
  :CUSTOM_ID: 车匿的故事
  :END:
在禅修的过程中，要排除傲慢和瞋恚的心理。傲慢是一种看低别人的心理。瞋恚是一种生气的心理。\\
当年印度的悉达多太子，小时候有一位玩伴，名字叫做”车匿”，或叫做”阐陀”。当悉达多太子离开王宫出家时，由车匿一人驾车送行。等到太子成佛后，车匿也来出家修行。但是车匿跟所有的比丘们都相处得不好，因为他认为自己很早就伴随佛陀，交情比别人深，因而生起了傲慢的心理。他对佛陀的上首二大弟子舍利弗和目犍连，特别看不顺眼。佛陀劝了车匿几次，仍然改不了他的傲慢与瞋恚。\\
佛陀入灭后，比丘们依照佛陀临终前的指示，对车匿施行”梵罚”。梵罚就是大家都不跟他说话。车匿只好自己在鹿野苑附近精进修行，但是证不了果。这时他的傲慢与瞋怒开始降温，想起了阿难尊者，便去找阿难指点，他问道：\\
"阿难尊者！身心一切都是无常和无我的。那么，做了善恶业后，是谁承受果报呢？还是没有人承受果报呢？"\\
阿难尊者看到车匿的傲慢与瞋恚已冷却下来，知道他已是接受佛法的好根器了，便向他解说甚深的”缘起”的道理：\\
『在身心的连续变化中，并不存在一个固定不变的我，由于没有一个固定不变的我在承担果报，所以不落入”常见”。另一方面，在身心的连续变化中，有一后续的身心存在着，这个后续出现的身心承受着果报，所以不落入”断见”。』\\
经由阿难的指点，车匿以强大的觉性看清身心现象的缘起过程，灭除了常见和断见，处在中道而证得了圣者的果位。\\
所以，大家要好好守护自己的心，不要给傲慢、瞋恚或无明所占据。

* 大象的故事
  :PROPERTIES:
  :CUSTOM_ID: 大象的故事
  :END:
古时印度，有一只大象，年轻时非常强壮，打起仗来，神勇无比。但是岁月不饶人，年纪一大，却是衰弱不堪。\\
有一天，它走到池塘边喝水时，不幸陷在泥中，脱困不得。旁边的人们，费了一番力气，也奈何不得，因为这只大象实在太重了。国王知道后，就派一位驯象师去处理。驯象师到达大象陷身的地方，观察了一下子，就叫人吹打战鼓。大象一听到隆隆的战鼓声时，仿佛又回到了战场，不由得精神大振，一鼓作气，就脱离了困境。\\
当年的佛陀以这只大象的故事告诉弟子们："比丘们！你们要像这只大象自行脱困一样，要奋力的从烦恼中解脱出来。"现在你们正在禅修中，也要依靠自己的力量，以强大的觉性，将自己从昏沉、妄念、无明的枷锁中拔脱出来，不要只想依赖外力，要像大象一样靠自己的力量挣脱出来。靠自己得来的自由，更是弥足珍贵。

* 珠宝商的故事
  :PROPERTIES:
  :CUSTOM_ID: 珠宝商的故事
  :END:
将觉性提高后，我们才有能力以智慧与慈悲来面对生活中突发的事件。没有觉性，我们就会被贪、瞋的习性拉着跑，做出错误的行为。\\
佛陀时期，舍卫城有一位珠宝商，能打造精美的首饰，家中养了一只白鹤当宠物。有一位长老比丘，名字叫做”谛沙”，天天来这儿托钵。有一天，他照常来托钵，在珠宝商的店里等着，这时，波斯匿王的使者送一颗红宝石来加工，将宝石交到珠宝商的手里就匆匆离去。珠宝商将宝石放在店内桌上，到里面洗完手，出来一看宝石不见了。他问家里的人和长老，都说没有拿。但是，他认为没有其他外人，只有谛沙长老在场，因此一定是他拿去了。\\
珠宝商的太太说："过去十二年多来，我没有看过长老做错过任何事。我们宁可接受国王的惩罚，也不要冤枉好人。"\\
但是珠宝商在焦虑与气愤的当下，哪里听得进太太说的话，反而拿起棍子把长老打得头破血流。店中的白鹤看到滴到地上的血就跑来吃，珠宝商这时正在气头上，一脚把白鹤踢死了。\\
谛沙长老看到白鹤死掉了，便劝珠宝商息怒，告诉他：当他进去洗手时，白鹤把红宝石误以为是食物吃进肚子里了。\\
珠宝商把白鹤的肚子切开，果然找到了宝石，也知道自己做出了错误的行为，请求谛沙长老原谅。长老说：我对你始终没有一丝恨意。\\
由于谛沙长老有强大的觉性，能以慈悲心看待白鹤，最初宁愿自己的身体受苦，也不愿白鹤被杀害。\\
珠宝商事后该怎么办呢？就应该好好培养觉性，改变自己的牛脾气。只有在强大的觉性下，才能看清自己念头的生起，当下才能切断后续的怒气，如此就不会做出错误的行为。否则，若没有培养出觉性。只有懊悔，或者找人来消灾解厄，都是无济于事，一旦面临相同的状况，又会一再重演悲剧。所以，最重要的事是我们要好好培养觉性。

* 梵吉沙的故事
  :PROPERTIES:
  :CUSTOM_ID: 梵吉沙的故事
  :END:
禅修的目的，在于脱离三界的束缚，得到真正的自在，不被世间的各种现象所迷惑。\\
佛陀时期，有一位婆罗门，名字叫做”梵吉沙”。他有一项特别的本领，只要将死人的头盖骨拍一拍，就知道这个死人是投生到天上、人间或是地狱。他的朋友们拥着他到各乡市巡回表演，村民们向梵吉沙询问死去的亲友们投生到何处去，问完后，有的给十元、二十元或一百元不等，一路下来，真的是财源滚滚。\\
有一天，梵吉沙来到祇数给孤独园附近。他的朋友们看到当地民众都去听佛陀说法，就向他们说："现在来了的一位摸骨大师，能够知道你们死去的亲友生到何处去，赶快过来瞧瞧，机会难得。"佛陀的信徒们说："佛陀是谁也比不上的，他才是究竟觉悟的人。"梵吉沙的朋友认为这是一句挑战的话，就拥着梵吉沙来向佛陀挑战。\\
佛陀知道了他们的来意后，便叫人准备好五个头盖骨，请梵吉沙回答。前面四个依次是投生到地狱、畜生、人间及天上的头盖骨，梵吉沙都答对了。但是第五个头盖骨，他拍了又拍，瞧了半天，冒了好多汗，却回答不出来。这个头盖骨确实难倒了他。\\
佛陀说："梵吉沙，不知道了吧。我知道这个头盖骨的主人生到何处去。"\\
原来这第五个是一位阿罗汉的头盖骨。梵吉沙便请求佛陀教导他如何知道这第五个的技巧。佛陀说他要先出家，加入僧团，才能教他。\\
梵吉沙为了学会这技巧，便受戒成为比丘，遵照佛陀的指示，整天观察自己的身体。\\
他很努力的禅修，培养出强而有力的觉性，终于看清自己身心的实相，灭除了痛苦，证得了阿罗汉的圣位，从三界的束缚中完全解脱出来了。\\
后来他的朋友们来找他，要他继续巡回表演，以特异功能来赚钱，梵吉沙说："你们回去吧，我不再加入你们的行列了。"一位内心拥有觉性的人，将过着安详而踏实的生活，不会沉迷于特异功能。一位内心拥有觉性的人，将过着安详而踏实的生活，不会沉迷于特异功能。\\
这句话说的多好啊！今天我们有机缘接触了佛法我们要珍惜今天的成果啊！不要因为个人的嗔心而毁了自己的道行。发四无量心：一、慈无量心、二、悲无量心、三、喜无量心、四、舍无量心.

* 理发师优波离
  :PROPERTIES:
  :CUSTOM_ID: 理发师优波离
  :END:
https://blog.sina.com.cn/s/blog_6271164c0101fwf0.html

在王舍城举行的结集经典的工作上,优波离（Upali）被推选为诵出戒律的长老，佛教往后的发展中，优波离是不可或缺的一位，佛陀在世时,特别赞誉为持戒第一。

优波离的一生成就,散见于杂阿含诸经等,《佛本行集经》优波离因缘品第五十五，有详尽叙述，还加上一段本生神话，这是后人总整理出来的。另外南传《中阿含部》-优波离经及北传《中阿含》一三三-优婆离经（大正藏一、六二八页。）也有出现一位优波离居士，本经乃述离系派(苦修尼犍子派)之徒，受世尊的教化而成为佛弟子。离系派之师若提子(尼犍子)、知之而吐血。其故事在南北传大体一致，北传还加上若提子其后往波瓦国而死。这一位先入苦修外道再归依三宝的优波离居士，并非首陀罗的理发师，因此被否认为持戒第一的优波离。

** 出身首陀罗

优波离出生于印度四种姓中的首陀罗族，也就是是奴隶阶级，在古印度受社会的歧视，不得受教育，不得和婆罗门丶剎帝利对谈和平起平坐，连双眼都不能正视。

当优波离长大后，父母送他去学做一个剃头匠，做为将来谋生餬口的技能。优波离是一位工作严谨又易于受教的孩子，加上天赋，不久他就能把各种剪发技能全都学会。他纯良忠实的本性，获得释迦族的信任，让他在宫中，专门负责为一些小王子们理发。也成为跋提、阿那律等王子的好朋友。

** 为佛陀剃发入四禅

佛陀回迦毗罗卫城省亲时，到了理发的日子(佛陀也是圆顶光头)，王宫推荐由理发师优波离担任。这是一件光荣神圣又紧张的任务。据《佛本行集经》[fn:1]描述，当时有母亲陪同，优波离谨慎的操刀，优波离母问佛陀："世尊，优波离剃佛须发，能胜任吗？"佛陀言："虽能胜任，但身体太低了"。优波离修正姿势一心不乱,即入初禅。接后母亲又问佛陀，佛说:"其身太仰。"优波离再次修正姿势一心不乱,即入二禅。母亲又问佛陀，佛说:"入息稍复太多。"优波离调整吸气一心不乱,即入三禅。母亲又问佛陀，佛说:"出息稍太多也。"优波离调整出气一心不乱,即入四禅。剃发须之后,佛告诸比丘："诸比丘！你们快取优波离手中剃刀，勿使倒地。因他已入四禅。"优波离的母亲听后，即从优波离手中取下剃刀。

这是一段很神奇的际遇，看出佛陀的细心观察与教导，也得知优波离的专注严谨，这种一丝不苟的个性，造就了优波离守戒不阿，成为众比丘中洁身如玉，谨言慎行的戒德大圆满。

[fn:1] 佛本行集经 属于北传经典 故此这段描述并不可靠。
** 优波离出家

在佛陀返乡之后,有跋提、阿难、阿那律等七王子(有说五百諸釋童子)要求剃发出家，剃发须的工作当然由优波离来完成。王子们离家前把上衣珠宝都脱下来送给优波离，优波离想:"这些王子大富大贵的家室都想出家.我今何事不出家也？"心意一决，便即捨施瓔珞等，直奔佛陀住处，在舍利弗陪同下,頂禮佛足说:"善哉！世尊！唯願聽我隨佛出家。"

佛陀应允说:“你很有善根，将来一定能宣扬我的正法。在此之前，跋提王子等已先来此要求剃度，但他们要经过七日的自修，等他们放下身段俗气后再出家。所以优波离是早王子们先得佛陀应允出家为师兄。

经过七日，佛陀叫出跋提王子等七人和大家见面，意外的见到已现比丘相的优波离，大家都很惊奇，都踌躇不知如何打招呼。佛陀对七人说："「汝等比丘！咸可俱來禮优波离上座比丘。」"跋提王子等七人，听佛陀说法后，都虚心的向优波离顶礼。佛陀对优波离比丘说道："你应该以兄长的身分对待他们。"

现代的人要出家受戒,只要父母允许,具单身身份，六根具足就被许可。在当时阶级悬殊的印度社会，一个被人认为下贱的佣人首陀罗，出家后的名次又在王子之前，史无前例。佛陀的教法，是平等慈悲的，不分职业的贵贱，只要能遵守清净的戒律，是谁都可以出家，都可以证得无上正等正觉。真正是'百川河水，同流入海；四姓出家，同一释姓。'


** 向佛问戒持戒第一

优波离的出家，使佛陀制定的种姓平等得以实现，优波离后来的成就，也没有辜负佛陀的期待！就在优波离出家的那年夏天，僧团内举行安居的时候，优波离因精进修道而开悟，他在生活上很重视行住坐卧四威仪。对佛制定的戒条，都能一一严加遵守，从不毁犯，他自然的成为教团中的上首，受四众的尊敬。

优波离大部份的时间都跟随在佛陀左右,除非受佛陀之命前往他处主持羯摩，一般常住在舍卫国的祗园精舍内。从《律藏》里可看到，他经常向佛陀请示戒法。

有一次，在迦毘罗卫城有一个释族的黑离车女，年纪轻轻的不幸丧夫寡居，不少异族的青年向她追求，又有丈夫的弟弟从中作难，想占她为自己的妻子。居心不良的夫弟不得欢心，向官府报告说："她和外族青年私通！"这可是重罪。黑离车逃向舍卫城，并且在舍卫城跟随比丘尼团出家。迦毘罗卫城释迦族的官府，得知黑离车女逃到舍卫城，他们即刻作书向波斯匿王要人。波斯匿王调查后,知该女已入僧团出家不可追罪，迦毘罗卫城释迦族为此愤愤不平，恶言四起。优波离得知请问佛陀道："世尊！犯了国法的人，僧团可以收她出家吗？佛陀回答道："优波离！犯了国法，在没有宣判无罪前，僧团不可收她出家！“犯了国法，自应受国法制裁，为了健全僧团，戒法不抵触国法。

律藏中有一则僧残戒(僧伽婆尸沙Sanghadisesa次重罪，犯者被停止僧权,应离去，但自己告白忏悔后，回复清净。)-任何比丘,为人说媒,为人传达情意,或促成夫妇，或是一次的男女关系者,僧残。(见《汉译南传大藏经》.经分别.僧残5。《大正藏》四分律.卷三)这是因为有位优陀夷比丘(或说是迦罗比丘)因为人说媒，后来夫妇不和，夫人吵着要回娘家，大家把过错指向媒人，造成困扰。优波离就请教佛陀这个问题："世尊！比丘和比丘尼可以为社会男女做媒吗？"佛陀回答道："优波离！若比丘、比丘尼持男意至女边，持女意至男边，乃至介绍，这就犯了僧残，需要悔过。"

随着出家僧众多，犯戒的人也不少。《律藏》中常见到恶比丘中的优陀夷，比丘尼中的偷兰难陀等人，常在僧团里挑起争端，制造矛盾。佛陀就派能辨别是非，主持公道的优波离，到各处调解纠纷。优波离息诤的原则：'彼处诤事彼处断'。不把争端的事扩大，不将争端的话传播。

一切行无常，比丘们也是有老病死；优波离见到一个病比丘躺卧在粪秽中不能自理；也有一个病比丘卧在路旁，其它比丘特地绕道而行，不愿看病。优波离请问佛陀道："佛陀！若有大德比丘病时，应如何去慰问看视？"佛陀回答道：“大德比丘生病时，不应住在陋小的房中，应住在阳光空气流通的房中，弟子要常侍在左右，洒扫房中，插花烧香，随时听他的呼吸，同修比丘前来问病，应以饮食供养问病比丘，若有所问，病者应答；病人力弱，没有精神讲话，侍者代答。慰问时要能随顺说法，能为病人服务一切，能满足病人所需饮食汤药。若是在家信众前来问病，请其坐后，即为说法；若有供养，即为念佛祝愿接受。

小德比丘病时，他的师长或弟子都应该来看视，假使他没有师长弟子，同住的僧众应该差人看病，看病人数在三人之间，病人如要医药饮食，看病的人应该服侍供给，若是没有，大众应供给，大众也没有，应取病人有价值的衣钵易取饮食医药，若无法贸易，大众应乞化供给，如不能乞得，在僧食中应取好的给予，僧食中没有好食，看病的人应持二钵到聚落中乞食，将好的供养病人！”

优波离洁身清净，能问戒持戒，有心修道者都欢喜恭敬，但那些不守规矩不持戒的人，就不会喜欢，甚至也有恶意批评他的人！

有一次，优波离和一些持戒如法比丘到各处去行脚弘化，他们发扬持戒精神，对于诃责羯摩、驱出羯摩、依止羯摩、举罪羯摩等的忏悔法，羯摩就是由长老开会讨论，对犯者举罪处理或忏悔之。有一些比丘听到优波离来，就非常不欢喜，他们私下说："现在优波离持戒比丘将要到来，他来了以后，一定会教诫我们什么应作，什么不应作，我们应该设去阻止，使他不要来！当他来时，把门户关起来，把卧具挂在门口，不理睬他！或当他来时，我们可以到别处去！"

优波离的严持戒律，生活上清净不犯，使得他与女众的关系，不大友好。传说他与持律者外出游行，尼众多沿路瞋骂他，使他乞食难得（"五分律"十八）。

有位差摩比丘尼命终，诸比丘尼在比丘僧坊中砌造骨塔，其眷属来此地围绕啼哭，让诸比丘无法坐禅行道。这时优波离来到僧坊，问明事由，即使人破坏之。诸比丘尼持杖见比丘便打。又狭路逢上优波离，举杖欲打。优波离以此投诉佛陀。佛陀制戒比丘尼非正事不得入比丘住处。（"五分律"十三）。

有一次，有一位时常犯错的偷兰难陀比丘尼，竟然当面骂优波离道："这不是真修道的人，专门喜欢兴风作浪，什么此该作，彼不该作，使我们生活增加不少困难和苦恼！"佛陀知道后，马上召集诸比丘，责问："你们对优波离比丘拒绝欢迎，甚至对他避不见面，瞋怒恶口大骂，真有这样的事吗？"这一群比丘、比丘尼在佛陀之前不敢说谎，只得承认说道："世尊！是真的，我们确曾对优波离比丘无礼！"佛陀诃责道："你们真是愚痴，不恭敬持戒比丘，还有谁可恭敬？戒是汝等尊师，戒在则法住，你们不对持戒比丘恭敬，就证明你们有非法的企图！"

佛陀又说:“诸位比丘们，有三种可以增长正法的学问非常的重要。哪三种呢？那就是增上戒学丶增上意学丶和增上慧学。

什么是增上戒学呢？如果比丘能安住在戒律上，行止坐卧具足威仪，看见微细之罪，就能心生怖畏，是故要接受持用学戒，这名叫增上戒学。

什么是增上意学呢？如果比丘能远离诸恶的不善之法，有觉知有观照，进而拒绝远离它而生起喜乐，如此的从初禅丶二禅丶三禅乃至四禅，就名叫做增上意学。

什么是增上慧学呢？如果比丘对于苦圣谛能确实觉知，对于苦集圣谛(苦的原因)，对于苦灭圣谛(消除苦的源头得到寂静涅盘)，对于苦灭道圣谛(达到寂静涅盘的八正道)，都能确实明了，就名叫做增上慧学。“(大正藏二册卷30-832)

戒定慧三学是一致的，无论是舍利弗的慧解脱，大迦叶的定解脱或持戒第一的优波离，他们都是俱解脱的长老。

** 结集大会诵出戒律

佛陀涅槃的时，优波离大约有七十多岁的高龄。在南传巴利《长部》的《大般涅盘经》，以及《长阿含、游行经》等说有比丘言："佛陀在世常言：应行是不应行是，应学是不应学是。我等于今始脱此苦，任意所为，无复拘碍"。大迦叶有感小戒不应舍，故发起在王舍城主持结集经典的大会，诸大弟子们由大迦叶为上首，公推优波离颂出律藏，阿难颂出经藏，每一条目都说明此戒佛陀于何时、何地、对何人，以何因缘而制，以及犯了此戒有罪无罪的程度，如此一日誦一律，分八十次誦出根本律法，而結集出律藏，就是所謂的《八十誦》(后来归纳八十诵律而成十诵律，至其后四分律丶五分律等诸律，由此分立)，是佛教中最原始的戒律。戒法称之”波罗提木叉(巴利语patimokkha意译为随顺解脱、处处解脱、别解脱)“，是佛陀為調伏弟子煩惱，對治生活惡習所制定的教團規則，所制的成文法典。佛陀世有半月诵波罗提木叉的制度，推论应早就有了编集。但波罗提木叉是因事立制，是隨犯隨制，属隨緣制戒，所以不断增加，逐渐完成的。

在这次结集中，优波离的保守态度取得大成果，毘尼(又译为毗奈耶vinaya，戒律之总名)取得了优先的地位，'王舍结集，实以集毘尼为首要任务（出经为次要的）。大迦叶发起结集的原因，为了毘尼；首先诵出的，是毘尼；大会责难阿难的，也有关毘尼...对戒法，否决小小戒可舍...逐渐完成严格而琐碎的规律。对尼众，采取严厉管教的态度，树立尼众绝对尊敬男众的制度。上座的权威也提高了...优波离同情头陀行，生活谨严，与尼众的关系不佳，这与大迦叶相近。这所以能互相和合，主持王舍结集...在大迦叶的主导下，优波离学系成为实质的佛教中心。'(见印顺著-戒律的分歧)。

优波离是一个出身下贱首陀罗种姓的理发师，用戒慎恐惧的心丶安稳平息的手操着剃头刀;出家后,同样以如临深渊丶如屡薄冰的言行，在僧团里中得到那么崇高的地位，乃至能由他主持律藏结集，千秋万世让四众弟子景仰！

* 生活禅修故事系列
https://tieba.baidu.com/p/2181971342
